// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: agent_logout.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Agent登出消息
type AgentLogout struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	PluginName    string                 `protobuf:"bytes,2,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentLogout) Reset() {
	*x = AgentLogout{}
	mi := &file_agent_logout_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentLogout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentLogout) ProtoMessage() {}

func (x *AgentLogout) ProtoReflect() protoreflect.Message {
	mi := &file_agent_logout_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentLogout.ProtoReflect.Descriptor instead.
func (*AgentLogout) Descriptor() ([]byte, []int) {
	return file_agent_logout_proto_rawDescGZIP(), []int{0}
}

func (x *AgentLogout) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentLogout) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

var File_agent_logout_proto protoreflect.FileDescriptor

const file_agent_logout_proto_rawDesc = "" +
	"\n" +
	"\x12agent_logout.proto\"I\n" +
	"\vAgentLogout\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1f\n" +
	"\vplugin_name\x18\x02 \x01(\tR\n" +
	"pluginNameB)\n" +
	"\n" +
	"sothoth.pbP\x01Z\x19sothoth-nodeagent/pkg/pb/b\x06proto3"

var (
	file_agent_logout_proto_rawDescOnce sync.Once
	file_agent_logout_proto_rawDescData []byte
)

func file_agent_logout_proto_rawDescGZIP() []byte {
	file_agent_logout_proto_rawDescOnce.Do(func() {
		file_agent_logout_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_logout_proto_rawDesc), len(file_agent_logout_proto_rawDesc)))
	})
	return file_agent_logout_proto_rawDescData
}

var file_agent_logout_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_agent_logout_proto_goTypes = []any{
	(*AgentLogout)(nil), // 0: AgentLogout
}
var file_agent_logout_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_agent_logout_proto_init() }
func file_agent_logout_proto_init() {
	if File_agent_logout_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_logout_proto_rawDesc), len(file_agent_logout_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agent_logout_proto_goTypes,
		DependencyIndexes: file_agent_logout_proto_depIdxs,
		MessageInfos:      file_agent_logout_proto_msgTypes,
	}.Build()
	File_agent_logout_proto = out.File
	file_agent_logout_proto_goTypes = nil
	file_agent_logout_proto_depIdxs = nil
}
