// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: datasource.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DatabaseCatalogOperation int32

const (
	DatabaseCatalogOperation_LIST_DATABASES DatabaseCatalogOperation = 0
	DatabaseCatalogOperation_LIST_TABLES    DatabaseCatalogOperation = 1
	DatabaseCatalogOperation_DESCRIBE_TABLE DatabaseCatalogOperation = 2
)

// Enum value maps for DatabaseCatalogOperation.
var (
	DatabaseCatalogOperation_name = map[int32]string{
		0: "LIST_DATABASES",
		1: "LIST_TABLES",
		2: "DESCRIBE_TABLE",
	}
	DatabaseCatalogOperation_value = map[string]int32{
		"LIST_DATABASES": 0,
		"LIST_TABLES":    1,
		"DESCRIBE_TABLE": 2,
	}
)

func (x DatabaseCatalogOperation) Enum() *DatabaseCatalogOperation {
	p := new(DatabaseCatalogOperation)
	*p = x
	return p
}

func (x DatabaseCatalogOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DatabaseCatalogOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_datasource_proto_enumTypes[0].Descriptor()
}

func (DatabaseCatalogOperation) Type() protoreflect.EnumType {
	return &file_datasource_proto_enumTypes[0]
}

func (x DatabaseCatalogOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DatabaseCatalogOperation.Descriptor instead.
func (DatabaseCatalogOperation) EnumDescriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{0}
}

type DatasourceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	DbType        string                 `protobuf:"bytes,5,opt,name=db_type,json=dbType,proto3" json:"db_type,omitempty"`
	PoolType      string                 `protobuf:"bytes,6,opt,name=pool_type,json=poolType,proto3" json:"pool_type,omitempty"`
	PoolClass     string                 `protobuf:"bytes,7,opt,name=pool_class,json=poolClass,proto3" json:"pool_class,omitempty"`
	ConnectedDb   string                 `protobuf:"bytes,8,opt,name=connected_db,json=connectedDb,proto3" json:"connected_db,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatasourceInfo) Reset() {
	*x = DatasourceInfo{}
	mi := &file_datasource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatasourceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatasourceInfo) ProtoMessage() {}

func (x *DatasourceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatasourceInfo.ProtoReflect.Descriptor instead.
func (*DatasourceInfo) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{0}
}

func (x *DatasourceInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DatasourceInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DatasourceInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DatasourceInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *DatasourceInfo) GetDbType() string {
	if x != nil {
		return x.DbType
	}
	return ""
}

func (x *DatasourceInfo) GetPoolType() string {
	if x != nil {
		return x.PoolType
	}
	return ""
}

func (x *DatasourceInfo) GetPoolClass() string {
	if x != nil {
		return x.PoolClass
	}
	return ""
}

func (x *DatasourceInfo) GetConnectedDb() string {
	if x != nil {
		return x.ConnectedDb
	}
	return ""
}

type DatasourceListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datasources   []*DatasourceInfo      `protobuf:"bytes,1,rep,name=datasources,proto3" json:"datasources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatasourceListResponse) Reset() {
	*x = DatasourceListResponse{}
	mi := &file_datasource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatasourceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatasourceListResponse) ProtoMessage() {}

func (x *DatasourceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatasourceListResponse.ProtoReflect.Descriptor instead.
func (*DatasourceListResponse) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{1}
}

func (x *DatasourceListResponse) GetDatasources() []*DatasourceInfo {
	if x != nil {
		return x.Datasources
	}
	return nil
}

type DatabaseCatalogRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	DatasourceId  string                   `protobuf:"bytes,1,opt,name=datasource_id,json=datasourceId,proto3" json:"datasource_id,omitempty"`
	Operation     DatabaseCatalogOperation `protobuf:"varint,2,opt,name=operation,proto3,enum=DatabaseCatalogOperation" json:"operation,omitempty"`
	Database      string                   `protobuf:"bytes,3,opt,name=database,proto3" json:"database,omitempty"`
	Table         string                   `protobuf:"bytes,4,opt,name=table,proto3" json:"table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseCatalogRequest) Reset() {
	*x = DatabaseCatalogRequest{}
	mi := &file_datasource_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseCatalogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseCatalogRequest) ProtoMessage() {}

func (x *DatabaseCatalogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseCatalogRequest.ProtoReflect.Descriptor instead.
func (*DatabaseCatalogRequest) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{2}
}

func (x *DatabaseCatalogRequest) GetDatasourceId() string {
	if x != nil {
		return x.DatasourceId
	}
	return ""
}

func (x *DatabaseCatalogRequest) GetOperation() DatabaseCatalogOperation {
	if x != nil {
		return x.Operation
	}
	return DatabaseCatalogOperation_LIST_DATABASES
}

func (x *DatabaseCatalogRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *DatabaseCatalogRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_datasource_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{3}
}

func (x *Row) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type DatabaseCatalogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []string               `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	Rows          []*Row                 `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseCatalogResponse) Reset() {
	*x = DatabaseCatalogResponse{}
	mi := &file_datasource_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseCatalogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseCatalogResponse) ProtoMessage() {}

func (x *DatabaseCatalogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseCatalogResponse.ProtoReflect.Descriptor instead.
func (*DatabaseCatalogResponse) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{4}
}

func (x *DatabaseCatalogResponse) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *DatabaseCatalogResponse) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *DatabaseCatalogResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DatabaseExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatasourceId  string                 `protobuf:"bytes,1,opt,name=datasource_id,json=datasourceId,proto3" json:"datasource_id,omitempty"`
	Sql           string                 `protobuf:"bytes,2,opt,name=sql,proto3" json:"sql,omitempty"`
	Database      string                 `protobuf:"bytes,3,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseExecuteRequest) Reset() {
	*x = DatabaseExecuteRequest{}
	mi := &file_datasource_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseExecuteRequest) ProtoMessage() {}

func (x *DatabaseExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseExecuteRequest.ProtoReflect.Descriptor instead.
func (*DatabaseExecuteRequest) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{5}
}

func (x *DatabaseExecuteRequest) GetDatasourceId() string {
	if x != nil {
		return x.DatasourceId
	}
	return ""
}

func (x *DatabaseExecuteRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *DatabaseExecuteRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

type DatabaseExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []string               `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	Rows          []*Row                 `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	RowCount      int64                  `protobuf:"varint,4,opt,name=row_count,json=rowCount,proto3" json:"row_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseExecuteResponse) Reset() {
	*x = DatabaseExecuteResponse{}
	mi := &file_datasource_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseExecuteResponse) ProtoMessage() {}

func (x *DatabaseExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseExecuteResponse.ProtoReflect.Descriptor instead.
func (*DatabaseExecuteResponse) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{6}
}

func (x *DatabaseExecuteResponse) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *DatabaseExecuteResponse) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *DatabaseExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DatabaseExecuteResponse) GetRowCount() int64 {
	if x != nil {
		return x.RowCount
	}
	return 0
}

var File_datasource_proto protoreflect.FileDescriptor

const file_datasource_proto_rawDesc = "" +
	"\n" +
	"\x10datasource.proto\"\xe2\x01\n" +
	"\x0eDatasourceInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x17\n" +
	"\adb_type\x18\x05 \x01(\tR\x06dbType\x12\x1b\n" +
	"\tpool_type\x18\x06 \x01(\tR\bpoolType\x12\x1d\n" +
	"\n" +
	"pool_class\x18\a \x01(\tR\tpoolClass\x12!\n" +
	"\fconnected_db\x18\b \x01(\tR\vconnectedDb\"K\n" +
	"\x16DatasourceListResponse\x121\n" +
	"\vdatasources\x18\x01 \x03(\v2\x0f.DatasourceInfoR\vdatasources\"\xa8\x01\n" +
	"\x16DatabaseCatalogRequest\x12#\n" +
	"\rdatasource_id\x18\x01 \x01(\tR\fdatasourceId\x127\n" +
	"\toperation\x18\x02 \x01(\x0e2\x19.DatabaseCatalogOperationR\toperation\x12\x1a\n" +
	"\bdatabase\x18\x03 \x01(\tR\bdatabase\x12\x14\n" +
	"\x05table\x18\x04 \x01(\tR\x05table\"\x1d\n" +
	"\x03Row\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"c\n" +
	"\x17DatabaseCatalogResponse\x12\x18\n" +
	"\acolumns\x18\x01 \x03(\tR\acolumns\x12\x18\n" +
	"\x04rows\x18\x02 \x03(\v2\x04.RowR\x04rows\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"k\n" +
	"\x16DatabaseExecuteRequest\x12#\n" +
	"\rdatasource_id\x18\x01 \x01(\tR\fdatasourceId\x12\x10\n" +
	"\x03sql\x18\x02 \x01(\tR\x03sql\x12\x1a\n" +
	"\bdatabase\x18\x03 \x01(\tR\bdatabase\"\x80\x01\n" +
	"\x17DatabaseExecuteResponse\x12\x18\n" +
	"\acolumns\x18\x01 \x03(\tR\acolumns\x12\x18\n" +
	"\x04rows\x18\x02 \x03(\v2\x04.RowR\x04rows\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1b\n" +
	"\trow_count\x18\x04 \x01(\x03R\browCount*S\n" +
	"\x18DatabaseCatalogOperation\x12\x12\n" +
	"\x0eLIST_DATABASES\x10\x00\x12\x0f\n" +
	"\vLIST_TABLES\x10\x01\x12\x12\n" +
	"\x0eDESCRIBE_TABLE\x10\x02B)\n" +
	"\n" +
	"gaiasec.pbP\x01Z\x19gaiasec-nodeagent/pkg/pb/b\x06proto3"

var (
	file_datasource_proto_rawDescOnce sync.Once
	file_datasource_proto_rawDescData []byte
)

func file_datasource_proto_rawDescGZIP() []byte {
	file_datasource_proto_rawDescOnce.Do(func() {
		file_datasource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_datasource_proto_rawDesc), len(file_datasource_proto_rawDesc)))
	})
	return file_datasource_proto_rawDescData
}

var file_datasource_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_datasource_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_datasource_proto_goTypes = []any{
	(DatabaseCatalogOperation)(0),   // 0: DatabaseCatalogOperation
	(*DatasourceInfo)(nil),          // 1: DatasourceInfo
	(*DatasourceListResponse)(nil),  // 2: DatasourceListResponse
	(*DatabaseCatalogRequest)(nil),  // 3: DatabaseCatalogRequest
	(*Row)(nil),                     // 4: Row
	(*DatabaseCatalogResponse)(nil), // 5: DatabaseCatalogResponse
	(*DatabaseExecuteRequest)(nil),  // 6: DatabaseExecuteRequest
	(*DatabaseExecuteResponse)(nil), // 7: DatabaseExecuteResponse
}
var file_datasource_proto_depIdxs = []int32{
	1, // 0: DatasourceListResponse.datasources:type_name -> DatasourceInfo
	0, // 1: DatabaseCatalogRequest.operation:type_name -> DatabaseCatalogOperation
	4, // 2: DatabaseCatalogResponse.rows:type_name -> Row
	4, // 3: DatabaseExecuteResponse.rows:type_name -> Row
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_datasource_proto_init() }
func file_datasource_proto_init() {
	if File_datasource_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datasource_proto_rawDesc), len(file_datasource_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_datasource_proto_goTypes,
		DependencyIndexes: file_datasource_proto_depIdxs,
		EnumInfos:         file_datasource_proto_enumTypes,
		MessageInfos:      file_datasource_proto_msgTypes,
	}.Build()
	File_datasource_proto = out.File
	file_datasource_proto_goTypes = nil
	file_datasource_proto_depIdxs = nil
}
