// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: escape.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 容器挂载信息
type ContainerMount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Driver        string                 `protobuf:"bytes,4,opt,name=driver,proto3" json:"driver,omitempty"`
	IsDangerous   bool                   `protobuf:"varint,5,opt,name=is_dangerous,json=isDangerous,proto3" json:"is_dangerous,omitempty"` // nodeagent 初步标记为危险
	RiskReason    string                 `protobuf:"bytes,6,opt,name=risk_reason,json=riskReason,proto3" json:"risk_reason,omitempty"`     // 危险原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerMount) Reset() {
	*x = ContainerMount{}
	mi := &file_escape_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerMount) ProtoMessage() {}

func (x *ContainerMount) ProtoReflect() protoreflect.Message {
	mi := &file_escape_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerMount.ProtoReflect.Descriptor instead.
func (*ContainerMount) Descriptor() ([]byte, []int) {
	return file_escape_proto_rawDescGZIP(), []int{0}
}

func (x *ContainerMount) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ContainerMount) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *ContainerMount) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ContainerMount) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *ContainerMount) GetIsDangerous() bool {
	if x != nil {
		return x.IsDangerous
	}
	return false
}

func (x *ContainerMount) GetRiskReason() string {
	if x != nil {
		return x.RiskReason
	}
	return ""
}

// 容器 capabilities
type ContainerCapability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	IsDangerous   bool                   `protobuf:"varint,3,opt,name=is_dangerous,json=isDangerous,proto3" json:"is_dangerous,omitempty"` // nodeagent 初步标记为危险
	RiskReason    string                 `protobuf:"bytes,4,opt,name=risk_reason,json=riskReason,proto3" json:"risk_reason,omitempty"`     // 危险原因
	IsDefault     bool                   `protobuf:"varint,5,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`       // 是否默认开启的 capability
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerCapability) Reset() {
	*x = ContainerCapability{}
	mi := &file_escape_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerCapability) ProtoMessage() {}

func (x *ContainerCapability) ProtoReflect() protoreflect.Message {
	mi := &file_escape_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerCapability.ProtoReflect.Descriptor instead.
func (*ContainerCapability) Descriptor() ([]byte, []int) {
	return file_escape_proto_rawDescGZIP(), []int{1}
}

func (x *ContainerCapability) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerCapability) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ContainerCapability) GetIsDangerous() bool {
	if x != nil {
		return x.IsDangerous
	}
	return false
}

func (x *ContainerCapability) GetRiskReason() string {
	if x != nil {
		return x.RiskReason
	}
	return ""
}

func (x *ContainerCapability) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

// 容器逃逸分析结果
type ContainerEscapeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	ContainerName string                 `protobuf:"bytes,2,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	// 容器安全配置
	HostPid     bool   `protobuf:"varint,3,opt,name=host_pid,json=hostPid,proto3" json:"host_pid,omitempty"`
	HostNetwork bool   `protobuf:"varint,4,opt,name=host_network,json=hostNetwork,proto3" json:"host_network,omitempty"`
	HostIpc     bool   `protobuf:"varint,5,opt,name=host_ipc,json=hostIpc,proto3" json:"host_ipc,omitempty"`
	HostUts     bool   `protobuf:"varint,6,opt,name=host_uts,json=hostUts,proto3" json:"host_uts,omitempty"`
	Privileged  bool   `protobuf:"varint,7,opt,name=privileged,proto3" json:"privileged,omitempty"`
	User        string `protobuf:"bytes,8,opt,name=user,proto3" json:"user,omitempty"`
	// 挂载信息 (全部上报，加风险标记)
	Mounts []*ContainerMount `protobuf:"bytes,10,rep,name=mounts,proto3" json:"mounts,omitempty"`
	// capabilities (全部上报，加风险标记)
	Capabilities []*ContainerCapability `protobuf:"bytes,11,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// 网络模式
	NetworkMode string `protobuf:"bytes,12,opt,name=network_mode,json=networkMode,proto3" json:"network_mode,omitempty"`
	// 运行时
	Runtime string `protobuf:"bytes,13,opt,name=runtime,proto3" json:"runtime,omitempty"`
	// 镜像名
	Image string `protobuf:"bytes,16,opt,name=image,proto3" json:"image,omitempty"`
	// 初步风险评估
	HasHighRisk   bool   `protobuf:"varint,14,opt,name=has_high_risk,json=hasHighRisk,proto3" json:"has_high_risk,omitempty"`
	RiskSummary   string `protobuf:"bytes,15,opt,name=risk_summary,json=riskSummary,proto3" json:"risk_summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerEscapeInfo) Reset() {
	*x = ContainerEscapeInfo{}
	mi := &file_escape_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerEscapeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerEscapeInfo) ProtoMessage() {}

func (x *ContainerEscapeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_escape_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerEscapeInfo.ProtoReflect.Descriptor instead.
func (*ContainerEscapeInfo) Descriptor() ([]byte, []int) {
	return file_escape_proto_rawDescGZIP(), []int{2}
}

func (x *ContainerEscapeInfo) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerEscapeInfo) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *ContainerEscapeInfo) GetHostPid() bool {
	if x != nil {
		return x.HostPid
	}
	return false
}

func (x *ContainerEscapeInfo) GetHostNetwork() bool {
	if x != nil {
		return x.HostNetwork
	}
	return false
}

func (x *ContainerEscapeInfo) GetHostIpc() bool {
	if x != nil {
		return x.HostIpc
	}
	return false
}

func (x *ContainerEscapeInfo) GetHostUts() bool {
	if x != nil {
		return x.HostUts
	}
	return false
}

func (x *ContainerEscapeInfo) GetPrivileged() bool {
	if x != nil {
		return x.Privileged
	}
	return false
}

func (x *ContainerEscapeInfo) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ContainerEscapeInfo) GetMounts() []*ContainerMount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

func (x *ContainerEscapeInfo) GetCapabilities() []*ContainerCapability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ContainerEscapeInfo) GetNetworkMode() string {
	if x != nil {
		return x.NetworkMode
	}
	return ""
}

func (x *ContainerEscapeInfo) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *ContainerEscapeInfo) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerEscapeInfo) GetHasHighRisk() bool {
	if x != nil {
		return x.HasHighRisk
	}
	return false
}

func (x *ContainerEscapeInfo) GetRiskSummary() string {
	if x != nil {
		return x.RiskSummary
	}
	return ""
}

// 容器逃逸请求
type ContainerEscapeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"` // 可选，不指定则分析所有容器
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerEscapeRequest) Reset() {
	*x = ContainerEscapeRequest{}
	mi := &file_escape_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerEscapeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerEscapeRequest) ProtoMessage() {}

func (x *ContainerEscapeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_escape_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerEscapeRequest.ProtoReflect.Descriptor instead.
func (*ContainerEscapeRequest) Descriptor() ([]byte, []int) {
	return file_escape_proto_rawDescGZIP(), []int{3}
}

func (x *ContainerEscapeRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

// 容器逃逸响应
type ContainerEscapeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*ContainerEscapeInfo `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerEscapeResponse) Reset() {
	*x = ContainerEscapeResponse{}
	mi := &file_escape_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerEscapeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerEscapeResponse) ProtoMessage() {}

func (x *ContainerEscapeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_escape_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerEscapeResponse.ProtoReflect.Descriptor instead.
func (*ContainerEscapeResponse) Descriptor() ([]byte, []int) {
	return file_escape_proto_rawDescGZIP(), []int{4}
}

func (x *ContainerEscapeResponse) GetContainers() []*ContainerEscapeInfo {
	if x != nil {
		return x.Containers
	}
	return nil
}

// SUID/SGID 文件信息
type SuidBinary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Owner         string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Group         string                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	IsSuid        bool                   `protobuf:"varint,4,opt,name=is_suid,json=isSuid,proto3" json:"is_suid,omitempty"`
	IsSgid        bool                   `protobuf:"varint,5,opt,name=is_sgid,json=isSgid,proto3" json:"is_sgid,omitempty"`
	IsDangerous   bool                   `protobuf:"varint,6,opt,name=is_dangerous,json=isDangerous,proto3" json:"is_dangerous,omitempty"`
	RiskReason    string                 `protobuf:"bytes,7,opt,name=risk_reason,json=riskReason,proto3" json:"risk_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuidBinary) Reset() {
	*x = SuidBinary{}
	mi := &file_escape_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuidBinary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuidBinary) ProtoMessage() {}

func (x *SuidBinary) ProtoReflect() protoreflect.Message {
	mi := &file_escape_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuidBinary.ProtoReflect.Descriptor instead.
func (*SuidBinary) Descriptor() ([]byte, []int) {
	return file_escape_proto_rawDescGZIP(), []int{5}
}

func (x *SuidBinary) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SuidBinary) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *SuidBinary) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *SuidBinary) GetIsSuid() bool {
	if x != nil {
		return x.IsSuid
	}
	return false
}

func (x *SuidBinary) GetIsSgid() bool {
	if x != nil {
		return x.IsSgid
	}
	return false
}

func (x *SuidBinary) GetIsDangerous() bool {
	if x != nil {
		return x.IsDangerous
	}
	return false
}

func (x *SuidBinary) GetRiskReason() string {
	if x != nil {
		return x.RiskReason
	}
	return ""
}

// sudo 配置
type SudoConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	User           string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Host           string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Runas          string                 `protobuf:"bytes,3,opt,name=runas,proto3" json:"runas,omitempty"`
	Command        string                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	IsPasswordless bool                   `protobuf:"varint,5,opt,name=is_passwordless,json=isPasswordless,proto3" json:"is_passwordless,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SudoConfig) Reset() {
	*x = SudoConfig{}
	mi := &file_escape_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SudoConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SudoConfig) ProtoMessage() {}

func (x *SudoConfig) ProtoReflect() protoreflect.Message {
	mi := &file_escape_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SudoConfig.ProtoReflect.Descriptor instead.
func (*SudoConfig) Descriptor() ([]byte, []int) {
	return file_escape_proto_rawDescGZIP(), []int{6}
}

func (x *SudoConfig) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *SudoConfig) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *SudoConfig) GetRunas() string {
	if x != nil {
		return x.Runas
	}
	return ""
}

func (x *SudoConfig) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *SudoConfig) GetIsPasswordless() bool {
	if x != nil {
		return x.IsPasswordless
	}
	return false
}

// 本地提权分析结果
type PrivilegeEscalationInfo struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	NodeName string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	// 当前用户信息
	CurrentUser string   `protobuf:"bytes,2,opt,name=current_user,json=currentUser,proto3" json:"current_user,omitempty"`
	CurrentUid  int32    `protobuf:"varint,3,opt,name=current_uid,json=currentUid,proto3" json:"current_uid,omitempty"`
	CurrentGid  int32    `protobuf:"varint,4,opt,name=current_gid,json=currentGid,proto3" json:"current_gid,omitempty"`
	Groups      []string `protobuf:"bytes,5,rep,name=groups,proto3" json:"groups,omitempty"`
	// SUID/SGID 可执行文件
	SuidBinaries []*SuidBinary `protobuf:"bytes,10,rep,name=suid_binaries,json=suidBinaries,proto3" json:"suid_binaries,omitempty"`
	// sudo 配置
	SudoConfig []*SudoConfig `protobuf:"bytes,11,rep,name=sudo_config,json=sudoConfig,proto3" json:"sudo_config,omitempty"`
	// 当前进程 capabilities
	Capabilities []*ContainerCapability `protobuf:"bytes,12,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// 可写入的敏感文件
	WritableSensitiveFiles []string `protobuf:"bytes,13,rep,name=writable_sensitive_files,json=writableSensitiveFiles,proto3" json:"writable_sensitive_files,omitempty"`
	// 环境变量中的敏感信息
	SensitiveEnvVars []string `protobuf:"bytes,14,rep,name=sensitive_env_vars,json=sensitiveEnvVars,proto3" json:"sensitive_env_vars,omitempty"`
	// 初步风险评估
	HasHighRisk   bool   `protobuf:"varint,15,opt,name=has_high_risk,json=hasHighRisk,proto3" json:"has_high_risk,omitempty"`
	RiskSummary   string `protobuf:"bytes,16,opt,name=risk_summary,json=riskSummary,proto3" json:"risk_summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrivilegeEscalationInfo) Reset() {
	*x = PrivilegeEscalationInfo{}
	mi := &file_escape_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivilegeEscalationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivilegeEscalationInfo) ProtoMessage() {}

func (x *PrivilegeEscalationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_escape_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivilegeEscalationInfo.ProtoReflect.Descriptor instead.
func (*PrivilegeEscalationInfo) Descriptor() ([]byte, []int) {
	return file_escape_proto_rawDescGZIP(), []int{7}
}

func (x *PrivilegeEscalationInfo) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *PrivilegeEscalationInfo) GetCurrentUser() string {
	if x != nil {
		return x.CurrentUser
	}
	return ""
}

func (x *PrivilegeEscalationInfo) GetCurrentUid() int32 {
	if x != nil {
		return x.CurrentUid
	}
	return 0
}

func (x *PrivilegeEscalationInfo) GetCurrentGid() int32 {
	if x != nil {
		return x.CurrentGid
	}
	return 0
}

func (x *PrivilegeEscalationInfo) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *PrivilegeEscalationInfo) GetSuidBinaries() []*SuidBinary {
	if x != nil {
		return x.SuidBinaries
	}
	return nil
}

func (x *PrivilegeEscalationInfo) GetSudoConfig() []*SudoConfig {
	if x != nil {
		return x.SudoConfig
	}
	return nil
}

func (x *PrivilegeEscalationInfo) GetCapabilities() []*ContainerCapability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *PrivilegeEscalationInfo) GetWritableSensitiveFiles() []string {
	if x != nil {
		return x.WritableSensitiveFiles
	}
	return nil
}

func (x *PrivilegeEscalationInfo) GetSensitiveEnvVars() []string {
	if x != nil {
		return x.SensitiveEnvVars
	}
	return nil
}

func (x *PrivilegeEscalationInfo) GetHasHighRisk() bool {
	if x != nil {
		return x.HasHighRisk
	}
	return false
}

func (x *PrivilegeEscalationInfo) GetRiskSummary() string {
	if x != nil {
		return x.RiskSummary
	}
	return ""
}

// 本地提权请求
type PrivilegeEscalationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrivilegeEscalationRequest) Reset() {
	*x = PrivilegeEscalationRequest{}
	mi := &file_escape_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivilegeEscalationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivilegeEscalationRequest) ProtoMessage() {}

func (x *PrivilegeEscalationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_escape_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivilegeEscalationRequest.ProtoReflect.Descriptor instead.
func (*PrivilegeEscalationRequest) Descriptor() ([]byte, []int) {
	return file_escape_proto_rawDescGZIP(), []int{8}
}

// 本地提权响应
type PrivilegeEscalationResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Info          *PrivilegeEscalationInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrivilegeEscalationResponse) Reset() {
	*x = PrivilegeEscalationResponse{}
	mi := &file_escape_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivilegeEscalationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivilegeEscalationResponse) ProtoMessage() {}

func (x *PrivilegeEscalationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_escape_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivilegeEscalationResponse.ProtoReflect.Descriptor instead.
func (*PrivilegeEscalationResponse) Descriptor() ([]byte, []int) {
	return file_escape_proto_rawDescGZIP(), []int{9}
}

func (x *PrivilegeEscalationResponse) GetInfo() *PrivilegeEscalationInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// ClusterRoleBinding 信息
type ClusterRoleBindingInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RoleKind        string                 `protobuf:"bytes,2,opt,name=role_kind,json=roleKind,proto3" json:"role_kind,omitempty"` // ClusterRole or Role
	RoleName        string                 `protobuf:"bytes,3,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	Subjects        []string               `protobuf:"bytes,4,rep,name=subjects,proto3" json:"subjects,omitempty"`
	CanPrivilegeEsc bool                   `protobuf:"varint,5,opt,name=can_privilege_esc,json=canPrivilegeEsc,proto3" json:"can_privilege_esc,omitempty"`
	RiskReason      string                 `protobuf:"bytes,6,opt,name=risk_reason,json=riskReason,proto3" json:"risk_reason,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClusterRoleBindingInfo) Reset() {
	*x = ClusterRoleBindingInfo{}
	mi := &file_escape_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterRoleBindingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterRoleBindingInfo) ProtoMessage() {}

func (x *ClusterRoleBindingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_escape_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterRoleBindingInfo.ProtoReflect.Descriptor instead.
func (*ClusterRoleBindingInfo) Descriptor() ([]byte, []int) {
	return file_escape_proto_rawDescGZIP(), []int{10}
}

func (x *ClusterRoleBindingInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClusterRoleBindingInfo) GetRoleKind() string {
	if x != nil {
		return x.RoleKind
	}
	return ""
}

func (x *ClusterRoleBindingInfo) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *ClusterRoleBindingInfo) GetSubjects() []string {
	if x != nil {
		return x.Subjects
	}
	return nil
}

func (x *ClusterRoleBindingInfo) GetCanPrivilegeEsc() bool {
	if x != nil {
		return x.CanPrivilegeEsc
	}
	return false
}

func (x *ClusterRoleBindingInfo) GetRiskReason() string {
	if x != nil {
		return x.RiskReason
	}
	return ""
}

// 可访问的 Secret 信息
type AccessibleSecret struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	SecretType    string                 `protobuf:"bytes,3,opt,name=secret_type,json=secretType,proto3" json:"secret_type,omitempty"`
	CanRead       bool                   `protobuf:"varint,4,opt,name=can_read,json=canRead,proto3" json:"can_read,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessibleSecret) Reset() {
	*x = AccessibleSecret{}
	mi := &file_escape_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessibleSecret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessibleSecret) ProtoMessage() {}

func (x *AccessibleSecret) ProtoReflect() protoreflect.Message {
	mi := &file_escape_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessibleSecret.ProtoReflect.Descriptor instead.
func (*AccessibleSecret) Descriptor() ([]byte, []int) {
	return file_escape_proto_rawDescGZIP(), []int{11}
}

func (x *AccessibleSecret) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccessibleSecret) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *AccessibleSecret) GetSecretType() string {
	if x != nil {
		return x.SecretType
	}
	return ""
}

func (x *AccessibleSecret) GetCanRead() bool {
	if x != nil {
		return x.CanRead
	}
	return false
}

// K8s 提权分析结果
type K8SPrivilegeEscalationInfo struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	NodeName    string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	ClusterName string                 `protobuf:"bytes,2,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	// 当前 Pod 信息
	PodName        string `protobuf:"bytes,3,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	Namespace      string `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ServiceAccount string `protobuf:"bytes,5,opt,name=service_account,json=serviceAccount,proto3" json:"service_account,omitempty"`
	// RBAC 分析
	ClusterRoleBindings []*ClusterRoleBindingInfo `protobuf:"bytes,10,rep,name=cluster_role_bindings,json=clusterRoleBindings,proto3" json:"cluster_role_bindings,omitempty"`
	RoleBindings        []*ClusterRoleBindingInfo `protobuf:"bytes,11,rep,name=role_bindings,json=roleBindings,proto3" json:"role_bindings,omitempty"`
	// 可访问的 Secrets
	AccessibleSecrets []*AccessibleSecret `protobuf:"bytes,12,rep,name=accessible_secrets,json=accessibleSecrets,proto3" json:"accessible_secrets,omitempty"`
	// Token 信息
	TokenExpiration int64  `protobuf:"varint,13,opt,name=token_expiration,json=tokenExpiration,proto3" json:"token_expiration,omitempty"` // 秒，-1 表示永不过期
	TokenFile       string `protobuf:"bytes,14,opt,name=token_file,json=tokenFile,proto3" json:"token_file,omitempty"`
	// 敏感操作权限
	CanExec        bool `protobuf:"varint,15,opt,name=can_exec,json=canExec,proto3" json:"can_exec,omitempty"`
	CanPortForward bool `protobuf:"varint,16,opt,name=can_port_forward,json=canPortForward,proto3" json:"can_port_forward,omitempty"`
	CanCreatePod   bool `protobuf:"varint,17,opt,name=can_create_pod,json=canCreatePod,proto3" json:"can_create_pod,omitempty"`
	CanDeletePod   bool `protobuf:"varint,18,opt,name=can_delete_pod,json=canDeletePod,proto3" json:"can_delete_pod,omitempty"`
	// 初步风险评估
	HasHighRisk   bool   `protobuf:"varint,19,opt,name=has_high_risk,json=hasHighRisk,proto3" json:"has_high_risk,omitempty"`
	RiskSummary   string `protobuf:"bytes,20,opt,name=risk_summary,json=riskSummary,proto3" json:"risk_summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *K8SPrivilegeEscalationInfo) Reset() {
	*x = K8SPrivilegeEscalationInfo{}
	mi := &file_escape_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SPrivilegeEscalationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SPrivilegeEscalationInfo) ProtoMessage() {}

func (x *K8SPrivilegeEscalationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_escape_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SPrivilegeEscalationInfo.ProtoReflect.Descriptor instead.
func (*K8SPrivilegeEscalationInfo) Descriptor() ([]byte, []int) {
	return file_escape_proto_rawDescGZIP(), []int{12}
}

func (x *K8SPrivilegeEscalationInfo) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *K8SPrivilegeEscalationInfo) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *K8SPrivilegeEscalationInfo) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *K8SPrivilegeEscalationInfo) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *K8SPrivilegeEscalationInfo) GetServiceAccount() string {
	if x != nil {
		return x.ServiceAccount
	}
	return ""
}

func (x *K8SPrivilegeEscalationInfo) GetClusterRoleBindings() []*ClusterRoleBindingInfo {
	if x != nil {
		return x.ClusterRoleBindings
	}
	return nil
}

func (x *K8SPrivilegeEscalationInfo) GetRoleBindings() []*ClusterRoleBindingInfo {
	if x != nil {
		return x.RoleBindings
	}
	return nil
}

func (x *K8SPrivilegeEscalationInfo) GetAccessibleSecrets() []*AccessibleSecret {
	if x != nil {
		return x.AccessibleSecrets
	}
	return nil
}

func (x *K8SPrivilegeEscalationInfo) GetTokenExpiration() int64 {
	if x != nil {
		return x.TokenExpiration
	}
	return 0
}

func (x *K8SPrivilegeEscalationInfo) GetTokenFile() string {
	if x != nil {
		return x.TokenFile
	}
	return ""
}

func (x *K8SPrivilegeEscalationInfo) GetCanExec() bool {
	if x != nil {
		return x.CanExec
	}
	return false
}

func (x *K8SPrivilegeEscalationInfo) GetCanPortForward() bool {
	if x != nil {
		return x.CanPortForward
	}
	return false
}

func (x *K8SPrivilegeEscalationInfo) GetCanCreatePod() bool {
	if x != nil {
		return x.CanCreatePod
	}
	return false
}

func (x *K8SPrivilegeEscalationInfo) GetCanDeletePod() bool {
	if x != nil {
		return x.CanDeletePod
	}
	return false
}

func (x *K8SPrivilegeEscalationInfo) GetHasHighRisk() bool {
	if x != nil {
		return x.HasHighRisk
	}
	return false
}

func (x *K8SPrivilegeEscalationInfo) GetRiskSummary() string {
	if x != nil {
		return x.RiskSummary
	}
	return ""
}

// K8s 提权请求
type K8SPrivilegeEscalationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *K8SPrivilegeEscalationRequest) Reset() {
	*x = K8SPrivilegeEscalationRequest{}
	mi := &file_escape_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SPrivilegeEscalationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SPrivilegeEscalationRequest) ProtoMessage() {}

func (x *K8SPrivilegeEscalationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_escape_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SPrivilegeEscalationRequest.ProtoReflect.Descriptor instead.
func (*K8SPrivilegeEscalationRequest) Descriptor() ([]byte, []int) {
	return file_escape_proto_rawDescGZIP(), []int{13}
}

// K8s 提权响应
type K8SPrivilegeEscalationResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Info          *K8SPrivilegeEscalationInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *K8SPrivilegeEscalationResponse) Reset() {
	*x = K8SPrivilegeEscalationResponse{}
	mi := &file_escape_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SPrivilegeEscalationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SPrivilegeEscalationResponse) ProtoMessage() {}

func (x *K8SPrivilegeEscalationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_escape_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SPrivilegeEscalationResponse.ProtoReflect.Descriptor instead.
func (*K8SPrivilegeEscalationResponse) Descriptor() ([]byte, []int) {
	return file_escape_proto_rawDescGZIP(), []int{14}
}

func (x *K8SPrivilegeEscalationResponse) GetInfo() *K8SPrivilegeEscalationInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

var File_escape_proto protoreflect.FileDescriptor

const file_escape_proto_rawDesc = "" +
	"\n" +
	"\fescape.proto\x1a\x12message_type.proto\"\xba\x01\n" +
	"\x0eContainerMount\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06driver\x18\x04 \x01(\tR\x06driver\x12!\n" +
	"\fis_dangerous\x18\x05 \x01(\bR\visDangerous\x12\x1f\n" +
	"\vrisk_reason\x18\x06 \x01(\tR\n" +
	"riskReason\"\xae\x01\n" +
	"\x13ContainerCapability\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12!\n" +
	"\fis_dangerous\x18\x03 \x01(\bR\visDangerous\x12\x1f\n" +
	"\vrisk_reason\x18\x04 \x01(\tR\n" +
	"riskReason\x12\x1d\n" +
	"\n" +
	"is_default\x18\x05 \x01(\bR\tisDefault\"\x84\x04\n" +
	"\x13ContainerEscapeInfo\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12%\n" +
	"\x0econtainer_name\x18\x02 \x01(\tR\rcontainerName\x12\x19\n" +
	"\bhost_pid\x18\x03 \x01(\bR\ahostPid\x12!\n" +
	"\fhost_network\x18\x04 \x01(\bR\vhostNetwork\x12\x19\n" +
	"\bhost_ipc\x18\x05 \x01(\bR\ahostIpc\x12\x19\n" +
	"\bhost_uts\x18\x06 \x01(\bR\ahostUts\x12\x1e\n" +
	"\n" +
	"privileged\x18\a \x01(\bR\n" +
	"privileged\x12\x12\n" +
	"\x04user\x18\b \x01(\tR\x04user\x12'\n" +
	"\x06mounts\x18\n" +
	" \x03(\v2\x0f.ContainerMountR\x06mounts\x128\n" +
	"\fcapabilities\x18\v \x03(\v2\x14.ContainerCapabilityR\fcapabilities\x12!\n" +
	"\fnetwork_mode\x18\f \x01(\tR\vnetworkMode\x12\x18\n" +
	"\aruntime\x18\r \x01(\tR\aruntime\x12\x14\n" +
	"\x05image\x18\x10 \x01(\tR\x05image\x12\"\n" +
	"\rhas_high_risk\x18\x0e \x01(\bR\vhasHighRisk\x12!\n" +
	"\frisk_summary\x18\x0f \x01(\tR\vriskSummary\";\n" +
	"\x16ContainerEscapeRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\"O\n" +
	"\x17ContainerEscapeResponse\x124\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2\x14.ContainerEscapeInfoR\n" +
	"containers\"\xc2\x01\n" +
	"\n" +
	"SuidBinary\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\x12\x17\n" +
	"\ais_suid\x18\x04 \x01(\bR\x06isSuid\x12\x17\n" +
	"\ais_sgid\x18\x05 \x01(\bR\x06isSgid\x12!\n" +
	"\fis_dangerous\x18\x06 \x01(\bR\visDangerous\x12\x1f\n" +
	"\vrisk_reason\x18\a \x01(\tR\n" +
	"riskReason\"\x8d\x01\n" +
	"\n" +
	"SudoConfig\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x14\n" +
	"\x05runas\x18\x03 \x01(\tR\x05runas\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\x12'\n" +
	"\x0fis_passwordless\x18\x05 \x01(\bR\x0eisPasswordless\"\xfc\x03\n" +
	"\x17PrivilegeEscalationInfo\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12!\n" +
	"\fcurrent_user\x18\x02 \x01(\tR\vcurrentUser\x12\x1f\n" +
	"\vcurrent_uid\x18\x03 \x01(\x05R\n" +
	"currentUid\x12\x1f\n" +
	"\vcurrent_gid\x18\x04 \x01(\x05R\n" +
	"currentGid\x12\x16\n" +
	"\x06groups\x18\x05 \x03(\tR\x06groups\x120\n" +
	"\rsuid_binaries\x18\n" +
	" \x03(\v2\v.SuidBinaryR\fsuidBinaries\x12,\n" +
	"\vsudo_config\x18\v \x03(\v2\v.SudoConfigR\n" +
	"sudoConfig\x128\n" +
	"\fcapabilities\x18\f \x03(\v2\x14.ContainerCapabilityR\fcapabilities\x128\n" +
	"\x18writable_sensitive_files\x18\r \x03(\tR\x16writableSensitiveFiles\x12,\n" +
	"\x12sensitive_env_vars\x18\x0e \x03(\tR\x10sensitiveEnvVars\x12\"\n" +
	"\rhas_high_risk\x18\x0f \x01(\bR\vhasHighRisk\x12!\n" +
	"\frisk_summary\x18\x10 \x01(\tR\vriskSummary\"\x1c\n" +
	"\x1aPrivilegeEscalationRequest\"K\n" +
	"\x1bPrivilegeEscalationResponse\x12,\n" +
	"\x04info\x18\x01 \x01(\v2\x18.PrivilegeEscalationInfoR\x04info\"\xcf\x01\n" +
	"\x16ClusterRoleBindingInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\trole_kind\x18\x02 \x01(\tR\broleKind\x12\x1b\n" +
	"\trole_name\x18\x03 \x01(\tR\broleName\x12\x1a\n" +
	"\bsubjects\x18\x04 \x03(\tR\bsubjects\x12*\n" +
	"\x11can_privilege_esc\x18\x05 \x01(\bR\x0fcanPrivilegeEsc\x12\x1f\n" +
	"\vrisk_reason\x18\x06 \x01(\tR\n" +
	"riskReason\"\x80\x01\n" +
	"\x10AccessibleSecret\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1f\n" +
	"\vsecret_type\x18\x03 \x01(\tR\n" +
	"secretType\x12\x19\n" +
	"\bcan_read\x18\x04 \x01(\bR\acanRead\"\xad\x05\n" +
	"\x1aK8SPrivilegeEscalationInfo\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12!\n" +
	"\fcluster_name\x18\x02 \x01(\tR\vclusterName\x12\x19\n" +
	"\bpod_name\x18\x03 \x01(\tR\apodName\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12'\n" +
	"\x0fservice_account\x18\x05 \x01(\tR\x0eserviceAccount\x12K\n" +
	"\x15cluster_role_bindings\x18\n" +
	" \x03(\v2\x17.ClusterRoleBindingInfoR\x13clusterRoleBindings\x12<\n" +
	"\rrole_bindings\x18\v \x03(\v2\x17.ClusterRoleBindingInfoR\froleBindings\x12@\n" +
	"\x12accessible_secrets\x18\f \x03(\v2\x11.AccessibleSecretR\x11accessibleSecrets\x12)\n" +
	"\x10token_expiration\x18\r \x01(\x03R\x0ftokenExpiration\x12\x1d\n" +
	"\n" +
	"token_file\x18\x0e \x01(\tR\ttokenFile\x12\x19\n" +
	"\bcan_exec\x18\x0f \x01(\bR\acanExec\x12(\n" +
	"\x10can_port_forward\x18\x10 \x01(\bR\x0ecanPortForward\x12$\n" +
	"\x0ecan_create_pod\x18\x11 \x01(\bR\fcanCreatePod\x12$\n" +
	"\x0ecan_delete_pod\x18\x12 \x01(\bR\fcanDeletePod\x12\"\n" +
	"\rhas_high_risk\x18\x13 \x01(\bR\vhasHighRisk\x12!\n" +
	"\frisk_summary\x18\x14 \x01(\tR\vriskSummary\"\x1f\n" +
	"\x1dK8SPrivilegeEscalationRequest\"Q\n" +
	"\x1eK8SPrivilegeEscalationResponse\x12/\n" +
	"\x04info\x18\x01 \x01(\v2\x1b.K8SPrivilegeEscalationInfoR\x04infoB)\n" +
	"\n" +
	"gaiasec.pbP\x01Z\x19gaiasec-nodeagent/pkg/pb/b\x06proto3"

var (
	file_escape_proto_rawDescOnce sync.Once
	file_escape_proto_rawDescData []byte
)

func file_escape_proto_rawDescGZIP() []byte {
	file_escape_proto_rawDescOnce.Do(func() {
		file_escape_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_escape_proto_rawDesc), len(file_escape_proto_rawDesc)))
	})
	return file_escape_proto_rawDescData
}

var file_escape_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_escape_proto_goTypes = []any{
	(*ContainerMount)(nil),                 // 0: ContainerMount
	(*ContainerCapability)(nil),            // 1: ContainerCapability
	(*ContainerEscapeInfo)(nil),            // 2: ContainerEscapeInfo
	(*ContainerEscapeRequest)(nil),         // 3: ContainerEscapeRequest
	(*ContainerEscapeResponse)(nil),        // 4: ContainerEscapeResponse
	(*SuidBinary)(nil),                     // 5: SuidBinary
	(*SudoConfig)(nil),                     // 6: SudoConfig
	(*PrivilegeEscalationInfo)(nil),        // 7: PrivilegeEscalationInfo
	(*PrivilegeEscalationRequest)(nil),     // 8: PrivilegeEscalationRequest
	(*PrivilegeEscalationResponse)(nil),    // 9: PrivilegeEscalationResponse
	(*ClusterRoleBindingInfo)(nil),         // 10: ClusterRoleBindingInfo
	(*AccessibleSecret)(nil),               // 11: AccessibleSecret
	(*K8SPrivilegeEscalationInfo)(nil),     // 12: K8SPrivilegeEscalationInfo
	(*K8SPrivilegeEscalationRequest)(nil),  // 13: K8SPrivilegeEscalationRequest
	(*K8SPrivilegeEscalationResponse)(nil), // 14: K8SPrivilegeEscalationResponse
}
var file_escape_proto_depIdxs = []int32{
	0,  // 0: ContainerEscapeInfo.mounts:type_name -> ContainerMount
	1,  // 1: ContainerEscapeInfo.capabilities:type_name -> ContainerCapability
	2,  // 2: ContainerEscapeResponse.containers:type_name -> ContainerEscapeInfo
	5,  // 3: PrivilegeEscalationInfo.suid_binaries:type_name -> SuidBinary
	6,  // 4: PrivilegeEscalationInfo.sudo_config:type_name -> SudoConfig
	1,  // 5: PrivilegeEscalationInfo.capabilities:type_name -> ContainerCapability
	7,  // 6: PrivilegeEscalationResponse.info:type_name -> PrivilegeEscalationInfo
	10, // 7: K8SPrivilegeEscalationInfo.cluster_role_bindings:type_name -> ClusterRoleBindingInfo
	10, // 8: K8SPrivilegeEscalationInfo.role_bindings:type_name -> ClusterRoleBindingInfo
	11, // 9: K8SPrivilegeEscalationInfo.accessible_secrets:type_name -> AccessibleSecret
	12, // 10: K8SPrivilegeEscalationResponse.info:type_name -> K8SPrivilegeEscalationInfo
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_escape_proto_init() }
func file_escape_proto_init() {
	if File_escape_proto != nil {
		return
	}
	file_message_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_escape_proto_rawDesc), len(file_escape_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_escape_proto_goTypes,
		DependencyIndexes: file_escape_proto_depIdxs,
		MessageInfos:      file_escape_proto_msgTypes,
	}.Build()
	File_escape_proto = out.File
	file_escape_proto_goTypes = nil
	file_escape_proto_depIdxs = nil
}
