// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: file.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileType int32

const (
	FileType_FILE      FileType = 0
	FileType_DIRECTORY FileType = 1
	FileType_SYMLINK   FileType = 2
)

// Enum value maps for FileType.
var (
	FileType_name = map[int32]string{
		0: "FILE",
		1: "DIRECTORY",
		2: "SYMLINK",
	}
	FileType_value = map[string]int32{
		"FILE":      0,
		"DIRECTORY": 1,
		"SYMLINK":   2,
	}
)

func (x FileType) Enum() *FileType {
	p := new(FileType)
	*p = x
	return p
}

func (x FileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileType) Descriptor() protoreflect.EnumDescriptor {
	return file_file_proto_enumTypes[0].Descriptor()
}

func (FileType) Type() protoreflect.EnumType {
	return &file_file_proto_enumTypes[0]
}

func (x FileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileType.Descriptor instead.
func (FileType) EnumDescriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{0}
}

type FileNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	FileType      FileType               `protobuf:"varint,3,opt,name=file_type,json=fileType,proto3,enum=FileType" json:"file_type,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	ModifiedTime  int64                  `protobuf:"varint,5,opt,name=modified_time,json=modifiedTime,proto3" json:"modified_time,omitempty"`
	Permission    string                 `protobuf:"bytes,6,opt,name=permission,proto3" json:"permission,omitempty"`
	Link          string                 `protobuf:"bytes,7,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileNode) Reset() {
	*x = FileNode{}
	mi := &file_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileNode) ProtoMessage() {}

func (x *FileNode) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileNode.ProtoReflect.Descriptor instead.
func (*FileNode) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{0}
}

func (x *FileNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileNode) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileNode) GetFileType() FileType {
	if x != nil {
		return x.FileType
	}
	return FileType_FILE
}

func (x *FileNode) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileNode) GetModifiedTime() int64 {
	if x != nil {
		return x.ModifiedTime
	}
	return 0
}

func (x *FileNode) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

func (x *FileNode) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type FSListDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FSListDirRequest) Reset() {
	*x = FSListDirRequest{}
	mi := &file_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FSListDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FSListDirRequest) ProtoMessage() {}

func (x *FSListDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FSListDirRequest.ProtoReflect.Descriptor instead.
func (*FSListDirRequest) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{1}
}

func (x *FSListDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FSListDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Files         []*FileNode            `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	Result        string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FSListDirResponse) Reset() {
	*x = FSListDirResponse{}
	mi := &file_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FSListDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FSListDirResponse) ProtoMessage() {}

func (x *FSListDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FSListDirResponse.ProtoReflect.Descriptor instead.
func (*FSListDirResponse) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{2}
}

func (x *FSListDirResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FSListDirResponse) GetFiles() []*FileNode {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *FSListDirResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type FSReadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FSReadFileRequest) Reset() {
	*x = FSReadFileRequest{}
	mi := &file_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FSReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FSReadFileRequest) ProtoMessage() {}

func (x *FSReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FSReadFileRequest.ProtoReflect.Descriptor instead.
func (*FSReadFileRequest) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{3}
}

func (x *FSReadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FSReadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	IsBinary      bool                   `protobuf:"varint,4,opt,name=is_binary,json=isBinary,proto3" json:"is_binary,omitempty"`
	Result        string                 `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FSReadFileResponse) Reset() {
	*x = FSReadFileResponse{}
	mi := &file_file_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FSReadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FSReadFileResponse) ProtoMessage() {}

func (x *FSReadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FSReadFileResponse.ProtoReflect.Descriptor instead.
func (*FSReadFileResponse) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{4}
}

func (x *FSReadFileResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FSReadFileResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *FSReadFileResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FSReadFileResponse) GetIsBinary() bool {
	if x != nil {
		return x.IsBinary
	}
	return false
}

func (x *FSReadFileResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type FSWriteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FSWriteFileRequest) Reset() {
	*x = FSWriteFileRequest{}
	mi := &file_file_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FSWriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FSWriteFileRequest) ProtoMessage() {}

func (x *FSWriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FSWriteFileRequest.ProtoReflect.Descriptor instead.
func (*FSWriteFileRequest) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{5}
}

func (x *FSWriteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FSWriteFileRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type FSWriteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FSWriteFileResponse) Reset() {
	*x = FSWriteFileResponse{}
	mi := &file_file_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FSWriteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FSWriteFileResponse) ProtoMessage() {}

func (x *FSWriteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FSWriteFileResponse.ProtoReflect.Descriptor instead.
func (*FSWriteFileResponse) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{6}
}

func (x *FSWriteFileResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type FSCreateFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FSCreateFileRequest) Reset() {
	*x = FSCreateFileRequest{}
	mi := &file_file_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FSCreateFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FSCreateFileRequest) ProtoMessage() {}

func (x *FSCreateFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FSCreateFileRequest.ProtoReflect.Descriptor instead.
func (*FSCreateFileRequest) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{7}
}

func (x *FSCreateFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FSCreateFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FSCreateFileResponse) Reset() {
	*x = FSCreateFileResponse{}
	mi := &file_file_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FSCreateFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FSCreateFileResponse) ProtoMessage() {}

func (x *FSCreateFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FSCreateFileResponse.ProtoReflect.Descriptor instead.
func (*FSCreateFileResponse) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{8}
}

func (x *FSCreateFileResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type FSCreateDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FSCreateDirRequest) Reset() {
	*x = FSCreateDirRequest{}
	mi := &file_file_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FSCreateDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FSCreateDirRequest) ProtoMessage() {}

func (x *FSCreateDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FSCreateDirRequest.ProtoReflect.Descriptor instead.
func (*FSCreateDirRequest) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{9}
}

func (x *FSCreateDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FSCreateDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FSCreateDirResponse) Reset() {
	*x = FSCreateDirResponse{}
	mi := &file_file_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FSCreateDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FSCreateDirResponse) ProtoMessage() {}

func (x *FSCreateDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FSCreateDirResponse.ProtoReflect.Descriptor instead.
func (*FSCreateDirResponse) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{10}
}

func (x *FSCreateDirResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type FSDeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FSDeleteFileRequest) Reset() {
	*x = FSDeleteFileRequest{}
	mi := &file_file_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FSDeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FSDeleteFileRequest) ProtoMessage() {}

func (x *FSDeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FSDeleteFileRequest.ProtoReflect.Descriptor instead.
func (*FSDeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{11}
}

func (x *FSDeleteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FSDeleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FSDeleteFileResponse) Reset() {
	*x = FSDeleteFileResponse{}
	mi := &file_file_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FSDeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FSDeleteFileResponse) ProtoMessage() {}

func (x *FSDeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FSDeleteFileResponse.ProtoReflect.Descriptor instead.
func (*FSDeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{12}
}

func (x *FSDeleteFileResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type FSRenameFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldPath       string                 `protobuf:"bytes,1,opt,name=old_path,json=oldPath,proto3" json:"old_path,omitempty"`
	NewPath       string                 `protobuf:"bytes,2,opt,name=new_path,json=newPath,proto3" json:"new_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FSRenameFileRequest) Reset() {
	*x = FSRenameFileRequest{}
	mi := &file_file_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FSRenameFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FSRenameFileRequest) ProtoMessage() {}

func (x *FSRenameFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FSRenameFileRequest.ProtoReflect.Descriptor instead.
func (*FSRenameFileRequest) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{13}
}

func (x *FSRenameFileRequest) GetOldPath() string {
	if x != nil {
		return x.OldPath
	}
	return ""
}

func (x *FSRenameFileRequest) GetNewPath() string {
	if x != nil {
		return x.NewPath
	}
	return ""
}

type FSRenameFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FSRenameFileResponse) Reset() {
	*x = FSRenameFileResponse{}
	mi := &file_file_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FSRenameFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FSRenameFileResponse) ProtoMessage() {}

func (x *FSRenameFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FSRenameFileResponse.ProtoReflect.Descriptor instead.
func (*FSRenameFileResponse) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{14}
}

func (x *FSRenameFileResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type FSDownloadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FSDownloadFileRequest) Reset() {
	*x = FSDownloadFileRequest{}
	mi := &file_file_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FSDownloadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FSDownloadFileRequest) ProtoMessage() {}

func (x *FSDownloadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FSDownloadFileRequest.ProtoReflect.Descriptor instead.
func (*FSDownloadFileRequest) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{15}
}

func (x *FSDownloadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FSArchiveCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootPath      string                 `protobuf:"bytes,1,opt,name=root_path,json=rootPath,proto3" json:"root_path,omitempty"`
	Include       []string               `protobuf:"bytes,2,rep,name=include,proto3" json:"include,omitempty"`
	Exclude       []string               `protobuf:"bytes,3,rep,name=exclude,proto3" json:"exclude,omitempty"`
	ArchiveName   string                 `protobuf:"bytes,4,opt,name=archive_name,json=archiveName,proto3" json:"archive_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FSArchiveCreateRequest) Reset() {
	*x = FSArchiveCreateRequest{}
	mi := &file_file_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FSArchiveCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FSArchiveCreateRequest) ProtoMessage() {}

func (x *FSArchiveCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FSArchiveCreateRequest.ProtoReflect.Descriptor instead.
func (*FSArchiveCreateRequest) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{16}
}

func (x *FSArchiveCreateRequest) GetRootPath() string {
	if x != nil {
		return x.RootPath
	}
	return ""
}

func (x *FSArchiveCreateRequest) GetInclude() []string {
	if x != nil {
		return x.Include
	}
	return nil
}

func (x *FSArchiveCreateRequest) GetExclude() []string {
	if x != nil {
		return x.Exclude
	}
	return nil
}

func (x *FSArchiveCreateRequest) GetArchiveName() string {
	if x != nil {
		return x.ArchiveName
	}
	return ""
}

type FSArchiveCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	ArchivePath   string                 `protobuf:"bytes,2,opt,name=archive_path,json=archivePath,proto3" json:"archive_path,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FSArchiveCreateResponse) Reset() {
	*x = FSArchiveCreateResponse{}
	mi := &file_file_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FSArchiveCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FSArchiveCreateResponse) ProtoMessage() {}

func (x *FSArchiveCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FSArchiveCreateResponse.ProtoReflect.Descriptor instead.
func (*FSArchiveCreateResponse) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{17}
}

func (x *FSArchiveCreateResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *FSArchiveCreateResponse) GetArchivePath() string {
	if x != nil {
		return x.ArchivePath
	}
	return ""
}

func (x *FSArchiveCreateResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FSArchiveCreateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FSArchiveUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootPath      string                 `protobuf:"bytes,1,opt,name=root_path,json=rootPath,proto3" json:"root_path,omitempty"`
	Include       []string               `protobuf:"bytes,2,rep,name=include,proto3" json:"include,omitempty"`
	Exclude       []string               `protobuf:"bytes,3,rep,name=exclude,proto3" json:"exclude,omitempty"`
	ArchiveName   string                 `protobuf:"bytes,4,opt,name=archive_name,json=archiveName,proto3" json:"archive_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FSArchiveUploadRequest) Reset() {
	*x = FSArchiveUploadRequest{}
	mi := &file_file_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FSArchiveUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FSArchiveUploadRequest) ProtoMessage() {}

func (x *FSArchiveUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FSArchiveUploadRequest.ProtoReflect.Descriptor instead.
func (*FSArchiveUploadRequest) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{18}
}

func (x *FSArchiveUploadRequest) GetRootPath() string {
	if x != nil {
		return x.RootPath
	}
	return ""
}

func (x *FSArchiveUploadRequest) GetInclude() []string {
	if x != nil {
		return x.Include
	}
	return nil
}

func (x *FSArchiveUploadRequest) GetExclude() []string {
	if x != nil {
		return x.Exclude
	}
	return nil
}

func (x *FSArchiveUploadRequest) GetArchiveName() string {
	if x != nil {
		return x.ArchiveName
	}
	return ""
}

type FSArchiveUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	ArchiveName   string                 `protobuf:"bytes,2,opt,name=archive_name,json=archiveName,proto3" json:"archive_name,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FSArchiveUploadResponse) Reset() {
	*x = FSArchiveUploadResponse{}
	mi := &file_file_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FSArchiveUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FSArchiveUploadResponse) ProtoMessage() {}

func (x *FSArchiveUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FSArchiveUploadResponse.ProtoReflect.Descriptor instead.
func (*FSArchiveUploadResponse) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{19}
}

func (x *FSArchiveUploadResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *FSArchiveUploadResponse) GetArchiveName() string {
	if x != nil {
		return x.ArchiveName
	}
	return ""
}

func (x *FSArchiveUploadResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_file_proto protoreflect.FileDescriptor

const file_file_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"file.proto\"\xc7\x01\n" +
	"\bFileNode\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12&\n" +
	"\tfile_type\x18\x03 \x01(\x0e2\t.FileTypeR\bfileType\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12#\n" +
	"\rmodified_time\x18\x05 \x01(\x03R\fmodifiedTime\x12\x1e\n" +
	"\n" +
	"permission\x18\x06 \x01(\tR\n" +
	"permission\x12\x12\n" +
	"\x04link\x18\a \x01(\tR\x04link\"&\n" +
	"\x10FSListDirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"`\n" +
	"\x11FSListDirResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1f\n" +
	"\x05files\x18\x02 \x03(\v2\t.FileNodeR\x05files\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\"'\n" +
	"\x11FSReadFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x8b\x01\n" +
	"\x12FSReadFileResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x1b\n" +
	"\tis_binary\x18\x04 \x01(\bR\bisBinary\x12\x16\n" +
	"\x06result\x18\x05 \x01(\tR\x06result\"B\n" +
	"\x12FSWriteFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"-\n" +
	"\x13FSWriteFileResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\")\n" +
	"\x13FSCreateFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\".\n" +
	"\x14FSCreateFileResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"(\n" +
	"\x12FSCreateDirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"-\n" +
	"\x13FSCreateDirResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\")\n" +
	"\x13FSDeleteFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\".\n" +
	"\x14FSDeleteFileResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"K\n" +
	"\x13FSRenameFileRequest\x12\x19\n" +
	"\bold_path\x18\x01 \x01(\tR\aoldPath\x12\x19\n" +
	"\bnew_path\x18\x02 \x01(\tR\anewPath\".\n" +
	"\x14FSRenameFileResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"+\n" +
	"\x15FSDownloadFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x8c\x01\n" +
	"\x16FSArchiveCreateRequest\x12\x1b\n" +
	"\troot_path\x18\x01 \x01(\tR\brootPath\x12\x18\n" +
	"\ainclude\x18\x02 \x03(\tR\ainclude\x12\x18\n" +
	"\aexclude\x18\x03 \x03(\tR\aexclude\x12!\n" +
	"\farchive_name\x18\x04 \x01(\tR\varchiveName\"~\n" +
	"\x17FSArchiveCreateResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12!\n" +
	"\farchive_path\x18\x02 \x01(\tR\varchivePath\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x8c\x01\n" +
	"\x16FSArchiveUploadRequest\x12\x1b\n" +
	"\troot_path\x18\x01 \x01(\tR\brootPath\x12\x18\n" +
	"\ainclude\x18\x02 \x03(\tR\ainclude\x12\x18\n" +
	"\aexclude\x18\x03 \x03(\tR\aexclude\x12!\n" +
	"\farchive_name\x18\x04 \x01(\tR\varchiveName\"j\n" +
	"\x17FSArchiveUploadResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12!\n" +
	"\farchive_name\x18\x02 \x01(\tR\varchiveName\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error*0\n" +
	"\bFileType\x12\b\n" +
	"\x04FILE\x10\x00\x12\r\n" +
	"\tDIRECTORY\x10\x01\x12\v\n" +
	"\aSYMLINK\x10\x02B)\n" +
	"\n" +
	"gaiasec.pbP\x01Z\x19gaiasec-nodeagent/pkg/pb/b\x06proto3"

var (
	file_file_proto_rawDescOnce sync.Once
	file_file_proto_rawDescData []byte
)

func file_file_proto_rawDescGZIP() []byte {
	file_file_proto_rawDescOnce.Do(func() {
		file_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_proto_rawDesc), len(file_file_proto_rawDesc)))
	})
	return file_file_proto_rawDescData
}

var file_file_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_file_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_file_proto_goTypes = []any{
	(FileType)(0),                   // 0: FileType
	(*FileNode)(nil),                // 1: FileNode
	(*FSListDirRequest)(nil),        // 2: FSListDirRequest
	(*FSListDirResponse)(nil),       // 3: FSListDirResponse
	(*FSReadFileRequest)(nil),       // 4: FSReadFileRequest
	(*FSReadFileResponse)(nil),      // 5: FSReadFileResponse
	(*FSWriteFileRequest)(nil),      // 6: FSWriteFileRequest
	(*FSWriteFileResponse)(nil),     // 7: FSWriteFileResponse
	(*FSCreateFileRequest)(nil),     // 8: FSCreateFileRequest
	(*FSCreateFileResponse)(nil),    // 9: FSCreateFileResponse
	(*FSCreateDirRequest)(nil),      // 10: FSCreateDirRequest
	(*FSCreateDirResponse)(nil),     // 11: FSCreateDirResponse
	(*FSDeleteFileRequest)(nil),     // 12: FSDeleteFileRequest
	(*FSDeleteFileResponse)(nil),    // 13: FSDeleteFileResponse
	(*FSRenameFileRequest)(nil),     // 14: FSRenameFileRequest
	(*FSRenameFileResponse)(nil),    // 15: FSRenameFileResponse
	(*FSDownloadFileRequest)(nil),   // 16: FSDownloadFileRequest
	(*FSArchiveCreateRequest)(nil),  // 17: FSArchiveCreateRequest
	(*FSArchiveCreateResponse)(nil), // 18: FSArchiveCreateResponse
	(*FSArchiveUploadRequest)(nil),  // 19: FSArchiveUploadRequest
	(*FSArchiveUploadResponse)(nil), // 20: FSArchiveUploadResponse
}
var file_file_proto_depIdxs = []int32{
	0, // 0: FileNode.file_type:type_name -> FileType
	1, // 1: FSListDirResponse.files:type_name -> FileNode
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_file_proto_init() }
func file_file_proto_init() {
	if File_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_proto_rawDesc), len(file_file_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_file_proto_goTypes,
		DependencyIndexes: file_file_proto_depIdxs,
		EnumInfos:         file_file_proto_enumTypes,
		MessageInfos:      file_file_proto_msgTypes,
	}.Build()
	File_file_proto = out.File
	file_file_proto_goTypes = nil
	file_file_proto_depIdxs = nil
}
