// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: fuzz.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FuzzRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Args          []string               `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FuzzRequest) Reset() {
	*x = FuzzRequest{}
	mi := &file_fuzz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FuzzRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuzzRequest) ProtoMessage() {}

func (x *FuzzRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fuzz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuzzRequest.ProtoReflect.Descriptor instead.
func (*FuzzRequest) Descriptor() ([]byte, []int) {
	return file_fuzz_proto_rawDescGZIP(), []int{0}
}

func (x *FuzzRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type FuzzResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FuzzResponse) Reset() {
	*x = FuzzResponse{}
	mi := &file_fuzz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FuzzResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuzzResponse) ProtoMessage() {}

func (x *FuzzResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fuzz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuzzResponse.ProtoReflect.Descriptor instead.
func (*FuzzResponse) Descriptor() ([]byte, []int) {
	return file_fuzz_proto_rawDescGZIP(), []int{1}
}

func (x *FuzzResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_fuzz_proto protoreflect.FileDescriptor

const file_fuzz_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"fuzz.proto\"!\n" +
	"\vFuzzRequest\x12\x12\n" +
	"\x04args\x18\x01 \x03(\tR\x04args\"&\n" +
	"\fFuzzResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06resultB)\n" +
	"\n" +
	"sothoth.pbP\x01Z\x19sothoth-nodeagent/pkg/pb/b\x06proto3"

var (
	file_fuzz_proto_rawDescOnce sync.Once
	file_fuzz_proto_rawDescData []byte
)

func file_fuzz_proto_rawDescGZIP() []byte {
	file_fuzz_proto_rawDescOnce.Do(func() {
		file_fuzz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fuzz_proto_rawDesc), len(file_fuzz_proto_rawDesc)))
	})
	return file_fuzz_proto_rawDescData
}

var file_fuzz_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fuzz_proto_goTypes = []any{
	(*FuzzRequest)(nil),  // 0: FuzzRequest
	(*FuzzResponse)(nil), // 1: FuzzResponse
}
var file_fuzz_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fuzz_proto_init() }
func file_fuzz_proto_init() {
	if File_fuzz_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fuzz_proto_rawDesc), len(file_fuzz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fuzz_proto_goTypes,
		DependencyIndexes: file_fuzz_proto_depIdxs,
		MessageInfos:      file_fuzz_proto_msgTypes,
	}.Build()
	File_fuzz_proto = out.File
	file_fuzz_proto_goTypes = nil
	file_fuzz_proto_depIdxs = nil
}
