// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: http.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HttpSendRequestProto struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Host           string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port           int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Secure         bool                   `protobuf:"varint,3,opt,name=secure,proto3" json:"secure,omitempty"`
	Data           string                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	ReadTimeout    int32                  `protobuf:"varint,5,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`
	ConnectTimeout int32                  `protobuf:"varint,6,opt,name=connect_timeout,json=connectTimeout,proto3" json:"connect_timeout,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HttpSendRequestProto) Reset() {
	*x = HttpSendRequestProto{}
	mi := &file_http_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpSendRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpSendRequestProto) ProtoMessage() {}

func (x *HttpSendRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_http_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpSendRequestProto.ProtoReflect.Descriptor instead.
func (*HttpSendRequestProto) Descriptor() ([]byte, []int) {
	return file_http_proto_rawDescGZIP(), []int{0}
}

func (x *HttpSendRequestProto) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *HttpSendRequestProto) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *HttpSendRequestProto) GetSecure() bool {
	if x != nil {
		return x.Secure
	}
	return false
}

func (x *HttpSendRequestProto) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *HttpSendRequestProto) GetReadTimeout() int32 {
	if x != nil {
		return x.ReadTimeout
	}
	return 0
}

func (x *HttpSendRequestProto) GetConnectTimeout() int32 {
	if x != nil {
		return x.ConnectTimeout
	}
	return 0
}

type HttpSendResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Response      string                 `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`
	ResponseTime  int64                  `protobuf:"varint,4,opt,name=response_time,json=responseTime,proto3" json:"response_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpSendResponseProto) Reset() {
	*x = HttpSendResponseProto{}
	mi := &file_http_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpSendResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpSendResponseProto) ProtoMessage() {}

func (x *HttpSendResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_http_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpSendResponseProto.ProtoReflect.Descriptor instead.
func (*HttpSendResponseProto) Descriptor() ([]byte, []int) {
	return file_http_proto_rawDescGZIP(), []int{1}
}

func (x *HttpSendResponseProto) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HttpSendResponseProto) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HttpSendResponseProto) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *HttpSendResponseProto) GetResponseTime() int64 {
	if x != nil {
		return x.ResponseTime
	}
	return 0
}

var File_http_proto protoreflect.FileDescriptor

const file_http_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"http.proto\"\xb6\x01\n" +
	"\x14HttpSendRequestProto\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x16\n" +
	"\x06secure\x18\x03 \x01(\bR\x06secure\x12\x12\n" +
	"\x04data\x18\x04 \x01(\tR\x04data\x12!\n" +
	"\fread_timeout\x18\x05 \x01(\x05R\vreadTimeout\x12'\n" +
	"\x0fconnect_timeout\x18\x06 \x01(\x05R\x0econnectTimeout\"\x8c\x01\n" +
	"\x15HttpSendResponseProto\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\bresponse\x18\x03 \x01(\tR\bresponse\x12#\n" +
	"\rresponse_time\x18\x04 \x01(\x03R\fresponseTimeB)\n" +
	"\n" +
	"gaiasec.pbP\x01Z\x19gaiasec-nodeagent/pkg/pb/b\x06proto3"

var (
	file_http_proto_rawDescOnce sync.Once
	file_http_proto_rawDescData []byte
)

func file_http_proto_rawDescGZIP() []byte {
	file_http_proto_rawDescOnce.Do(func() {
		file_http_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_http_proto_rawDesc), len(file_http_proto_rawDesc)))
	})
	return file_http_proto_rawDescData
}

var file_http_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_http_proto_goTypes = []any{
	(*HttpSendRequestProto)(nil),  // 0: HttpSendRequestProto
	(*HttpSendResponseProto)(nil), // 1: HttpSendResponseProto
}
var file_http_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_http_proto_init() }
func file_http_proto_init() {
	if File_http_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_http_proto_rawDesc), len(file_http_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_http_proto_goTypes,
		DependencyIndexes: file_http_proto_depIdxs,
		MessageInfos:      file_http_proto_msgTypes,
	}.Build()
	File_http_proto = out.File
	file_http_proto_goTypes = nil
	file_http_proto_depIdxs = nil
}
