// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: iast.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IastNormalReport struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	VulnType       string                 `protobuf:"bytes,2,opt,name=vuln_type,json=vulnType,proto3" json:"vuln_type,omitempty"`
	Protocol       string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Scheme         string                 `protobuf:"bytes,4,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Method         string                 `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	Secure         bool                   `protobuf:"varint,6,opt,name=secure,proto3" json:"secure,omitempty"`
	Url            string                 `protobuf:"bytes,7,opt,name=url,proto3" json:"url,omitempty"`
	Uri            string                 `protobuf:"bytes,8,opt,name=uri,proto3" json:"uri,omitempty"`
	ClientIp       string                 `protobuf:"bytes,9,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	QueryString    string                 `protobuf:"bytes,10,opt,name=query_string,json=queryString,proto3" json:"query_string,omitempty"`
	RequestHeader  string                 `protobuf:"bytes,11,opt,name=request_header,json=requestHeader,proto3" json:"request_header,omitempty"`
	RequestBody    string                 `protobuf:"bytes,12,opt,name=request_body,json=requestBody,proto3" json:"request_body,omitempty"`
	ResponseHeader string                 `protobuf:"bytes,13,opt,name=response_header,json=responseHeader,proto3" json:"response_header,omitempty"`
	ResponseBody   string                 `protobuf:"bytes,14,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"`
	ContextPath    string                 `protobuf:"bytes,15,opt,name=context_path,json=contextPath,proto3" json:"context_path,omitempty"`
	AppCaller      []string               `protobuf:"bytes,16,rep,name=app_caller,json=appCaller,proto3" json:"app_caller,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IastNormalReport) Reset() {
	*x = IastNormalReport{}
	mi := &file_iast_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IastNormalReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IastNormalReport) ProtoMessage() {}

func (x *IastNormalReport) ProtoReflect() protoreflect.Message {
	mi := &file_iast_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IastNormalReport.ProtoReflect.Descriptor instead.
func (*IastNormalReport) Descriptor() ([]byte, []int) {
	return file_iast_proto_rawDescGZIP(), []int{0}
}

func (x *IastNormalReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *IastNormalReport) GetVulnType() string {
	if x != nil {
		return x.VulnType
	}
	return ""
}

func (x *IastNormalReport) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *IastNormalReport) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *IastNormalReport) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *IastNormalReport) GetSecure() bool {
	if x != nil {
		return x.Secure
	}
	return false
}

func (x *IastNormalReport) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *IastNormalReport) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *IastNormalReport) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *IastNormalReport) GetQueryString() string {
	if x != nil {
		return x.QueryString
	}
	return ""
}

func (x *IastNormalReport) GetRequestHeader() string {
	if x != nil {
		return x.RequestHeader
	}
	return ""
}

func (x *IastNormalReport) GetRequestBody() string {
	if x != nil {
		return x.RequestBody
	}
	return ""
}

func (x *IastNormalReport) GetResponseHeader() string {
	if x != nil {
		return x.ResponseHeader
	}
	return ""
}

func (x *IastNormalReport) GetResponseBody() string {
	if x != nil {
		return x.ResponseBody
	}
	return ""
}

func (x *IastNormalReport) GetContextPath() string {
	if x != nil {
		return x.ContextPath
	}
	return ""
}

func (x *IastNormalReport) GetAppCaller() []string {
	if x != nil {
		return x.AppCaller
	}
	return nil
}

type IastTaintPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        []string               `protobuf:"bytes,1,rep,name=source,proto3" json:"source,omitempty"`
	Target        []string               `protobuf:"bytes,2,rep,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IastTaintPosition) Reset() {
	*x = IastTaintPosition{}
	mi := &file_iast_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IastTaintPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IastTaintPosition) ProtoMessage() {}

func (x *IastTaintPosition) ProtoReflect() protoreflect.Message {
	mi := &file_iast_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IastTaintPosition.ProtoReflect.Descriptor instead.
func (*IastTaintPosition) Descriptor() ([]byte, []int) {
	return file_iast_proto_rawDescGZIP(), []int{1}
}

func (x *IastTaintPosition) GetSource() []string {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *IastTaintPosition) GetTarget() []string {
	if x != nil {
		return x.Target
	}
	return nil
}

type IastParameter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         string                 `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IastParameter) Reset() {
	*x = IastParameter{}
	mi := &file_iast_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IastParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IastParameter) ProtoMessage() {}

func (x *IastParameter) ProtoReflect() protoreflect.Message {
	mi := &file_iast_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IastParameter.ProtoReflect.Descriptor instead.
func (*IastParameter) Descriptor() ([]byte, []int) {
	return file_iast_proto_rawDescGZIP(), []int{2}
}

func (x *IastParameter) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *IastParameter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type IastRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Start         int32                  `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	Stop          int32                  `protobuf:"varint,3,opt,name=stop,proto3" json:"stop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IastRange) Reset() {
	*x = IastRange{}
	mi := &file_iast_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IastRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IastRange) ProtoMessage() {}

func (x *IastRange) ProtoReflect() protoreflect.Message {
	mi := &file_iast_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IastRange.ProtoReflect.Descriptor instead.
func (*IastRange) Descriptor() ([]byte, []int) {
	return file_iast_proto_rawDescGZIP(), []int{3}
}

func (x *IastRange) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IastRange) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *IastRange) GetStop() int32 {
	if x != nil {
		return x.Stop
	}
	return 0
}

type IastTargetRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          int64                  `protobuf:"varint,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Ranges        []*IastRange           `protobuf:"bytes,2,rep,name=ranges,proto3" json:"ranges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IastTargetRange) Reset() {
	*x = IastTargetRange{}
	mi := &file_iast_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IastTargetRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IastTargetRange) ProtoMessage() {}

func (x *IastTargetRange) ProtoReflect() protoreflect.Message {
	mi := &file_iast_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IastTargetRange.ProtoReflect.Descriptor instead.
func (*IastTargetRange) Descriptor() ([]byte, []int) {
	return file_iast_proto_rawDescGZIP(), []int{4}
}

func (x *IastTargetRange) GetHash() int64 {
	if x != nil {
		return x.Hash
	}
	return 0
}

func (x *IastTargetRange) GetRanges() []*IastRange {
	if x != nil {
		return x.Ranges
	}
	return nil
}

type IastSourceType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          int64                  `protobuf:"varint,1,opt,name=hash,proto3" json:"hash,omitempty"`
	SourceType    string                 `protobuf:"bytes,2,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IastSourceType) Reset() {
	*x = IastSourceType{}
	mi := &file_iast_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IastSourceType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IastSourceType) ProtoMessage() {}

func (x *IastSourceType) ProtoReflect() protoreflect.Message {
	mi := &file_iast_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IastSourceType.ProtoReflect.Descriptor instead.
func (*IastSourceType) Descriptor() ([]byte, []int) {
	return file_iast_proto_rawDescGZIP(), []int{5}
}

func (x *IastSourceType) GetHash() int64 {
	if x != nil {
		return x.Hash
	}
	return 0
}

func (x *IastSourceType) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

type IastMethodEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	InvokeId         int32                  `protobuf:"varint,1,opt,name=invoke_id,json=invokeId,proto3" json:"invoke_id,omitempty"`
	PolicyType       string                 `protobuf:"bytes,2,opt,name=policy_type,json=policyType,proto3" json:"policy_type,omitempty"`
	Source           bool                   `protobuf:"varint,3,opt,name=source,proto3" json:"source,omitempty"`
	OriginClassName  string                 `protobuf:"bytes,4,opt,name=origin_class_name,json=originClassName,proto3" json:"origin_class_name,omitempty"`
	ClassName        string                 `protobuf:"bytes,5,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	MethodName       string                 `protobuf:"bytes,6,opt,name=method_name,json=methodName,proto3" json:"method_name,omitempty"`
	Signature        string                 `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	CallerClassName  string                 `protobuf:"bytes,8,opt,name=caller_class_name,json=callerClassName,proto3" json:"caller_class_name,omitempty"`
	CallerMethodName string                 `protobuf:"bytes,9,opt,name=caller_method_name,json=callerMethodName,proto3" json:"caller_method_name,omitempty"`
	CallerLineNumber int32                  `protobuf:"varint,10,opt,name=caller_line_number,json=callerLineNumber,proto3" json:"caller_line_number,omitempty"`
	SourceHash       []int64                `protobuf:"varint,11,rep,packed,name=source_hash,json=sourceHash,proto3" json:"source_hash,omitempty"`
	TargetHash       []int64                `protobuf:"varint,12,rep,packed,name=target_hash,json=targetHash,proto3" json:"target_hash,omitempty"`
	TaintPosition    *IastTaintPosition     `protobuf:"bytes,13,opt,name=taint_position,json=taintPosition,proto3" json:"taint_position,omitempty"`
	Object           string                 `protobuf:"bytes,14,opt,name=object,proto3" json:"object,omitempty"`
	Parameters       []*IastParameter       `protobuf:"bytes,15,rep,name=parameters,proto3" json:"parameters,omitempty"`
	Return           string                 `protobuf:"bytes,16,opt,name=return,proto3" json:"return,omitempty"`
	TargetRange      []*IastTargetRange     `protobuf:"bytes,17,rep,name=target_range,json=targetRange,proto3" json:"target_range,omitempty"`
	SourceRange      []*IastTargetRange     `protobuf:"bytes,18,rep,name=source_range,json=sourceRange,proto3" json:"source_range,omitempty"`
	SourceType       []*IastSourceType      `protobuf:"bytes,19,rep,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	TraceId          string                 `protobuf:"bytes,20,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Stacks           []string               `protobuf:"bytes,21,rep,name=stacks,proto3" json:"stacks,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IastMethodEvent) Reset() {
	*x = IastMethodEvent{}
	mi := &file_iast_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IastMethodEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IastMethodEvent) ProtoMessage() {}

func (x *IastMethodEvent) ProtoReflect() protoreflect.Message {
	mi := &file_iast_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IastMethodEvent.ProtoReflect.Descriptor instead.
func (*IastMethodEvent) Descriptor() ([]byte, []int) {
	return file_iast_proto_rawDescGZIP(), []int{6}
}

func (x *IastMethodEvent) GetInvokeId() int32 {
	if x != nil {
		return x.InvokeId
	}
	return 0
}

func (x *IastMethodEvent) GetPolicyType() string {
	if x != nil {
		return x.PolicyType
	}
	return ""
}

func (x *IastMethodEvent) GetSource() bool {
	if x != nil {
		return x.Source
	}
	return false
}

func (x *IastMethodEvent) GetOriginClassName() string {
	if x != nil {
		return x.OriginClassName
	}
	return ""
}

func (x *IastMethodEvent) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *IastMethodEvent) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

func (x *IastMethodEvent) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *IastMethodEvent) GetCallerClassName() string {
	if x != nil {
		return x.CallerClassName
	}
	return ""
}

func (x *IastMethodEvent) GetCallerMethodName() string {
	if x != nil {
		return x.CallerMethodName
	}
	return ""
}

func (x *IastMethodEvent) GetCallerLineNumber() int32 {
	if x != nil {
		return x.CallerLineNumber
	}
	return 0
}

func (x *IastMethodEvent) GetSourceHash() []int64 {
	if x != nil {
		return x.SourceHash
	}
	return nil
}

func (x *IastMethodEvent) GetTargetHash() []int64 {
	if x != nil {
		return x.TargetHash
	}
	return nil
}

func (x *IastMethodEvent) GetTaintPosition() *IastTaintPosition {
	if x != nil {
		return x.TaintPosition
	}
	return nil
}

func (x *IastMethodEvent) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *IastMethodEvent) GetParameters() []*IastParameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *IastMethodEvent) GetReturn() string {
	if x != nil {
		return x.Return
	}
	return ""
}

func (x *IastMethodEvent) GetTargetRange() []*IastTargetRange {
	if x != nil {
		return x.TargetRange
	}
	return nil
}

func (x *IastMethodEvent) GetSourceRange() []*IastTargetRange {
	if x != nil {
		return x.SourceRange
	}
	return nil
}

func (x *IastMethodEvent) GetSourceType() []*IastSourceType {
	if x != nil {
		return x.SourceType
	}
	return nil
}

func (x *IastMethodEvent) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *IastMethodEvent) GetStacks() []string {
	if x != nil {
		return x.Stacks
	}
	return nil
}

type IastSaasReport struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	HttpProtocol   string                 `protobuf:"bytes,2,opt,name=http_protocol,json=httpProtocol,proto3" json:"http_protocol,omitempty"`
	HttpScheme     string                 `protobuf:"bytes,3,opt,name=http_scheme,json=httpScheme,proto3" json:"http_scheme,omitempty"`
	HttpMethod     string                 `protobuf:"bytes,4,opt,name=http_method,json=httpMethod,proto3" json:"http_method,omitempty"`
	Secure         bool                   `protobuf:"varint,5,opt,name=secure,proto3" json:"secure,omitempty"`
	Url            string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	Uri            string                 `protobuf:"bytes,7,opt,name=uri,proto3" json:"uri,omitempty"`
	ClientIp       string                 `protobuf:"bytes,8,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	QueryString    string                 `protobuf:"bytes,9,opt,name=query_string,json=queryString,proto3" json:"query_string,omitempty"`
	RequestHeader  string                 `protobuf:"bytes,10,opt,name=request_header,json=requestHeader,proto3" json:"request_header,omitempty"`
	RequestBody    string                 `protobuf:"bytes,11,opt,name=request_body,json=requestBody,proto3" json:"request_body,omitempty"`
	ResponseHeader string                 `protobuf:"bytes,12,opt,name=response_header,json=responseHeader,proto3" json:"response_header,omitempty"`
	ResponseBody   string                 `protobuf:"bytes,13,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"`
	ContextPath    string                 `protobuf:"bytes,14,opt,name=context_path,json=contextPath,proto3" json:"context_path,omitempty"`
	Pool           []*IastMethodEvent     `protobuf:"bytes,15,rep,name=pool,proto3" json:"pool,omitempty"`
	TraceId        string                 `protobuf:"bytes,16,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IastSaasReport) Reset() {
	*x = IastSaasReport{}
	mi := &file_iast_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IastSaasReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IastSaasReport) ProtoMessage() {}

func (x *IastSaasReport) ProtoReflect() protoreflect.Message {
	mi := &file_iast_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IastSaasReport.ProtoReflect.Descriptor instead.
func (*IastSaasReport) Descriptor() ([]byte, []int) {
	return file_iast_proto_rawDescGZIP(), []int{7}
}

func (x *IastSaasReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *IastSaasReport) GetHttpProtocol() string {
	if x != nil {
		return x.HttpProtocol
	}
	return ""
}

func (x *IastSaasReport) GetHttpScheme() string {
	if x != nil {
		return x.HttpScheme
	}
	return ""
}

func (x *IastSaasReport) GetHttpMethod() string {
	if x != nil {
		return x.HttpMethod
	}
	return ""
}

func (x *IastSaasReport) GetSecure() bool {
	if x != nil {
		return x.Secure
	}
	return false
}

func (x *IastSaasReport) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *IastSaasReport) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *IastSaasReport) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *IastSaasReport) GetQueryString() string {
	if x != nil {
		return x.QueryString
	}
	return ""
}

func (x *IastSaasReport) GetRequestHeader() string {
	if x != nil {
		return x.RequestHeader
	}
	return ""
}

func (x *IastSaasReport) GetRequestBody() string {
	if x != nil {
		return x.RequestBody
	}
	return ""
}

func (x *IastSaasReport) GetResponseHeader() string {
	if x != nil {
		return x.ResponseHeader
	}
	return ""
}

func (x *IastSaasReport) GetResponseBody() string {
	if x != nil {
		return x.ResponseBody
	}
	return ""
}

func (x *IastSaasReport) GetContextPath() string {
	if x != nil {
		return x.ContextPath
	}
	return ""
}

func (x *IastSaasReport) GetPool() []*IastMethodEvent {
	if x != nil {
		return x.Pool
	}
	return nil
}

func (x *IastSaasReport) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type IastHardCodeReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	File          string                 `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	ClassName     string                 `protobuf:"bytes,3,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	IsJdk         bool                   `protobuf:"varint,4,opt,name=is_jdk,json=isJdk,proto3" json:"is_jdk,omitempty"`
	FieldName     string                 `protobuf:"bytes,5,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	Value         string                 `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IastHardCodeReport) Reset() {
	*x = IastHardCodeReport{}
	mi := &file_iast_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IastHardCodeReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IastHardCodeReport) ProtoMessage() {}

func (x *IastHardCodeReport) ProtoReflect() protoreflect.Message {
	mi := &file_iast_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IastHardCodeReport.ProtoReflect.Descriptor instead.
func (*IastHardCodeReport) Descriptor() ([]byte, []int) {
	return file_iast_proto_rawDescGZIP(), []int{8}
}

func (x *IastHardCodeReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *IastHardCodeReport) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *IastHardCodeReport) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *IastHardCodeReport) GetIsJdk() bool {
	if x != nil {
		return x.IsJdk
	}
	return false
}

func (x *IastHardCodeReport) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *IastHardCodeReport) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_iast_proto protoreflect.FileDescriptor

const file_iast_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"iast.proto\"\xec\x03\n" +
	"\x10IastNormalReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\tvuln_type\x18\x02 \x01(\tR\bvulnType\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x16\n" +
	"\x06scheme\x18\x04 \x01(\tR\x06scheme\x12\x16\n" +
	"\x06method\x18\x05 \x01(\tR\x06method\x12\x16\n" +
	"\x06secure\x18\x06 \x01(\bR\x06secure\x12\x10\n" +
	"\x03url\x18\a \x01(\tR\x03url\x12\x10\n" +
	"\x03uri\x18\b \x01(\tR\x03uri\x12\x1b\n" +
	"\tclient_ip\x18\t \x01(\tR\bclientIp\x12!\n" +
	"\fquery_string\x18\n" +
	" \x01(\tR\vqueryString\x12%\n" +
	"\x0erequest_header\x18\v \x01(\tR\rrequestHeader\x12!\n" +
	"\frequest_body\x18\f \x01(\tR\vrequestBody\x12'\n" +
	"\x0fresponse_header\x18\r \x01(\tR\x0eresponseHeader\x12#\n" +
	"\rresponse_body\x18\x0e \x01(\tR\fresponseBody\x12!\n" +
	"\fcontext_path\x18\x0f \x01(\tR\vcontextPath\x12\x1d\n" +
	"\n" +
	"app_caller\x18\x10 \x03(\tR\tappCaller\"C\n" +
	"\x11IastTaintPosition\x12\x16\n" +
	"\x06source\x18\x01 \x03(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x02 \x03(\tR\x06target\";\n" +
	"\rIastParameter\x12\x14\n" +
	"\x05index\x18\x01 \x01(\tR\x05index\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"I\n" +
	"\tIastRange\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05start\x18\x02 \x01(\x05R\x05start\x12\x12\n" +
	"\x04stop\x18\x03 \x01(\x05R\x04stop\"I\n" +
	"\x0fIastTargetRange\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\x03R\x04hash\x12\"\n" +
	"\x06ranges\x18\x02 \x03(\v2\n" +
	".IastRangeR\x06ranges\"E\n" +
	"\x0eIastSourceType\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\x03R\x04hash\x12\x1f\n" +
	"\vsource_type\x18\x02 \x01(\tR\n" +
	"sourceType\"\xa5\x06\n" +
	"\x0fIastMethodEvent\x12\x1b\n" +
	"\tinvoke_id\x18\x01 \x01(\x05R\binvokeId\x12\x1f\n" +
	"\vpolicy_type\x18\x02 \x01(\tR\n" +
	"policyType\x12\x16\n" +
	"\x06source\x18\x03 \x01(\bR\x06source\x12*\n" +
	"\x11origin_class_name\x18\x04 \x01(\tR\x0foriginClassName\x12\x1d\n" +
	"\n" +
	"class_name\x18\x05 \x01(\tR\tclassName\x12\x1f\n" +
	"\vmethod_name\x18\x06 \x01(\tR\n" +
	"methodName\x12\x1c\n" +
	"\tsignature\x18\a \x01(\tR\tsignature\x12*\n" +
	"\x11caller_class_name\x18\b \x01(\tR\x0fcallerClassName\x12,\n" +
	"\x12caller_method_name\x18\t \x01(\tR\x10callerMethodName\x12,\n" +
	"\x12caller_line_number\x18\n" +
	" \x01(\x05R\x10callerLineNumber\x12\x1f\n" +
	"\vsource_hash\x18\v \x03(\x03R\n" +
	"sourceHash\x12\x1f\n" +
	"\vtarget_hash\x18\f \x03(\x03R\n" +
	"targetHash\x129\n" +
	"\x0etaint_position\x18\r \x01(\v2\x12.IastTaintPositionR\rtaintPosition\x12\x16\n" +
	"\x06object\x18\x0e \x01(\tR\x06object\x12.\n" +
	"\n" +
	"parameters\x18\x0f \x03(\v2\x0e.IastParameterR\n" +
	"parameters\x12\x16\n" +
	"\x06return\x18\x10 \x01(\tR\x06return\x123\n" +
	"\ftarget_range\x18\x11 \x03(\v2\x10.IastTargetRangeR\vtargetRange\x123\n" +
	"\fsource_range\x18\x12 \x03(\v2\x10.IastTargetRangeR\vsourceRange\x120\n" +
	"\vsource_type\x18\x13 \x03(\v2\x0f.IastSourceTypeR\n" +
	"sourceType\x12\x19\n" +
	"\btrace_id\x18\x14 \x01(\tR\atraceId\x12\x16\n" +
	"\x06stacks\x18\x15 \x03(\tR\x06stacks\"\x8a\x04\n" +
	"\x0eIastSaasReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12#\n" +
	"\rhttp_protocol\x18\x02 \x01(\tR\fhttpProtocol\x12\x1f\n" +
	"\vhttp_scheme\x18\x03 \x01(\tR\n" +
	"httpScheme\x12\x1f\n" +
	"\vhttp_method\x18\x04 \x01(\tR\n" +
	"httpMethod\x12\x16\n" +
	"\x06secure\x18\x05 \x01(\bR\x06secure\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x12\x10\n" +
	"\x03uri\x18\a \x01(\tR\x03uri\x12\x1b\n" +
	"\tclient_ip\x18\b \x01(\tR\bclientIp\x12!\n" +
	"\fquery_string\x18\t \x01(\tR\vqueryString\x12%\n" +
	"\x0erequest_header\x18\n" +
	" \x01(\tR\rrequestHeader\x12!\n" +
	"\frequest_body\x18\v \x01(\tR\vrequestBody\x12'\n" +
	"\x0fresponse_header\x18\f \x01(\tR\x0eresponseHeader\x12#\n" +
	"\rresponse_body\x18\r \x01(\tR\fresponseBody\x12!\n" +
	"\fcontext_path\x18\x0e \x01(\tR\vcontextPath\x12$\n" +
	"\x04pool\x18\x0f \x03(\v2\x10.IastMethodEventR\x04pool\x12\x19\n" +
	"\btrace_id\x18\x10 \x01(\tR\atraceId\"\xae\x01\n" +
	"\x12IastHardCodeReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x12\n" +
	"\x04file\x18\x02 \x01(\tR\x04file\x12\x1d\n" +
	"\n" +
	"class_name\x18\x03 \x01(\tR\tclassName\x12\x15\n" +
	"\x06is_jdk\x18\x04 \x01(\bR\x05isJdk\x12\x1d\n" +
	"\n" +
	"field_name\x18\x05 \x01(\tR\tfieldName\x12\x14\n" +
	"\x05value\x18\x06 \x01(\tR\x05valueB)\n" +
	"\n" +
	"sothoth.pbP\x01Z\x19sothoth-nodeagent/pkg/pb/b\x06proto3"

var (
	file_iast_proto_rawDescOnce sync.Once
	file_iast_proto_rawDescData []byte
)

func file_iast_proto_rawDescGZIP() []byte {
	file_iast_proto_rawDescOnce.Do(func() {
		file_iast_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iast_proto_rawDesc), len(file_iast_proto_rawDesc)))
	})
	return file_iast_proto_rawDescData
}

var file_iast_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_iast_proto_goTypes = []any{
	(*IastNormalReport)(nil),   // 0: IastNormalReport
	(*IastTaintPosition)(nil),  // 1: IastTaintPosition
	(*IastParameter)(nil),      // 2: IastParameter
	(*IastRange)(nil),          // 3: IastRange
	(*IastTargetRange)(nil),    // 4: IastTargetRange
	(*IastSourceType)(nil),     // 5: IastSourceType
	(*IastMethodEvent)(nil),    // 6: IastMethodEvent
	(*IastSaasReport)(nil),     // 7: IastSaasReport
	(*IastHardCodeReport)(nil), // 8: IastHardCodeReport
}
var file_iast_proto_depIdxs = []int32{
	3, // 0: IastTargetRange.ranges:type_name -> IastRange
	1, // 1: IastMethodEvent.taint_position:type_name -> IastTaintPosition
	2, // 2: IastMethodEvent.parameters:type_name -> IastParameter
	4, // 3: IastMethodEvent.target_range:type_name -> IastTargetRange
	4, // 4: IastMethodEvent.source_range:type_name -> IastTargetRange
	5, // 5: IastMethodEvent.source_type:type_name -> IastSourceType
	6, // 6: IastSaasReport.pool:type_name -> IastMethodEvent
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_iast_proto_init() }
func file_iast_proto_init() {
	if File_iast_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iast_proto_rawDesc), len(file_iast_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_iast_proto_goTypes,
		DependencyIndexes: file_iast_proto_depIdxs,
		MessageInfos:      file_iast_proto_msgTypes,
	}.Build()
	File_iast_proto = out.File
	file_iast_proto_goTypes = nil
	file_iast_proto_depIdxs = nil
}
