// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: mcp.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type McpHttpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HttpMethod    string                 `protobuf:"bytes,1,opt,name=http_method,json=httpMethod,proto3" json:"http_method,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *McpHttpRequest) Reset() {
	*x = McpHttpRequest{}
	mi := &file_mcp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McpHttpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McpHttpRequest) ProtoMessage() {}

func (x *McpHttpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McpHttpRequest.ProtoReflect.Descriptor instead.
func (*McpHttpRequest) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{0}
}

func (x *McpHttpRequest) GetHttpMethod() string {
	if x != nil {
		return x.HttpMethod
	}
	return ""
}

func (x *McpHttpRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *McpHttpRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *McpHttpRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type McpHttpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *McpHttpResponse) Reset() {
	*x = McpHttpResponse{}
	mi := &file_mcp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McpHttpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McpHttpResponse) ProtoMessage() {}

func (x *McpHttpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McpHttpResponse.ProtoReflect.Descriptor instead.
func (*McpHttpResponse) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{1}
}

func (x *McpHttpResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *McpHttpResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *McpHttpResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type McpInitializeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestJson   []byte                 `protobuf:"bytes,1,opt,name=request_json,json=requestJson,proto3" json:"request_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *McpInitializeRequest) Reset() {
	*x = McpInitializeRequest{}
	mi := &file_mcp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McpInitializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McpInitializeRequest) ProtoMessage() {}

func (x *McpInitializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McpInitializeRequest.ProtoReflect.Descriptor instead.
func (*McpInitializeRequest) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{2}
}

func (x *McpInitializeRequest) GetRequestJson() []byte {
	if x != nil {
		return x.RequestJson
	}
	return nil
}

type McpInitializeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ResponseJson  []byte                 `protobuf:"bytes,2,opt,name=response_json,json=responseJson,proto3" json:"response_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *McpInitializeResponse) Reset() {
	*x = McpInitializeResponse{}
	mi := &file_mcp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McpInitializeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McpInitializeResponse) ProtoMessage() {}

func (x *McpInitializeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McpInitializeResponse.ProtoReflect.Descriptor instead.
func (*McpInitializeResponse) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{3}
}

func (x *McpInitializeResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *McpInitializeResponse) GetResponseJson() []byte {
	if x != nil {
		return x.ResponseJson
	}
	return nil
}

type McpJsonRpcRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SessionId        string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	BackendSessionId string                 `protobuf:"bytes,2,opt,name=backend_session_id,json=backendSessionId,proto3" json:"backend_session_id,omitempty"`
	RequestJson      []byte                 `protobuf:"bytes,3,opt,name=request_json,json=requestJson,proto3" json:"request_json,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *McpJsonRpcRequest) Reset() {
	*x = McpJsonRpcRequest{}
	mi := &file_mcp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McpJsonRpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McpJsonRpcRequest) ProtoMessage() {}

func (x *McpJsonRpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McpJsonRpcRequest.ProtoReflect.Descriptor instead.
func (*McpJsonRpcRequest) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{4}
}

func (x *McpJsonRpcRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *McpJsonRpcRequest) GetBackendSessionId() string {
	if x != nil {
		return x.BackendSessionId
	}
	return ""
}

func (x *McpJsonRpcRequest) GetRequestJson() []byte {
	if x != nil {
		return x.RequestJson
	}
	return nil
}

type McpJsonRpcResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ResponseJson  []byte                 `protobuf:"bytes,2,opt,name=response_json,json=responseJson,proto3" json:"response_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *McpJsonRpcResponse) Reset() {
	*x = McpJsonRpcResponse{}
	mi := &file_mcp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McpJsonRpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McpJsonRpcResponse) ProtoMessage() {}

func (x *McpJsonRpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McpJsonRpcResponse.ProtoReflect.Descriptor instead.
func (*McpJsonRpcResponse) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{5}
}

func (x *McpJsonRpcResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *McpJsonRpcResponse) GetResponseJson() []byte {
	if x != nil {
		return x.ResponseJson
	}
	return nil
}

type McpEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *McpEvent) Reset() {
	*x = McpEvent{}
	mi := &file_mcp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McpEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McpEvent) ProtoMessage() {}

func (x *McpEvent) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McpEvent.ProtoReflect.Descriptor instead.
func (*McpEvent) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{6}
}

func (x *McpEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *McpEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *McpEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *McpEvent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type McpSessionClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *McpSessionClose) Reset() {
	*x = McpSessionClose{}
	mi := &file_mcp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McpSessionClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McpSessionClose) ProtoMessage() {}

func (x *McpSessionClose) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McpSessionClose.ProtoReflect.Descriptor instead.
func (*McpSessionClose) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{7}
}

func (x *McpSessionClose) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

var File_mcp_proto protoreflect.FileDescriptor

const file_mcp_proto_rawDesc = "" +
	"\n" +
	"\tmcp.proto\"\xcd\x01\n" +
	"\x0eMcpHttpRequest\x12\x1f\n" +
	"\vhttp_method\x18\x01 \x01(\tR\n" +
	"httpMethod\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x126\n" +
	"\aheaders\x18\x03 \x03(\v2\x1c.McpHttpRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbb\x01\n" +
	"\x0fMcpHttpResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x127\n" +
	"\aheaders\x18\x02 \x03(\v2\x1d.McpHttpResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"9\n" +
	"\x14McpInitializeRequest\x12!\n" +
	"\frequest_json\x18\x01 \x01(\fR\vrequestJson\"[\n" +
	"\x15McpInitializeResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rresponse_json\x18\x02 \x01(\fR\fresponseJson\"\x83\x01\n" +
	"\x11McpJsonRpcRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12,\n" +
	"\x12backend_session_id\x18\x02 \x01(\tR\x10backendSessionId\x12!\n" +
	"\frequest_json\x18\x03 \x01(\fR\vrequestJson\"X\n" +
	"\x12McpJsonRpcResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rresponse_json\x18\x02 \x01(\fR\fresponseJson\"w\n" +
	"\bMcpEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"0\n" +
	"\x0fMcpSessionClose\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionIdB)\n" +
	"\n" +
	"gaiasec.pbP\x01Z\x19gaiasec-nodeagent/pkg/pb/b\x06proto3"

var (
	file_mcp_proto_rawDescOnce sync.Once
	file_mcp_proto_rawDescData []byte
)

func file_mcp_proto_rawDescGZIP() []byte {
	file_mcp_proto_rawDescOnce.Do(func() {
		file_mcp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcp_proto_rawDesc), len(file_mcp_proto_rawDesc)))
	})
	return file_mcp_proto_rawDescData
}

var file_mcp_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_mcp_proto_goTypes = []any{
	(*McpHttpRequest)(nil),        // 0: McpHttpRequest
	(*McpHttpResponse)(nil),       // 1: McpHttpResponse
	(*McpInitializeRequest)(nil),  // 2: McpInitializeRequest
	(*McpInitializeResponse)(nil), // 3: McpInitializeResponse
	(*McpJsonRpcRequest)(nil),     // 4: McpJsonRpcRequest
	(*McpJsonRpcResponse)(nil),    // 5: McpJsonRpcResponse
	(*McpEvent)(nil),              // 6: McpEvent
	(*McpSessionClose)(nil),       // 7: McpSessionClose
	nil,                           // 8: McpHttpRequest.HeadersEntry
	nil,                           // 9: McpHttpResponse.HeadersEntry
}
var file_mcp_proto_depIdxs = []int32{
	8, // 0: McpHttpRequest.headers:type_name -> McpHttpRequest.HeadersEntry
	9, // 1: McpHttpResponse.headers:type_name -> McpHttpResponse.HeadersEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mcp_proto_init() }
func file_mcp_proto_init() {
	if File_mcp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcp_proto_rawDesc), len(file_mcp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mcp_proto_goTypes,
		DependencyIndexes: file_mcp_proto_depIdxs,
		MessageInfos:      file_mcp_proto_msgTypes,
	}.Build()
	File_mcp_proto = out.File
	file_mcp_proto_goTypes = nil
	file_mcp_proto_depIdxs = nil
}
