// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: message_type.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义消息类型枚举
type MessageType int32

const (
	MessageType_UNKNOWN                   MessageType = 0
	MessageType_REGISTER                  MessageType = 1
	MessageType_UNREGISTER                MessageType = 2
	MessageType_HEARTBEAT                 MessageType = 3
	MessageType_INIT                      MessageType = 4
	MessageType_PROCESSES_REQUEST         MessageType = 5
	MessageType_PROCESSES_RESPONSE        MessageType = 6
	MessageType_PROCESS_METADATA_REQUEST  MessageType = 13
	MessageType_PROCESS_METADATA_RESPONSE MessageType = 14
	MessageType_DEPLOY_PLUGIN_REQUEST     MessageType = 7
	MessageType_DEPLOY_PLUGIN_RESPONSE    MessageType = 8
	MessageType_EXECUTE_COMMAND_REQUEST   MessageType = 9
	MessageType_EXECUTE_COMMAND_RESPONSE  MessageType = 10
	MessageType_NETWORK_REQUEST           MessageType = 11
	MessageType_NETWORK_RESPONSE          MessageType = 12
	// 文件系统
	MessageType_FS_LIST_DIR_REQUEST        MessageType = 20
	MessageType_FS_LIST_DIR_RESPONSE       MessageType = 21
	MessageType_FS_READ_FILE_REQUEST       MessageType = 22
	MessageType_FS_READ_FILE_RESPONSE      MessageType = 23
	MessageType_FS_WRITE_FILE_REQUEST      MessageType = 24
	MessageType_FS_WRITE_FILE_RESPONSE     MessageType = 25
	MessageType_FS_CREATE_FILE_REQUEST     MessageType = 26
	MessageType_FS_CREATE_FILE_RESPONSE    MessageType = 27
	MessageType_FS_CREATE_DIR_REQUEST      MessageType = 28
	MessageType_FS_CREATE_DIR_RESPONSE     MessageType = 29
	MessageType_FS_DELETE_REQUEST          MessageType = 30
	MessageType_FS_DELETE_RESPONSE         MessageType = 31
	MessageType_FS_RENAME_REQUEST          MessageType = 32
	MessageType_FS_RENAME_RESPONSE         MessageType = 33
	MessageType_FS_DOWNLOAD_REQUEST        MessageType = 34
	MessageType_FS_ARCHIVE_CREATE_REQUEST  MessageType = 35
	MessageType_FS_ARCHIVE_CREATE_RESPONSE MessageType = 36
	// 代理
	MessageType_PROXY_ESTABLISH      MessageType = 40 // establish
	MessageType_PROXY_DATA_TO_SERVER MessageType = 41 // data  nodeagent -> server
	MessageType_PROXY_DATA_TO_CLIENT MessageType = 42 // data  nodeagent -> client
	MessageType_PROXY_CLOSE          MessageType = 43 // finish
	// Terminal
	MessageType_TERMINAL_CREATE_REQUEST  MessageType = 45
	MessageType_TERMINAL_CREATE_RESPONSE MessageType = 46
	MessageType_TERMINAL_CLOSE           MessageType = 47
	MessageType_TERMINAL_ERROR           MessageType = 48
	// Java Agent
	MessageType_WEB_ROUTES_REQUEST   MessageType = 50
	MessageType_WEB_ROUTES_RESPONSE  MessageType = 51
	MessageType_SCA_RESPONSE         MessageType = 52
	MessageType_IAST_NORMAL_REPORT   MessageType = 53
	MessageType_IAST_SAAS_REPORT     MessageType = 54
	MessageType_IAST_HARDCODE_REPORT MessageType = 55
	MessageType_FUZZ_REQUEST         MessageType = 56
	MessageType_FUZZ_RESPONSE        MessageType = 57
	MessageType_TRACE_REPORT         MessageType = 58
	MessageType_HTTP_SEND_REQUEST    MessageType = 59
	MessageType_HTTP_SEND_RESPONSE   MessageType = 60
	MessageType_PUSH                 MessageType = 80
	MessageType_PULL                 MessageType = 81
	// 容器信息
	MessageType_CONTAINER_REQUEST  MessageType = 100
	MessageType_CONTAINER_RESPONSE MessageType = 101
	// 容器逃逸分析
	MessageType_CONTAINER_ESCAPE_REQUEST  MessageType = 102
	MessageType_CONTAINER_ESCAPE_RESPONSE MessageType = 103
	// 本地提权分析
	MessageType_PRIVILEGE_ESCALATION_REQUEST  MessageType = 104
	MessageType_PRIVILEGE_ESCALATION_RESPONSE MessageType = 105
	// K8s 集群内提权分析
	MessageType_K8S_PRIVILEGE_ESCALATION_REQUEST  MessageType = 106
	MessageType_K8S_PRIVILEGE_ESCALATION_RESPONSE MessageType = 107
	// 数据源信息
	MessageType_DATASOURCE_LIST_REQUEST   MessageType = 70
	MessageType_DATASOURCE_LIST_RESPONSE  MessageType = 71
	MessageType_DATABASE_CATALOG_REQUEST  MessageType = 72
	MessageType_DATABASE_CATALOG_RESPONSE MessageType = 73
	MessageType_DATABASE_EXECUTE_REQUEST  MessageType = 74
	MessageType_DATABASE_EXECUTE_RESPONSE MessageType = 75
	// MCP bridge
	MessageType_MCP_HTTP_REQUEST        MessageType = 108
	MessageType_MCP_HTTP_RESPONSE       MessageType = 109
	MessageType_MCP_INITIALIZE_REQUEST  MessageType = 110
	MessageType_MCP_INITIALIZE_RESPONSE MessageType = 111
	MessageType_MCP_JSONRPC_REQUEST     MessageType = 112
	MessageType_MCP_JSONRPC_RESPONSE    MessageType = 113
	MessageType_MCP_EVENT               MessageType = 114
	MessageType_MCP_SESSION_CLOSE       MessageType = 115
	// Tool call bridge
	MessageType_TOOL_CALL_REQUEST  MessageType = 116
	MessageType_TOOL_CALL_RESPONSE MessageType = 117
	MessageType_TOOL_CALL_EVENT    MessageType = 118
	// JVM 诊断工具 (120-139)
	MessageType_JVM_REQUEST          MessageType = 120
	MessageType_JVM_RESPONSE         MessageType = 121
	MessageType_THREAD_REQUEST       MessageType = 122
	MessageType_THREAD_RESPONSE      MessageType = 123
	MessageType_SYS_PROP_REQUEST     MessageType = 124
	MessageType_SYS_PROP_RESPONSE    MessageType = 125
	MessageType_SYS_ENV_REQUEST      MessageType = 126
	MessageType_SYS_ENV_RESPONSE     MessageType = 127
	MessageType_MEMORY_REQUEST       MessageType = 128
	MessageType_MEMORY_RESPONSE      MessageType = 129
	MessageType_VM_OPTION_REQUEST    MessageType = 130
	MessageType_VM_OPTION_RESPONSE   MessageType = 131
	MessageType_MBEAN_REQUEST        MessageType = 132
	MessageType_MBEAN_RESPONSE       MessageType = 133
	MessageType_CLASSLOADER_REQUEST  MessageType = 134
	MessageType_CLASSLOADER_RESPONSE MessageType = 135
	MessageType_DASHBOARD_REQUEST    MessageType = 136
	MessageType_DASHBOARD_RESPONSE   MessageType = 137
	MessageType_VM_TOOL_REQUEST      MessageType = 138
	MessageType_VM_TOOL_RESPONSE     MessageType = 139
	// 类搜索工具 (140-149)
	MessageType_SEARCH_CLASS_REQUEST   MessageType = 140
	MessageType_SEARCH_CLASS_RESPONSE  MessageType = 141
	MessageType_SEARCH_METHOD_REQUEST  MessageType = 142
	MessageType_SEARCH_METHOD_RESPONSE MessageType = 143
	MessageType_GET_STATIC_REQUEST     MessageType = 144
	MessageType_GET_STATIC_RESPONSE    MessageType = 145
	MessageType_OGNL_REQUEST           MessageType = 146
	MessageType_OGNL_RESPONSE          MessageType = 147
	MessageType_HEAP_DUMP_REQUEST      MessageType = 148
	MessageType_HEAP_DUMP_RESPONSE     MessageType = 149
	// 类增强工具 (150-159)
	MessageType_JAD_REQUEST              MessageType = 150
	MessageType_JAD_RESPONSE             MessageType = 151
	MessageType_DUMP_CLASS_REQUEST       MessageType = 152
	MessageType_DUMP_CLASS_RESPONSE      MessageType = 153
	MessageType_MEMORY_COMPILER_REQUEST  MessageType = 154
	MessageType_MEMORY_COMPILER_RESPONSE MessageType = 155
	MessageType_REDEFINE_REQUEST         MessageType = 156
	MessageType_REDEFINE_RESPONSE        MessageType = 157
	MessageType_RETRANSFORM_REQUEST      MessageType = 158
	MessageType_RETRANSFORM_RESPONSE     MessageType = 159
	// 异步流式诊断工具 (160-179)
	MessageType_WATCH_REQUEST        MessageType = 160
	MessageType_WATCH_RESPONSE       MessageType = 161
	MessageType_WATCH_EVENT          MessageType = 162
	MessageType_TRACE_REQUEST        MessageType = 163
	MessageType_TRACE_RESPONSE       MessageType = 164
	MessageType_TRACE_EVENT          MessageType = 165
	MessageType_STACK_REQUEST        MessageType = 166
	MessageType_STACK_RESPONSE       MessageType = 167
	MessageType_STACK_EVENT          MessageType = 168
	MessageType_MONITOR_REQUEST      MessageType = 169
	MessageType_MONITOR_RESPONSE     MessageType = 170
	MessageType_MONITOR_EVENT        MessageType = 171
	MessageType_TIME_TUNNEL_REQUEST  MessageType = 172
	MessageType_TIME_TUNNEL_RESPONSE MessageType = 173
	MessageType_TIME_TUNNEL_EVENT    MessageType = 174
	MessageType_TASK_CANCEL_REQUEST  MessageType = 175
	MessageType_TASK_CANCEL_RESPONSE MessageType = 176
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:   "UNKNOWN",
		1:   "REGISTER",
		2:   "UNREGISTER",
		3:   "HEARTBEAT",
		4:   "INIT",
		5:   "PROCESSES_REQUEST",
		6:   "PROCESSES_RESPONSE",
		13:  "PROCESS_METADATA_REQUEST",
		14:  "PROCESS_METADATA_RESPONSE",
		7:   "DEPLOY_PLUGIN_REQUEST",
		8:   "DEPLOY_PLUGIN_RESPONSE",
		9:   "EXECUTE_COMMAND_REQUEST",
		10:  "EXECUTE_COMMAND_RESPONSE",
		11:  "NETWORK_REQUEST",
		12:  "NETWORK_RESPONSE",
		20:  "FS_LIST_DIR_REQUEST",
		21:  "FS_LIST_DIR_RESPONSE",
		22:  "FS_READ_FILE_REQUEST",
		23:  "FS_READ_FILE_RESPONSE",
		24:  "FS_WRITE_FILE_REQUEST",
		25:  "FS_WRITE_FILE_RESPONSE",
		26:  "FS_CREATE_FILE_REQUEST",
		27:  "FS_CREATE_FILE_RESPONSE",
		28:  "FS_CREATE_DIR_REQUEST",
		29:  "FS_CREATE_DIR_RESPONSE",
		30:  "FS_DELETE_REQUEST",
		31:  "FS_DELETE_RESPONSE",
		32:  "FS_RENAME_REQUEST",
		33:  "FS_RENAME_RESPONSE",
		34:  "FS_DOWNLOAD_REQUEST",
		35:  "FS_ARCHIVE_CREATE_REQUEST",
		36:  "FS_ARCHIVE_CREATE_RESPONSE",
		40:  "PROXY_ESTABLISH",
		41:  "PROXY_DATA_TO_SERVER",
		42:  "PROXY_DATA_TO_CLIENT",
		43:  "PROXY_CLOSE",
		45:  "TERMINAL_CREATE_REQUEST",
		46:  "TERMINAL_CREATE_RESPONSE",
		47:  "TERMINAL_CLOSE",
		48:  "TERMINAL_ERROR",
		50:  "WEB_ROUTES_REQUEST",
		51:  "WEB_ROUTES_RESPONSE",
		52:  "SCA_RESPONSE",
		53:  "IAST_NORMAL_REPORT",
		54:  "IAST_SAAS_REPORT",
		55:  "IAST_HARDCODE_REPORT",
		56:  "FUZZ_REQUEST",
		57:  "FUZZ_RESPONSE",
		58:  "TRACE_REPORT",
		59:  "HTTP_SEND_REQUEST",
		60:  "HTTP_SEND_RESPONSE",
		80:  "PUSH",
		81:  "PULL",
		100: "CONTAINER_REQUEST",
		101: "CONTAINER_RESPONSE",
		102: "CONTAINER_ESCAPE_REQUEST",
		103: "CONTAINER_ESCAPE_RESPONSE",
		104: "PRIVILEGE_ESCALATION_REQUEST",
		105: "PRIVILEGE_ESCALATION_RESPONSE",
		106: "K8S_PRIVILEGE_ESCALATION_REQUEST",
		107: "K8S_PRIVILEGE_ESCALATION_RESPONSE",
		70:  "DATASOURCE_LIST_REQUEST",
		71:  "DATASOURCE_LIST_RESPONSE",
		72:  "DATABASE_CATALOG_REQUEST",
		73:  "DATABASE_CATALOG_RESPONSE",
		74:  "DATABASE_EXECUTE_REQUEST",
		75:  "DATABASE_EXECUTE_RESPONSE",
		108: "MCP_HTTP_REQUEST",
		109: "MCP_HTTP_RESPONSE",
		110: "MCP_INITIALIZE_REQUEST",
		111: "MCP_INITIALIZE_RESPONSE",
		112: "MCP_JSONRPC_REQUEST",
		113: "MCP_JSONRPC_RESPONSE",
		114: "MCP_EVENT",
		115: "MCP_SESSION_CLOSE",
		116: "TOOL_CALL_REQUEST",
		117: "TOOL_CALL_RESPONSE",
		118: "TOOL_CALL_EVENT",
		120: "JVM_REQUEST",
		121: "JVM_RESPONSE",
		122: "THREAD_REQUEST",
		123: "THREAD_RESPONSE",
		124: "SYS_PROP_REQUEST",
		125: "SYS_PROP_RESPONSE",
		126: "SYS_ENV_REQUEST",
		127: "SYS_ENV_RESPONSE",
		128: "MEMORY_REQUEST",
		129: "MEMORY_RESPONSE",
		130: "VM_OPTION_REQUEST",
		131: "VM_OPTION_RESPONSE",
		132: "MBEAN_REQUEST",
		133: "MBEAN_RESPONSE",
		134: "CLASSLOADER_REQUEST",
		135: "CLASSLOADER_RESPONSE",
		136: "DASHBOARD_REQUEST",
		137: "DASHBOARD_RESPONSE",
		138: "VM_TOOL_REQUEST",
		139: "VM_TOOL_RESPONSE",
		140: "SEARCH_CLASS_REQUEST",
		141: "SEARCH_CLASS_RESPONSE",
		142: "SEARCH_METHOD_REQUEST",
		143: "SEARCH_METHOD_RESPONSE",
		144: "GET_STATIC_REQUEST",
		145: "GET_STATIC_RESPONSE",
		146: "OGNL_REQUEST",
		147: "OGNL_RESPONSE",
		148: "HEAP_DUMP_REQUEST",
		149: "HEAP_DUMP_RESPONSE",
		150: "JAD_REQUEST",
		151: "JAD_RESPONSE",
		152: "DUMP_CLASS_REQUEST",
		153: "DUMP_CLASS_RESPONSE",
		154: "MEMORY_COMPILER_REQUEST",
		155: "MEMORY_COMPILER_RESPONSE",
		156: "REDEFINE_REQUEST",
		157: "REDEFINE_RESPONSE",
		158: "RETRANSFORM_REQUEST",
		159: "RETRANSFORM_RESPONSE",
		160: "WATCH_REQUEST",
		161: "WATCH_RESPONSE",
		162: "WATCH_EVENT",
		163: "TRACE_REQUEST",
		164: "TRACE_RESPONSE",
		165: "TRACE_EVENT",
		166: "STACK_REQUEST",
		167: "STACK_RESPONSE",
		168: "STACK_EVENT",
		169: "MONITOR_REQUEST",
		170: "MONITOR_RESPONSE",
		171: "MONITOR_EVENT",
		172: "TIME_TUNNEL_REQUEST",
		173: "TIME_TUNNEL_RESPONSE",
		174: "TIME_TUNNEL_EVENT",
		175: "TASK_CANCEL_REQUEST",
		176: "TASK_CANCEL_RESPONSE",
	}
	MessageType_value = map[string]int32{
		"UNKNOWN":                           0,
		"REGISTER":                          1,
		"UNREGISTER":                        2,
		"HEARTBEAT":                         3,
		"INIT":                              4,
		"PROCESSES_REQUEST":                 5,
		"PROCESSES_RESPONSE":                6,
		"PROCESS_METADATA_REQUEST":          13,
		"PROCESS_METADATA_RESPONSE":         14,
		"DEPLOY_PLUGIN_REQUEST":             7,
		"DEPLOY_PLUGIN_RESPONSE":            8,
		"EXECUTE_COMMAND_REQUEST":           9,
		"EXECUTE_COMMAND_RESPONSE":          10,
		"NETWORK_REQUEST":                   11,
		"NETWORK_RESPONSE":                  12,
		"FS_LIST_DIR_REQUEST":               20,
		"FS_LIST_DIR_RESPONSE":              21,
		"FS_READ_FILE_REQUEST":              22,
		"FS_READ_FILE_RESPONSE":             23,
		"FS_WRITE_FILE_REQUEST":             24,
		"FS_WRITE_FILE_RESPONSE":            25,
		"FS_CREATE_FILE_REQUEST":            26,
		"FS_CREATE_FILE_RESPONSE":           27,
		"FS_CREATE_DIR_REQUEST":             28,
		"FS_CREATE_DIR_RESPONSE":            29,
		"FS_DELETE_REQUEST":                 30,
		"FS_DELETE_RESPONSE":                31,
		"FS_RENAME_REQUEST":                 32,
		"FS_RENAME_RESPONSE":                33,
		"FS_DOWNLOAD_REQUEST":               34,
		"FS_ARCHIVE_CREATE_REQUEST":         35,
		"FS_ARCHIVE_CREATE_RESPONSE":        36,
		"PROXY_ESTABLISH":                   40,
		"PROXY_DATA_TO_SERVER":              41,
		"PROXY_DATA_TO_CLIENT":              42,
		"PROXY_CLOSE":                       43,
		"TERMINAL_CREATE_REQUEST":           45,
		"TERMINAL_CREATE_RESPONSE":          46,
		"TERMINAL_CLOSE":                    47,
		"TERMINAL_ERROR":                    48,
		"WEB_ROUTES_REQUEST":                50,
		"WEB_ROUTES_RESPONSE":               51,
		"SCA_RESPONSE":                      52,
		"IAST_NORMAL_REPORT":                53,
		"IAST_SAAS_REPORT":                  54,
		"IAST_HARDCODE_REPORT":              55,
		"FUZZ_REQUEST":                      56,
		"FUZZ_RESPONSE":                     57,
		"TRACE_REPORT":                      58,
		"HTTP_SEND_REQUEST":                 59,
		"HTTP_SEND_RESPONSE":                60,
		"PUSH":                              80,
		"PULL":                              81,
		"CONTAINER_REQUEST":                 100,
		"CONTAINER_RESPONSE":                101,
		"CONTAINER_ESCAPE_REQUEST":          102,
		"CONTAINER_ESCAPE_RESPONSE":         103,
		"PRIVILEGE_ESCALATION_REQUEST":      104,
		"PRIVILEGE_ESCALATION_RESPONSE":     105,
		"K8S_PRIVILEGE_ESCALATION_REQUEST":  106,
		"K8S_PRIVILEGE_ESCALATION_RESPONSE": 107,
		"DATASOURCE_LIST_REQUEST":           70,
		"DATASOURCE_LIST_RESPONSE":          71,
		"DATABASE_CATALOG_REQUEST":          72,
		"DATABASE_CATALOG_RESPONSE":         73,
		"DATABASE_EXECUTE_REQUEST":          74,
		"DATABASE_EXECUTE_RESPONSE":         75,
		"MCP_HTTP_REQUEST":                  108,
		"MCP_HTTP_RESPONSE":                 109,
		"MCP_INITIALIZE_REQUEST":            110,
		"MCP_INITIALIZE_RESPONSE":           111,
		"MCP_JSONRPC_REQUEST":               112,
		"MCP_JSONRPC_RESPONSE":              113,
		"MCP_EVENT":                         114,
		"MCP_SESSION_CLOSE":                 115,
		"TOOL_CALL_REQUEST":                 116,
		"TOOL_CALL_RESPONSE":                117,
		"TOOL_CALL_EVENT":                   118,
		"JVM_REQUEST":                       120,
		"JVM_RESPONSE":                      121,
		"THREAD_REQUEST":                    122,
		"THREAD_RESPONSE":                   123,
		"SYS_PROP_REQUEST":                  124,
		"SYS_PROP_RESPONSE":                 125,
		"SYS_ENV_REQUEST":                   126,
		"SYS_ENV_RESPONSE":                  127,
		"MEMORY_REQUEST":                    128,
		"MEMORY_RESPONSE":                   129,
		"VM_OPTION_REQUEST":                 130,
		"VM_OPTION_RESPONSE":                131,
		"MBEAN_REQUEST":                     132,
		"MBEAN_RESPONSE":                    133,
		"CLASSLOADER_REQUEST":               134,
		"CLASSLOADER_RESPONSE":              135,
		"DASHBOARD_REQUEST":                 136,
		"DASHBOARD_RESPONSE":                137,
		"VM_TOOL_REQUEST":                   138,
		"VM_TOOL_RESPONSE":                  139,
		"SEARCH_CLASS_REQUEST":              140,
		"SEARCH_CLASS_RESPONSE":             141,
		"SEARCH_METHOD_REQUEST":             142,
		"SEARCH_METHOD_RESPONSE":            143,
		"GET_STATIC_REQUEST":                144,
		"GET_STATIC_RESPONSE":               145,
		"OGNL_REQUEST":                      146,
		"OGNL_RESPONSE":                     147,
		"HEAP_DUMP_REQUEST":                 148,
		"HEAP_DUMP_RESPONSE":                149,
		"JAD_REQUEST":                       150,
		"JAD_RESPONSE":                      151,
		"DUMP_CLASS_REQUEST":                152,
		"DUMP_CLASS_RESPONSE":               153,
		"MEMORY_COMPILER_REQUEST":           154,
		"MEMORY_COMPILER_RESPONSE":          155,
		"REDEFINE_REQUEST":                  156,
		"REDEFINE_RESPONSE":                 157,
		"RETRANSFORM_REQUEST":               158,
		"RETRANSFORM_RESPONSE":              159,
		"WATCH_REQUEST":                     160,
		"WATCH_RESPONSE":                    161,
		"WATCH_EVENT":                       162,
		"TRACE_REQUEST":                     163,
		"TRACE_RESPONSE":                    164,
		"TRACE_EVENT":                       165,
		"STACK_REQUEST":                     166,
		"STACK_RESPONSE":                    167,
		"STACK_EVENT":                       168,
		"MONITOR_REQUEST":                   169,
		"MONITOR_RESPONSE":                  170,
		"MONITOR_EVENT":                     171,
		"TIME_TUNNEL_REQUEST":               172,
		"TIME_TUNNEL_RESPONSE":              173,
		"TIME_TUNNEL_EVENT":                 174,
		"TASK_CANCEL_REQUEST":               175,
		"TASK_CANCEL_RESPONSE":              176,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_type_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_message_type_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_message_type_proto_rawDescGZIP(), []int{0}
}

var File_message_type_proto protoreflect.FileDescriptor

const file_message_type_proto_rawDesc = "" +
	"\n" +
	"\x12message_type.proto*\xbb\x19\n" +
	"\vMessageType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bREGISTER\x10\x01\x12\x0e\n" +
	"\n" +
	"UNREGISTER\x10\x02\x12\r\n" +
	"\tHEARTBEAT\x10\x03\x12\b\n" +
	"\x04INIT\x10\x04\x12\x15\n" +
	"\x11PROCESSES_REQUEST\x10\x05\x12\x16\n" +
	"\x12PROCESSES_RESPONSE\x10\x06\x12\x1c\n" +
	"\x18PROCESS_METADATA_REQUEST\x10\r\x12\x1d\n" +
	"\x19PROCESS_METADATA_RESPONSE\x10\x0e\x12\x19\n" +
	"\x15DEPLOY_PLUGIN_REQUEST\x10\a\x12\x1a\n" +
	"\x16DEPLOY_PLUGIN_RESPONSE\x10\b\x12\x1b\n" +
	"\x17EXECUTE_COMMAND_REQUEST\x10\t\x12\x1c\n" +
	"\x18EXECUTE_COMMAND_RESPONSE\x10\n" +
	"\x12\x13\n" +
	"\x0fNETWORK_REQUEST\x10\v\x12\x14\n" +
	"\x10NETWORK_RESPONSE\x10\f\x12\x17\n" +
	"\x13FS_LIST_DIR_REQUEST\x10\x14\x12\x18\n" +
	"\x14FS_LIST_DIR_RESPONSE\x10\x15\x12\x18\n" +
	"\x14FS_READ_FILE_REQUEST\x10\x16\x12\x19\n" +
	"\x15FS_READ_FILE_RESPONSE\x10\x17\x12\x19\n" +
	"\x15FS_WRITE_FILE_REQUEST\x10\x18\x12\x1a\n" +
	"\x16FS_WRITE_FILE_RESPONSE\x10\x19\x12\x1a\n" +
	"\x16FS_CREATE_FILE_REQUEST\x10\x1a\x12\x1b\n" +
	"\x17FS_CREATE_FILE_RESPONSE\x10\x1b\x12\x19\n" +
	"\x15FS_CREATE_DIR_REQUEST\x10\x1c\x12\x1a\n" +
	"\x16FS_CREATE_DIR_RESPONSE\x10\x1d\x12\x15\n" +
	"\x11FS_DELETE_REQUEST\x10\x1e\x12\x16\n" +
	"\x12FS_DELETE_RESPONSE\x10\x1f\x12\x15\n" +
	"\x11FS_RENAME_REQUEST\x10 \x12\x16\n" +
	"\x12FS_RENAME_RESPONSE\x10!\x12\x17\n" +
	"\x13FS_DOWNLOAD_REQUEST\x10\"\x12\x1d\n" +
	"\x19FS_ARCHIVE_CREATE_REQUEST\x10#\x12\x1e\n" +
	"\x1aFS_ARCHIVE_CREATE_RESPONSE\x10$\x12\x13\n" +
	"\x0fPROXY_ESTABLISH\x10(\x12\x18\n" +
	"\x14PROXY_DATA_TO_SERVER\x10)\x12\x18\n" +
	"\x14PROXY_DATA_TO_CLIENT\x10*\x12\x0f\n" +
	"\vPROXY_CLOSE\x10+\x12\x1b\n" +
	"\x17TERMINAL_CREATE_REQUEST\x10-\x12\x1c\n" +
	"\x18TERMINAL_CREATE_RESPONSE\x10.\x12\x12\n" +
	"\x0eTERMINAL_CLOSE\x10/\x12\x12\n" +
	"\x0eTERMINAL_ERROR\x100\x12\x16\n" +
	"\x12WEB_ROUTES_REQUEST\x102\x12\x17\n" +
	"\x13WEB_ROUTES_RESPONSE\x103\x12\x10\n" +
	"\fSCA_RESPONSE\x104\x12\x16\n" +
	"\x12IAST_NORMAL_REPORT\x105\x12\x14\n" +
	"\x10IAST_SAAS_REPORT\x106\x12\x18\n" +
	"\x14IAST_HARDCODE_REPORT\x107\x12\x10\n" +
	"\fFUZZ_REQUEST\x108\x12\x11\n" +
	"\rFUZZ_RESPONSE\x109\x12\x10\n" +
	"\fTRACE_REPORT\x10:\x12\x15\n" +
	"\x11HTTP_SEND_REQUEST\x10;\x12\x16\n" +
	"\x12HTTP_SEND_RESPONSE\x10<\x12\b\n" +
	"\x04PUSH\x10P\x12\b\n" +
	"\x04PULL\x10Q\x12\x15\n" +
	"\x11CONTAINER_REQUEST\x10d\x12\x16\n" +
	"\x12CONTAINER_RESPONSE\x10e\x12\x1c\n" +
	"\x18CONTAINER_ESCAPE_REQUEST\x10f\x12\x1d\n" +
	"\x19CONTAINER_ESCAPE_RESPONSE\x10g\x12 \n" +
	"\x1cPRIVILEGE_ESCALATION_REQUEST\x10h\x12!\n" +
	"\x1dPRIVILEGE_ESCALATION_RESPONSE\x10i\x12$\n" +
	" K8S_PRIVILEGE_ESCALATION_REQUEST\x10j\x12%\n" +
	"!K8S_PRIVILEGE_ESCALATION_RESPONSE\x10k\x12\x1b\n" +
	"\x17DATASOURCE_LIST_REQUEST\x10F\x12\x1c\n" +
	"\x18DATASOURCE_LIST_RESPONSE\x10G\x12\x1c\n" +
	"\x18DATABASE_CATALOG_REQUEST\x10H\x12\x1d\n" +
	"\x19DATABASE_CATALOG_RESPONSE\x10I\x12\x1c\n" +
	"\x18DATABASE_EXECUTE_REQUEST\x10J\x12\x1d\n" +
	"\x19DATABASE_EXECUTE_RESPONSE\x10K\x12\x14\n" +
	"\x10MCP_HTTP_REQUEST\x10l\x12\x15\n" +
	"\x11MCP_HTTP_RESPONSE\x10m\x12\x1a\n" +
	"\x16MCP_INITIALIZE_REQUEST\x10n\x12\x1b\n" +
	"\x17MCP_INITIALIZE_RESPONSE\x10o\x12\x17\n" +
	"\x13MCP_JSONRPC_REQUEST\x10p\x12\x18\n" +
	"\x14MCP_JSONRPC_RESPONSE\x10q\x12\r\n" +
	"\tMCP_EVENT\x10r\x12\x15\n" +
	"\x11MCP_SESSION_CLOSE\x10s\x12\x15\n" +
	"\x11TOOL_CALL_REQUEST\x10t\x12\x16\n" +
	"\x12TOOL_CALL_RESPONSE\x10u\x12\x13\n" +
	"\x0fTOOL_CALL_EVENT\x10v\x12\x0f\n" +
	"\vJVM_REQUEST\x10x\x12\x10\n" +
	"\fJVM_RESPONSE\x10y\x12\x12\n" +
	"\x0eTHREAD_REQUEST\x10z\x12\x13\n" +
	"\x0fTHREAD_RESPONSE\x10{\x12\x14\n" +
	"\x10SYS_PROP_REQUEST\x10|\x12\x15\n" +
	"\x11SYS_PROP_RESPONSE\x10}\x12\x13\n" +
	"\x0fSYS_ENV_REQUEST\x10~\x12\x14\n" +
	"\x10SYS_ENV_RESPONSE\x10\x7f\x12\x13\n" +
	"\x0eMEMORY_REQUEST\x10\x80\x01\x12\x14\n" +
	"\x0fMEMORY_RESPONSE\x10\x81\x01\x12\x16\n" +
	"\x11VM_OPTION_REQUEST\x10\x82\x01\x12\x17\n" +
	"\x12VM_OPTION_RESPONSE\x10\x83\x01\x12\x12\n" +
	"\rMBEAN_REQUEST\x10\x84\x01\x12\x13\n" +
	"\x0eMBEAN_RESPONSE\x10\x85\x01\x12\x18\n" +
	"\x13CLASSLOADER_REQUEST\x10\x86\x01\x12\x19\n" +
	"\x14CLASSLOADER_RESPONSE\x10\x87\x01\x12\x16\n" +
	"\x11DASHBOARD_REQUEST\x10\x88\x01\x12\x17\n" +
	"\x12DASHBOARD_RESPONSE\x10\x89\x01\x12\x14\n" +
	"\x0fVM_TOOL_REQUEST\x10\x8a\x01\x12\x15\n" +
	"\x10VM_TOOL_RESPONSE\x10\x8b\x01\x12\x19\n" +
	"\x14SEARCH_CLASS_REQUEST\x10\x8c\x01\x12\x1a\n" +
	"\x15SEARCH_CLASS_RESPONSE\x10\x8d\x01\x12\x1a\n" +
	"\x15SEARCH_METHOD_REQUEST\x10\x8e\x01\x12\x1b\n" +
	"\x16SEARCH_METHOD_RESPONSE\x10\x8f\x01\x12\x17\n" +
	"\x12GET_STATIC_REQUEST\x10\x90\x01\x12\x18\n" +
	"\x13GET_STATIC_RESPONSE\x10\x91\x01\x12\x11\n" +
	"\fOGNL_REQUEST\x10\x92\x01\x12\x12\n" +
	"\rOGNL_RESPONSE\x10\x93\x01\x12\x16\n" +
	"\x11HEAP_DUMP_REQUEST\x10\x94\x01\x12\x17\n" +
	"\x12HEAP_DUMP_RESPONSE\x10\x95\x01\x12\x10\n" +
	"\vJAD_REQUEST\x10\x96\x01\x12\x11\n" +
	"\fJAD_RESPONSE\x10\x97\x01\x12\x17\n" +
	"\x12DUMP_CLASS_REQUEST\x10\x98\x01\x12\x18\n" +
	"\x13DUMP_CLASS_RESPONSE\x10\x99\x01\x12\x1c\n" +
	"\x17MEMORY_COMPILER_REQUEST\x10\x9a\x01\x12\x1d\n" +
	"\x18MEMORY_COMPILER_RESPONSE\x10\x9b\x01\x12\x15\n" +
	"\x10REDEFINE_REQUEST\x10\x9c\x01\x12\x16\n" +
	"\x11REDEFINE_RESPONSE\x10\x9d\x01\x12\x18\n" +
	"\x13RETRANSFORM_REQUEST\x10\x9e\x01\x12\x19\n" +
	"\x14RETRANSFORM_RESPONSE\x10\x9f\x01\x12\x12\n" +
	"\rWATCH_REQUEST\x10\xa0\x01\x12\x13\n" +
	"\x0eWATCH_RESPONSE\x10\xa1\x01\x12\x10\n" +
	"\vWATCH_EVENT\x10\xa2\x01\x12\x12\n" +
	"\rTRACE_REQUEST\x10\xa3\x01\x12\x13\n" +
	"\x0eTRACE_RESPONSE\x10\xa4\x01\x12\x10\n" +
	"\vTRACE_EVENT\x10\xa5\x01\x12\x12\n" +
	"\rSTACK_REQUEST\x10\xa6\x01\x12\x13\n" +
	"\x0eSTACK_RESPONSE\x10\xa7\x01\x12\x10\n" +
	"\vSTACK_EVENT\x10\xa8\x01\x12\x14\n" +
	"\x0fMONITOR_REQUEST\x10\xa9\x01\x12\x15\n" +
	"\x10MONITOR_RESPONSE\x10\xaa\x01\x12\x12\n" +
	"\rMONITOR_EVENT\x10\xab\x01\x12\x18\n" +
	"\x13TIME_TUNNEL_REQUEST\x10\xac\x01\x12\x19\n" +
	"\x14TIME_TUNNEL_RESPONSE\x10\xad\x01\x12\x16\n" +
	"\x11TIME_TUNNEL_EVENT\x10\xae\x01\x12\x18\n" +
	"\x13TASK_CANCEL_REQUEST\x10\xaf\x01\x12\x19\n" +
	"\x14TASK_CANCEL_RESPONSE\x10\xb0\x01B)\n" +
	"\n" +
	"gaiasec.pbP\x01Z\x19gaiasec-nodeagent/pkg/pb/b\x06proto3"

var (
	file_message_type_proto_rawDescOnce sync.Once
	file_message_type_proto_rawDescData []byte
)

func file_message_type_proto_rawDescGZIP() []byte {
	file_message_type_proto_rawDescOnce.Do(func() {
		file_message_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_type_proto_rawDesc), len(file_message_type_proto_rawDesc)))
	})
	return file_message_type_proto_rawDescData
}

var file_message_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_message_type_proto_goTypes = []any{
	(MessageType)(0), // 0: MessageType
}
var file_message_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_type_proto_init() }
func file_message_type_proto_init() {
	if File_message_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_type_proto_rawDesc), len(file_message_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_type_proto_goTypes,
		DependencyIndexes: file_message_type_proto_depIdxs,
		EnumInfos:         file_message_type_proto_enumTypes,
	}.Build()
	File_message_type_proto = out.File
	file_message_type_proto_goTypes = nil
	file_message_type_proto_depIdxs = nil
}
