// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: message_type.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义消息类型枚举
type MessageType int32

const (
	MessageType_UNKNOWN                  MessageType = 0
	MessageType_REGISTER                 MessageType = 1
	MessageType_UNREGISTER               MessageType = 2
	MessageType_HEARTBEAT                MessageType = 3
	MessageType_INIT                     MessageType = 4
	MessageType_PROCESSES_REQUEST        MessageType = 5
	MessageType_PROCESSES_RESPONSE       MessageType = 6
	MessageType_DEPLOY_PLUGIN_REQUEST    MessageType = 7
	MessageType_DEPLOY_PLUGIN_RESPONSE   MessageType = 8
	MessageType_EXECUTE_COMMAND_REQUEST  MessageType = 9
	MessageType_EXECUTE_COMMAND_RESPONSE MessageType = 10
	MessageType_NETWORK_REQUEST          MessageType = 11
	MessageType_NETWORK_RESPONSE         MessageType = 12
	// 文件系统
	MessageType_FS_LIST_DIR_REQUEST     MessageType = 20
	MessageType_FS_LIST_DIR_RESPONSE    MessageType = 21
	MessageType_FS_READ_FILE_REQUEST    MessageType = 22
	MessageType_FS_READ_FILE_RESPONSE   MessageType = 23
	MessageType_FS_WRITE_FILE_REQUEST   MessageType = 24
	MessageType_FS_WRITE_FILE_RESPONSE  MessageType = 25
	MessageType_FS_CREATE_FILE_REQUEST  MessageType = 26
	MessageType_FS_CREATE_FILE_RESPONSE MessageType = 27
	MessageType_FS_CREATE_DIR_REQUEST   MessageType = 28
	MessageType_FS_CREATE_DIR_RESPONSE  MessageType = 29
	MessageType_FS_DELETE_REQUEST       MessageType = 30
	MessageType_FS_DELETE_RESPONSE      MessageType = 31
	MessageType_FS_RENAME_REQUEST       MessageType = 32
	MessageType_FS_RENAME_RESPONSE      MessageType = 33
	MessageType_FS_DOWNLOAD_REQUEST     MessageType = 34
	// 代理
	MessageType_PROXY_ESTABLISH      MessageType = 40 // establish
	MessageType_PROXY_DATA_TO_SERVER MessageType = 41 // data  nodeagent -> server
	MessageType_PROXY_DATA_TO_CLIENT MessageType = 42 // data  nodeagent -> client
	MessageType_PROXY_CLOSE          MessageType = 43 // finish
	// Terminal
	MessageType_TERMINAL_CREATE_REQUEST  MessageType = 45
	MessageType_TERMINAL_CREATE_RESPONSE MessageType = 46
	MessageType_TERMINAL_CLOSE           MessageType = 47
	MessageType_TERMINAL_ERROR           MessageType = 48
	// Java Agent
	MessageType_WEB_ROUTES_REQUEST   MessageType = 50
	MessageType_WEB_ROUTES_RESPONSE  MessageType = 51
	MessageType_SCA_RESPONSE         MessageType = 52
	MessageType_IAST_NORMAL_REPORT   MessageType = 53
	MessageType_IAST_SAAS_REPORT     MessageType = 54
	MessageType_IAST_HARDCODE_REPORT MessageType = 55
	MessageType_FUZZ_REQUEST         MessageType = 56
	MessageType_FUZZ_RESPONSE        MessageType = 57
	MessageType_TRACE_REPORT         MessageType = 58
	MessageType_PUSH                 MessageType = 80
	MessageType_PULL                 MessageType = 81
	// 容器信息
	MessageType_CONTAINER_REQUEST  MessageType = 100
	MessageType_CONTAINER_RESPONSE MessageType = 101
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:   "UNKNOWN",
		1:   "REGISTER",
		2:   "UNREGISTER",
		3:   "HEARTBEAT",
		4:   "INIT",
		5:   "PROCESSES_REQUEST",
		6:   "PROCESSES_RESPONSE",
		7:   "DEPLOY_PLUGIN_REQUEST",
		8:   "DEPLOY_PLUGIN_RESPONSE",
		9:   "EXECUTE_COMMAND_REQUEST",
		10:  "EXECUTE_COMMAND_RESPONSE",
		11:  "NETWORK_REQUEST",
		12:  "NETWORK_RESPONSE",
		20:  "FS_LIST_DIR_REQUEST",
		21:  "FS_LIST_DIR_RESPONSE",
		22:  "FS_READ_FILE_REQUEST",
		23:  "FS_READ_FILE_RESPONSE",
		24:  "FS_WRITE_FILE_REQUEST",
		25:  "FS_WRITE_FILE_RESPONSE",
		26:  "FS_CREATE_FILE_REQUEST",
		27:  "FS_CREATE_FILE_RESPONSE",
		28:  "FS_CREATE_DIR_REQUEST",
		29:  "FS_CREATE_DIR_RESPONSE",
		30:  "FS_DELETE_REQUEST",
		31:  "FS_DELETE_RESPONSE",
		32:  "FS_RENAME_REQUEST",
		33:  "FS_RENAME_RESPONSE",
		34:  "FS_DOWNLOAD_REQUEST",
		40:  "PROXY_ESTABLISH",
		41:  "PROXY_DATA_TO_SERVER",
		42:  "PROXY_DATA_TO_CLIENT",
		43:  "PROXY_CLOSE",
		45:  "TERMINAL_CREATE_REQUEST",
		46:  "TERMINAL_CREATE_RESPONSE",
		47:  "TERMINAL_CLOSE",
		48:  "TERMINAL_ERROR",
		50:  "WEB_ROUTES_REQUEST",
		51:  "WEB_ROUTES_RESPONSE",
		52:  "SCA_RESPONSE",
		53:  "IAST_NORMAL_REPORT",
		54:  "IAST_SAAS_REPORT",
		55:  "IAST_HARDCODE_REPORT",
		56:  "FUZZ_REQUEST",
		57:  "FUZZ_RESPONSE",
		58:  "TRACE_REPORT",
		80:  "PUSH",
		81:  "PULL",
		100: "CONTAINER_REQUEST",
		101: "CONTAINER_RESPONSE",
	}
	MessageType_value = map[string]int32{
		"UNKNOWN":                  0,
		"REGISTER":                 1,
		"UNREGISTER":               2,
		"HEARTBEAT":                3,
		"INIT":                     4,
		"PROCESSES_REQUEST":        5,
		"PROCESSES_RESPONSE":       6,
		"DEPLOY_PLUGIN_REQUEST":    7,
		"DEPLOY_PLUGIN_RESPONSE":   8,
		"EXECUTE_COMMAND_REQUEST":  9,
		"EXECUTE_COMMAND_RESPONSE": 10,
		"NETWORK_REQUEST":          11,
		"NETWORK_RESPONSE":         12,
		"FS_LIST_DIR_REQUEST":      20,
		"FS_LIST_DIR_RESPONSE":     21,
		"FS_READ_FILE_REQUEST":     22,
		"FS_READ_FILE_RESPONSE":    23,
		"FS_WRITE_FILE_REQUEST":    24,
		"FS_WRITE_FILE_RESPONSE":   25,
		"FS_CREATE_FILE_REQUEST":   26,
		"FS_CREATE_FILE_RESPONSE":  27,
		"FS_CREATE_DIR_REQUEST":    28,
		"FS_CREATE_DIR_RESPONSE":   29,
		"FS_DELETE_REQUEST":        30,
		"FS_DELETE_RESPONSE":       31,
		"FS_RENAME_REQUEST":        32,
		"FS_RENAME_RESPONSE":       33,
		"FS_DOWNLOAD_REQUEST":      34,
		"PROXY_ESTABLISH":          40,
		"PROXY_DATA_TO_SERVER":     41,
		"PROXY_DATA_TO_CLIENT":     42,
		"PROXY_CLOSE":              43,
		"TERMINAL_CREATE_REQUEST":  45,
		"TERMINAL_CREATE_RESPONSE": 46,
		"TERMINAL_CLOSE":           47,
		"TERMINAL_ERROR":           48,
		"WEB_ROUTES_REQUEST":       50,
		"WEB_ROUTES_RESPONSE":      51,
		"SCA_RESPONSE":             52,
		"IAST_NORMAL_REPORT":       53,
		"IAST_SAAS_REPORT":         54,
		"IAST_HARDCODE_REPORT":     55,
		"FUZZ_REQUEST":             56,
		"FUZZ_RESPONSE":            57,
		"TRACE_REPORT":             58,
		"PUSH":                     80,
		"PULL":                     81,
		"CONTAINER_REQUEST":        100,
		"CONTAINER_RESPONSE":       101,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_type_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_message_type_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_message_type_proto_rawDescGZIP(), []int{0}
}

var File_message_type_proto protoreflect.FileDescriptor

const file_message_type_proto_rawDesc = "" +
	"\n" +
	"\x12message_type.proto*\xe5\b\n" +
	"\vMessageType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bREGISTER\x10\x01\x12\x0e\n" +
	"\n" +
	"UNREGISTER\x10\x02\x12\r\n" +
	"\tHEARTBEAT\x10\x03\x12\b\n" +
	"\x04INIT\x10\x04\x12\x15\n" +
	"\x11PROCESSES_REQUEST\x10\x05\x12\x16\n" +
	"\x12PROCESSES_RESPONSE\x10\x06\x12\x19\n" +
	"\x15DEPLOY_PLUGIN_REQUEST\x10\a\x12\x1a\n" +
	"\x16DEPLOY_PLUGIN_RESPONSE\x10\b\x12\x1b\n" +
	"\x17EXECUTE_COMMAND_REQUEST\x10\t\x12\x1c\n" +
	"\x18EXECUTE_COMMAND_RESPONSE\x10\n" +
	"\x12\x13\n" +
	"\x0fNETWORK_REQUEST\x10\v\x12\x14\n" +
	"\x10NETWORK_RESPONSE\x10\f\x12\x17\n" +
	"\x13FS_LIST_DIR_REQUEST\x10\x14\x12\x18\n" +
	"\x14FS_LIST_DIR_RESPONSE\x10\x15\x12\x18\n" +
	"\x14FS_READ_FILE_REQUEST\x10\x16\x12\x19\n" +
	"\x15FS_READ_FILE_RESPONSE\x10\x17\x12\x19\n" +
	"\x15FS_WRITE_FILE_REQUEST\x10\x18\x12\x1a\n" +
	"\x16FS_WRITE_FILE_RESPONSE\x10\x19\x12\x1a\n" +
	"\x16FS_CREATE_FILE_REQUEST\x10\x1a\x12\x1b\n" +
	"\x17FS_CREATE_FILE_RESPONSE\x10\x1b\x12\x19\n" +
	"\x15FS_CREATE_DIR_REQUEST\x10\x1c\x12\x1a\n" +
	"\x16FS_CREATE_DIR_RESPONSE\x10\x1d\x12\x15\n" +
	"\x11FS_DELETE_REQUEST\x10\x1e\x12\x16\n" +
	"\x12FS_DELETE_RESPONSE\x10\x1f\x12\x15\n" +
	"\x11FS_RENAME_REQUEST\x10 \x12\x16\n" +
	"\x12FS_RENAME_RESPONSE\x10!\x12\x17\n" +
	"\x13FS_DOWNLOAD_REQUEST\x10\"\x12\x13\n" +
	"\x0fPROXY_ESTABLISH\x10(\x12\x18\n" +
	"\x14PROXY_DATA_TO_SERVER\x10)\x12\x18\n" +
	"\x14PROXY_DATA_TO_CLIENT\x10*\x12\x0f\n" +
	"\vPROXY_CLOSE\x10+\x12\x1b\n" +
	"\x17TERMINAL_CREATE_REQUEST\x10-\x12\x1c\n" +
	"\x18TERMINAL_CREATE_RESPONSE\x10.\x12\x12\n" +
	"\x0eTERMINAL_CLOSE\x10/\x12\x12\n" +
	"\x0eTERMINAL_ERROR\x100\x12\x16\n" +
	"\x12WEB_ROUTES_REQUEST\x102\x12\x17\n" +
	"\x13WEB_ROUTES_RESPONSE\x103\x12\x10\n" +
	"\fSCA_RESPONSE\x104\x12\x16\n" +
	"\x12IAST_NORMAL_REPORT\x105\x12\x14\n" +
	"\x10IAST_SAAS_REPORT\x106\x12\x18\n" +
	"\x14IAST_HARDCODE_REPORT\x107\x12\x10\n" +
	"\fFUZZ_REQUEST\x108\x12\x11\n" +
	"\rFUZZ_RESPONSE\x109\x12\x10\n" +
	"\fTRACE_REPORT\x10:\x12\b\n" +
	"\x04PUSH\x10P\x12\b\n" +
	"\x04PULL\x10Q\x12\x15\n" +
	"\x11CONTAINER_REQUEST\x10d\x12\x16\n" +
	"\x12CONTAINER_RESPONSE\x10eB)\n" +
	"\n" +
	"gaiasec.pbP\x01Z\x19gaiasec-nodeagent/pkg/pb/b\x06proto3"

var (
	file_message_type_proto_rawDescOnce sync.Once
	file_message_type_proto_rawDescData []byte
)

func file_message_type_proto_rawDescGZIP() []byte {
	file_message_type_proto_rawDescOnce.Do(func() {
		file_message_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_type_proto_rawDesc), len(file_message_type_proto_rawDesc)))
	})
	return file_message_type_proto_rawDescData
}

var file_message_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_message_type_proto_goTypes = []any{
	(MessageType)(0), // 0: MessageType
}
var file_message_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_type_proto_init() }
func file_message_type_proto_init() {
	if File_message_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_type_proto_rawDesc), len(file_message_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_type_proto_goTypes,
		DependencyIndexes: file_message_type_proto_depIdxs,
		EnumInfos:         file_message_type_proto_enumTypes,
	}.Build()
	File_message_type_proto = out.File
	file_message_type_proto_goTypes = nil
	file_message_type_proto_depIdxs = nil
}
