// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: message_type.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义消息类型枚举
type MessageType int32

const (
	MessageType_UNKNOWN                MessageType = 0
	MessageType_REGISTER               MessageType = 1
	MessageType_UNREGISTER             MessageType = 2
	MessageType_HEARTBEAT              MessageType = 3
	MessageType_INIT                   MessageType = 4
	MessageType_PROCESSES_REQUEST      MessageType = 5
	MessageType_PROCESSES_RESPONSE     MessageType = 6
	MessageType_DEPLOY_PLUGIN_REQUEST  MessageType = 7
	MessageType_DEPLOY_PLUGIN_RESPONSE MessageType = 8
	// 文件系统
	MessageType_FS_LIST_DIR_REQUEST     MessageType = 20
	MessageType_FS_LIST_DIR_RESPONSE    MessageType = 21
	MessageType_FS_READ_FILE_REQUEST    MessageType = 22
	MessageType_FS_READ_FILE_RESPONSE   MessageType = 23
	MessageType_FS_WRITE_FILE_REQUEST   MessageType = 24
	MessageType_FS_WRITE_FILE_RESPONSE  MessageType = 25
	MessageType_FS_CREATE_FILE_REQUEST  MessageType = 26
	MessageType_FS_CREATE_FILE_RESPONSE MessageType = 27
	MessageType_FS_CREATE_DIR_REQUEST   MessageType = 28
	MessageType_FS_CREATE_DIR_RESPONSE  MessageType = 29
	MessageType_FS_DELETE_REQUEST       MessageType = 30
	MessageType_FS_DELETE_RESPONSE      MessageType = 31
	MessageType_FS_RENAME_REQUEST       MessageType = 32
	MessageType_FS_RENAME_RESPONSE      MessageType = 33
	// Java Agent
	MessageType_WEB_ROUTES_REQUEST  MessageType = 50
	MessageType_WEB_ROUTES_RESPONSE MessageType = 51
	MessageType_PUSH                MessageType = 80
	MessageType_PULL                MessageType = 81
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "REGISTER",
		2:  "UNREGISTER",
		3:  "HEARTBEAT",
		4:  "INIT",
		5:  "PROCESSES_REQUEST",
		6:  "PROCESSES_RESPONSE",
		7:  "DEPLOY_PLUGIN_REQUEST",
		8:  "DEPLOY_PLUGIN_RESPONSE",
		20: "FS_LIST_DIR_REQUEST",
		21: "FS_LIST_DIR_RESPONSE",
		22: "FS_READ_FILE_REQUEST",
		23: "FS_READ_FILE_RESPONSE",
		24: "FS_WRITE_FILE_REQUEST",
		25: "FS_WRITE_FILE_RESPONSE",
		26: "FS_CREATE_FILE_REQUEST",
		27: "FS_CREATE_FILE_RESPONSE",
		28: "FS_CREATE_DIR_REQUEST",
		29: "FS_CREATE_DIR_RESPONSE",
		30: "FS_DELETE_REQUEST",
		31: "FS_DELETE_RESPONSE",
		32: "FS_RENAME_REQUEST",
		33: "FS_RENAME_RESPONSE",
		50: "WEB_ROUTES_REQUEST",
		51: "WEB_ROUTES_RESPONSE",
		80: "PUSH",
		81: "PULL",
	}
	MessageType_value = map[string]int32{
		"UNKNOWN":                 0,
		"REGISTER":                1,
		"UNREGISTER":              2,
		"HEARTBEAT":               3,
		"INIT":                    4,
		"PROCESSES_REQUEST":       5,
		"PROCESSES_RESPONSE":      6,
		"DEPLOY_PLUGIN_REQUEST":   7,
		"DEPLOY_PLUGIN_RESPONSE":  8,
		"FS_LIST_DIR_REQUEST":     20,
		"FS_LIST_DIR_RESPONSE":    21,
		"FS_READ_FILE_REQUEST":    22,
		"FS_READ_FILE_RESPONSE":   23,
		"FS_WRITE_FILE_REQUEST":   24,
		"FS_WRITE_FILE_RESPONSE":  25,
		"FS_CREATE_FILE_REQUEST":  26,
		"FS_CREATE_FILE_RESPONSE": 27,
		"FS_CREATE_DIR_REQUEST":   28,
		"FS_CREATE_DIR_RESPONSE":  29,
		"FS_DELETE_REQUEST":       30,
		"FS_DELETE_RESPONSE":      31,
		"FS_RENAME_REQUEST":       32,
		"FS_RENAME_RESPONSE":      33,
		"WEB_ROUTES_REQUEST":      50,
		"WEB_ROUTES_RESPONSE":     51,
		"PUSH":                    80,
		"PULL":                    81,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_type_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_message_type_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_message_type_proto_rawDescGZIP(), []int{0}
}

var File_message_type_proto protoreflect.FileDescriptor

const file_message_type_proto_rawDesc = "" +
	"\n" +
	"\x12message_type.proto*\xe9\x04\n" +
	"\vMessageType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bREGISTER\x10\x01\x12\x0e\n" +
	"\n" +
	"UNREGISTER\x10\x02\x12\r\n" +
	"\tHEARTBEAT\x10\x03\x12\b\n" +
	"\x04INIT\x10\x04\x12\x15\n" +
	"\x11PROCESSES_REQUEST\x10\x05\x12\x16\n" +
	"\x12PROCESSES_RESPONSE\x10\x06\x12\x19\n" +
	"\x15DEPLOY_PLUGIN_REQUEST\x10\a\x12\x1a\n" +
	"\x16DEPLOY_PLUGIN_RESPONSE\x10\b\x12\x17\n" +
	"\x13FS_LIST_DIR_REQUEST\x10\x14\x12\x18\n" +
	"\x14FS_LIST_DIR_RESPONSE\x10\x15\x12\x18\n" +
	"\x14FS_READ_FILE_REQUEST\x10\x16\x12\x19\n" +
	"\x15FS_READ_FILE_RESPONSE\x10\x17\x12\x19\n" +
	"\x15FS_WRITE_FILE_REQUEST\x10\x18\x12\x1a\n" +
	"\x16FS_WRITE_FILE_RESPONSE\x10\x19\x12\x1a\n" +
	"\x16FS_CREATE_FILE_REQUEST\x10\x1a\x12\x1b\n" +
	"\x17FS_CREATE_FILE_RESPONSE\x10\x1b\x12\x19\n" +
	"\x15FS_CREATE_DIR_REQUEST\x10\x1c\x12\x1a\n" +
	"\x16FS_CREATE_DIR_RESPONSE\x10\x1d\x12\x15\n" +
	"\x11FS_DELETE_REQUEST\x10\x1e\x12\x16\n" +
	"\x12FS_DELETE_RESPONSE\x10\x1f\x12\x15\n" +
	"\x11FS_RENAME_REQUEST\x10 \x12\x16\n" +
	"\x12FS_RENAME_RESPONSE\x10!\x12\x16\n" +
	"\x12WEB_ROUTES_REQUEST\x102\x12\x17\n" +
	"\x13WEB_ROUTES_RESPONSE\x103\x12\b\n" +
	"\x04PUSH\x10P\x12\b\n" +
	"\x04PULL\x10QB)\n" +
	"\n" +
	"sothoth.pbP\x01Z\x19sothoth-nodeagent/pkg/pb/b\x06proto3"

var (
	file_message_type_proto_rawDescOnce sync.Once
	file_message_type_proto_rawDescData []byte
)

func file_message_type_proto_rawDescGZIP() []byte {
	file_message_type_proto_rawDescOnce.Do(func() {
		file_message_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_type_proto_rawDesc), len(file_message_type_proto_rawDesc)))
	})
	return file_message_type_proto_rawDescData
}

var file_message_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_message_type_proto_goTypes = []any{
	(MessageType)(0), // 0: MessageType
}
var file_message_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_type_proto_init() }
func file_message_type_proto_init() {
	if File_message_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_type_proto_rawDesc), len(file_message_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_type_proto_goTypes,
		DependencyIndexes: file_message_type_proto_depIdxs,
		EnumInfos:         file_message_type_proto_enumTypes,
	}.Build()
	File_message_type_proto = out.File
	file_message_type_proto_goTypes = nil
	file_message_type_proto_depIdxs = nil
}
