// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: node_deploy_plugin_request.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 节点部署插件请求
type NodeDeployPluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	PluginName    string                 `protobuf:"bytes,3,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	PluginVersion string                 `protobuf:"bytes,4,opt,name=plugin_version,json=pluginVersion,proto3" json:"plugin_version,omitempty"`
	Pid           int32                  `protobuf:"varint,5,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeDeployPluginRequest) Reset() {
	*x = NodeDeployPluginRequest{}
	mi := &file_node_deploy_plugin_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeDeployPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeDeployPluginRequest) ProtoMessage() {}

func (x *NodeDeployPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_deploy_plugin_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeDeployPluginRequest.ProtoReflect.Descriptor instead.
func (*NodeDeployPluginRequest) Descriptor() ([]byte, []int) {
	return file_node_deploy_plugin_request_proto_rawDescGZIP(), []int{0}
}

func (x *NodeDeployPluginRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *NodeDeployPluginRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *NodeDeployPluginRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *NodeDeployPluginRequest) GetPluginVersion() string {
	if x != nil {
		return x.PluginVersion
	}
	return ""
}

func (x *NodeDeployPluginRequest) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

var File_node_deploy_plugin_request_proto protoreflect.FileDescriptor

const file_node_deploy_plugin_request_proto_rawDesc = "" +
	"\n" +
	" node_deploy_plugin_request.proto\"\xa7\x01\n" +
	"\x17NodeDeployPluginRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1f\n" +
	"\vplugin_name\x18\x03 \x01(\tR\n" +
	"pluginName\x12%\n" +
	"\x0eplugin_version\x18\x04 \x01(\tR\rpluginVersion\x12\x10\n" +
	"\x03pid\x18\x05 \x01(\x05R\x03pidB)\n" +
	"\n" +
	"sothoth.pbP\x01Z\x19sothoth-nodeagent/pkg/pb/b\x06proto3"

var (
	file_node_deploy_plugin_request_proto_rawDescOnce sync.Once
	file_node_deploy_plugin_request_proto_rawDescData []byte
)

func file_node_deploy_plugin_request_proto_rawDescGZIP() []byte {
	file_node_deploy_plugin_request_proto_rawDescOnce.Do(func() {
		file_node_deploy_plugin_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_deploy_plugin_request_proto_rawDesc), len(file_node_deploy_plugin_request_proto_rawDesc)))
	})
	return file_node_deploy_plugin_request_proto_rawDescData
}

var file_node_deploy_plugin_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_node_deploy_plugin_request_proto_goTypes = []any{
	(*NodeDeployPluginRequest)(nil), // 0: NodeDeployPluginRequest
}
var file_node_deploy_plugin_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_node_deploy_plugin_request_proto_init() }
func file_node_deploy_plugin_request_proto_init() {
	if File_node_deploy_plugin_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_deploy_plugin_request_proto_rawDesc), len(file_node_deploy_plugin_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_node_deploy_plugin_request_proto_goTypes,
		DependencyIndexes: file_node_deploy_plugin_request_proto_depIdxs,
		MessageInfos:      file_node_deploy_plugin_request_proto_msgTypes,
	}.Build()
	File_node_deploy_plugin_request_proto = out.File
	file_node_deploy_plugin_request_proto_goTypes = nil
	file_node_deploy_plugin_request_proto_depIdxs = nil
}
