// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: node_logout.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 节点登出消息
type NodeLogout struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeLogout) Reset() {
	*x = NodeLogout{}
	mi := &file_node_logout_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeLogout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeLogout) ProtoMessage() {}

func (x *NodeLogout) ProtoReflect() protoreflect.Message {
	mi := &file_node_logout_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeLogout.ProtoReflect.Descriptor instead.
func (*NodeLogout) Descriptor() ([]byte, []int) {
	return file_node_logout_proto_rawDescGZIP(), []int{0}
}

func (x *NodeLogout) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *NodeLogout) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

var File_node_logout_proto protoreflect.FileDescriptor

const file_node_logout_proto_rawDesc = "" +
	"\n" +
	"\x11node_logout.proto\"D\n" +
	"\n" +
	"NodeLogout\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeIdB)\n" +
	"\n" +
	"sothoth.pbP\x01Z\x19sothoth-nodeagent/pkg/pb/b\x06proto3"

var (
	file_node_logout_proto_rawDescOnce sync.Once
	file_node_logout_proto_rawDescData []byte
)

func file_node_logout_proto_rawDescGZIP() []byte {
	file_node_logout_proto_rawDescOnce.Do(func() {
		file_node_logout_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_logout_proto_rawDesc), len(file_node_logout_proto_rawDesc)))
	})
	return file_node_logout_proto_rawDescData
}

var file_node_logout_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_node_logout_proto_goTypes = []any{
	(*NodeLogout)(nil), // 0: NodeLogout
}
var file_node_logout_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_node_logout_proto_init() }
func file_node_logout_proto_init() {
	if File_node_logout_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_logout_proto_rawDesc), len(file_node_logout_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_node_logout_proto_goTypes,
		DependencyIndexes: file_node_logout_proto_depIdxs,
		MessageInfos:      file_node_logout_proto_msgTypes,
	}.Build()
	File_node_logout_proto = out.File
	file_node_logout_proto_goTypes = nil
	file_node_logout_proto_depIdxs = nil
}
