// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: node_login.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 节点登录消息
type NodeLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Ip            string                 `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	Os            string                 `protobuf:"bytes,5,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,6,opt,name=arch,proto3" json:"arch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeLogin) Reset() {
	*x = NodeLogin{}
	mi := &file_node_login_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeLogin) ProtoMessage() {}

func (x *NodeLogin) ProtoReflect() protoreflect.Message {
	mi := &file_node_login_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeLogin.ProtoReflect.Descriptor instead.
func (*NodeLogin) Descriptor() ([]byte, []int) {
	return file_node_login_proto_rawDescGZIP(), []int{0}
}

func (x *NodeLogin) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *NodeLogin) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeLogin) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *NodeLogin) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *NodeLogin) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *NodeLogin) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

var File_node_login_proto protoreflect.FileDescriptor

const file_node_login_proto_rawDesc = "" +
	"\n" +
	"\x10node_login.proto\"\x93\x01\n" +
	"\tNodeLogin\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\x12\x0e\n" +
	"\x02os\x18\x05 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x06 \x01(\tR\x04archB)\n" +
	"\n" +
	"sothoth.pbP\x01Z\x19sothoth-nodeagent/pkg/pb/b\x06proto3"

var (
	file_node_login_proto_rawDescOnce sync.Once
	file_node_login_proto_rawDescData []byte
)

func file_node_login_proto_rawDescGZIP() []byte {
	file_node_login_proto_rawDescOnce.Do(func() {
		file_node_login_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_login_proto_rawDesc), len(file_node_login_proto_rawDesc)))
	})
	return file_node_login_proto_rawDescData
}

var file_node_login_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_node_login_proto_goTypes = []any{
	(*NodeLogin)(nil), // 0: NodeLogin
}
var file_node_login_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_node_login_proto_init() }
func file_node_login_proto_init() {
	if File_node_login_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_login_proto_rawDesc), len(file_node_login_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_node_login_proto_goTypes,
		DependencyIndexes: file_node_login_proto_depIdxs,
		MessageInfos:      file_node_login_proto_msgTypes,
	}.Build()
	File_node_login_proto = out.File
	file_node_login_proto_goTypes = nil
	file_node_login_proto_depIdxs = nil
}
