// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proxy.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PROXY_DATA_TYPE int32

const (
	PROXY_DATA_TYPE_DATA            PROXY_DATA_TYPE = 0
	PROXY_DATA_TYPE_ESTABLISH_OK    PROXY_DATA_TYPE = 1
	PROXY_DATA_TYPE_ESTABLISH_ERROR PROXY_DATA_TYPE = 2
	PROXY_DATA_TYPE_NO_MORE         PROXY_DATA_TYPE = 3
)

// Enum value maps for PROXY_DATA_TYPE.
var (
	PROXY_DATA_TYPE_name = map[int32]string{
		0: "DATA",
		1: "ESTABLISH_OK",
		2: "ESTABLISH_ERROR",
		3: "NO_MORE",
	}
	PROXY_DATA_TYPE_value = map[string]int32{
		"DATA":            0,
		"ESTABLISH_OK":    1,
		"ESTABLISH_ERROR": 2,
		"NO_MORE":         3,
	}
)

func (x PROXY_DATA_TYPE) Enum() *PROXY_DATA_TYPE {
	p := new(PROXY_DATA_TYPE)
	*p = x
	return p
}

func (x PROXY_DATA_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PROXY_DATA_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_proxy_proto_enumTypes[0].Descriptor()
}

func (PROXY_DATA_TYPE) Type() protoreflect.EnumType {
	return &file_proxy_proto_enumTypes[0]
}

func (x PROXY_DATA_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PROXY_DATA_TYPE.Descriptor instead.
func (PROXY_DATA_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{0}
}

type ProxyEstablishMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyEstablishMessage) Reset() {
	*x = ProxyEstablishMessage{}
	mi := &file_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyEstablishMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyEstablishMessage) ProtoMessage() {}

func (x *ProxyEstablishMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyEstablishMessage.ProtoReflect.Descriptor instead.
func (*ProxyEstablishMessage) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *ProxyEstablishMessage) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type ProxyData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProxyDataType PROXY_DATA_TYPE        `protobuf:"varint,1,opt,name=proxy_data_type,json=proxyDataType,proto3,enum=PROXY_DATA_TYPE" json:"proxy_data_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyData) Reset() {
	*x = ProxyData{}
	mi := &file_proxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyData) ProtoMessage() {}

func (x *ProxyData) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyData.ProtoReflect.Descriptor instead.
func (*ProxyData) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *ProxyData) GetProxyDataType() PROXY_DATA_TYPE {
	if x != nil {
		return x.ProxyDataType
	}
	return PROXY_DATA_TYPE_DATA
}

func (x *ProxyData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proxy_proto protoreflect.FileDescriptor

const file_proxy_proto_rawDesc = "" +
	"\n" +
	"\vproxy.proto\"+\n" +
	"\x15ProxyEstablishMessage\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\"Y\n" +
	"\tProxyData\x128\n" +
	"\x0fproxy_data_type\x18\x01 \x01(\x0e2\x10.PROXY_DATA_TYPER\rproxyDataType\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data*O\n" +
	"\x0fPROXY_DATA_TYPE\x12\b\n" +
	"\x04DATA\x10\x00\x12\x10\n" +
	"\fESTABLISH_OK\x10\x01\x12\x13\n" +
	"\x0fESTABLISH_ERROR\x10\x02\x12\v\n" +
	"\aNO_MORE\x10\x03B)\n" +
	"\n" +
	"gaiasec.pbP\x01Z\x19gaiasec-nodeagent/pkg/pb/b\x06proto3"

var (
	file_proxy_proto_rawDescOnce sync.Once
	file_proxy_proto_rawDescData []byte
)

func file_proxy_proto_rawDescGZIP() []byte {
	file_proxy_proto_rawDescOnce.Do(func() {
		file_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_proto_rawDesc), len(file_proxy_proto_rawDesc)))
	})
	return file_proxy_proto_rawDescData
}

var file_proxy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proxy_proto_goTypes = []any{
	(PROXY_DATA_TYPE)(0),          // 0: PROXY_DATA_TYPE
	(*ProxyEstablishMessage)(nil), // 1: ProxyEstablishMessage
	(*ProxyData)(nil),             // 2: ProxyData
}
var file_proxy_proto_depIdxs = []int32{
	0, // 0: ProxyData.proxy_data_type:type_name -> PROXY_DATA_TYPE
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proxy_proto_init() }
func file_proxy_proto_init() {
	if File_proxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_proto_rawDesc), len(file_proxy_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_proto_goTypes,
		DependencyIndexes: file_proxy_proto_depIdxs,
		EnumInfos:         file_proxy_proto_enumTypes,
		MessageInfos:      file_proxy_proto_msgTypes,
	}.Build()
	File_proxy_proto = out.File
	file_proxy_proto_goTypes = nil
	file_proxy_proto_depIdxs = nil
}
