// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: register.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentType int32

const (
	AgentType_NODE_AGENT AgentType = 0
	AgentType_JAVA_AGENT AgentType = 1
)

// Enum value maps for AgentType.
var (
	AgentType_name = map[int32]string{
		0: "NODE_AGENT",
		1: "JAVA_AGENT",
	}
	AgentType_value = map[string]int32{
		"NODE_AGENT": 0,
		"JAVA_AGENT": 1,
	}
)

func (x AgentType) Enum() *AgentType {
	p := new(AgentType)
	*p = x
	return p
}

func (x AgentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentType) Descriptor() protoreflect.EnumDescriptor {
	return file_register_proto_enumTypes[0].Descriptor()
}

func (AgentType) Type() protoreflect.EnumType {
	return &file_register_proto_enumTypes[0]
}

func (x AgentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentType.Descriptor instead.
func (AgentType) EnumDescriptor() ([]byte, []int) {
	return file_register_proto_rawDescGZIP(), []int{0}
}

// Agent注册消息
type Register struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ParentId      string                 `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	AgentType     AgentType              `protobuf:"varint,4,opt,name=agent_type,json=agentType,proto3,enum=AgentType" json:"agent_type,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,5,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Hostname      string                 `protobuf:"bytes,6,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Ips           []string               `protobuf:"bytes,7,rep,name=ips,proto3" json:"ips,omitempty"`
	Os            string                 `protobuf:"bytes,8,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,9,opt,name=arch,proto3" json:"arch,omitempty"`
	Pid           int32                  `protobuf:"varint,10,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Register) Reset() {
	*x = Register{}
	mi := &file_register_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_register_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_register_proto_rawDescGZIP(), []int{0}
}

func (x *Register) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Register) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Register) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Register) GetAgentType() AgentType {
	if x != nil {
		return x.AgentType
	}
	return AgentType_NODE_AGENT
}

func (x *Register) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Register) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Register) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *Register) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Register) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *Register) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

// Agent注销消息
type Unregister struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unregister) Reset() {
	*x = Unregister{}
	mi := &file_register_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unregister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unregister) ProtoMessage() {}

func (x *Unregister) ProtoReflect() protoreflect.Message {
	mi := &file_register_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unregister.ProtoReflect.Descriptor instead.
func (*Unregister) Descriptor() ([]byte, []int) {
	return file_register_proto_rawDescGZIP(), []int{1}
}

func (x *Unregister) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_register_proto protoreflect.FileDescriptor

const file_register_proto_rawDesc = "" +
	"\n" +
	"\x0eregister.proto\"\x8a\x02\n" +
	"\bRegister\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\tR\bparentId\x12)\n" +
	"\n" +
	"agent_type\x18\x04 \x01(\x0e2\n" +
	".AgentTypeR\tagentType\x12#\n" +
	"\ragent_version\x18\x05 \x01(\tR\fagentVersion\x12\x1a\n" +
	"\bhostname\x18\x06 \x01(\tR\bhostname\x12\x10\n" +
	"\x03ips\x18\a \x03(\tR\x03ips\x12\x0e\n" +
	"\x02os\x18\b \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\t \x01(\tR\x04arch\x12\x10\n" +
	"\x03pid\x18\n" +
	" \x01(\x05R\x03pid\"\x1c\n" +
	"\n" +
	"Unregister\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id*+\n" +
	"\tAgentType\x12\x0e\n" +
	"\n" +
	"NODE_AGENT\x10\x00\x12\x0e\n" +
	"\n" +
	"JAVA_AGENT\x10\x01B)\n" +
	"\n" +
	"sothoth.pbP\x01Z\x19sothoth-nodeagent/pkg/pb/b\x06proto3"

var (
	file_register_proto_rawDescOnce sync.Once
	file_register_proto_rawDescData []byte
)

func file_register_proto_rawDescGZIP() []byte {
	file_register_proto_rawDescOnce.Do(func() {
		file_register_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_register_proto_rawDesc), len(file_register_proto_rawDesc)))
	})
	return file_register_proto_rawDescData
}

var file_register_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_register_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_register_proto_goTypes = []any{
	(AgentType)(0),     // 0: AgentType
	(*Register)(nil),   // 1: Register
	(*Unregister)(nil), // 2: Unregister
}
var file_register_proto_depIdxs = []int32{
	0, // 0: Register.agent_type:type_name -> AgentType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_register_proto_init() }
func file_register_proto_init() {
	if File_register_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_register_proto_rawDesc), len(file_register_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_register_proto_goTypes,
		DependencyIndexes: file_register_proto_depIdxs,
		EnumInfos:         file_register_proto_enumTypes,
		MessageInfos:      file_register_proto_msgTypes,
	}.Build()
	File_register_proto = out.File
	file_register_proto_goTypes = nil
	file_register_proto_depIdxs = nil
}
