// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: terminal.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TerminalCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Cols          int32                  `protobuf:"varint,3,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          int32                  `protobuf:"varint,4,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalCreateRequest) Reset() {
	*x = TerminalCreateRequest{}
	mi := &file_terminal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalCreateRequest) ProtoMessage() {}

func (x *TerminalCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalCreateRequest.ProtoReflect.Descriptor instead.
func (*TerminalCreateRequest) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{0}
}

func (x *TerminalCreateRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *TerminalCreateRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *TerminalCreateRequest) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *TerminalCreateRequest) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type TerminalCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalCreateResponse) Reset() {
	*x = TerminalCreateResponse{}
	mi := &file_terminal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalCreateResponse) ProtoMessage() {}

func (x *TerminalCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalCreateResponse.ProtoReflect.Descriptor instead.
func (*TerminalCreateResponse) Descriptor() ([]byte, []int) {
	return file_terminal_proto_rawDescGZIP(), []int{1}
}

func (x *TerminalCreateResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_terminal_proto protoreflect.FileDescriptor

const file_terminal_proto_rawDesc = "" +
	"\n" +
	"\x0eterminal.proto\"s\n" +
	"\x15TerminalCreateRequest\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x12\n" +
	"\x04cols\x18\x03 \x01(\x05R\x04cols\x12\x12\n" +
	"\x04rows\x18\x04 \x01(\x05R\x04rows\"0\n" +
	"\x16TerminalCreateResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06resultB)\n" +
	"\n" +
	"gaiasec.pbP\x01Z\x19gaiasec-nodeagent/pkg/pb/b\x06proto3"

var (
	file_terminal_proto_rawDescOnce sync.Once
	file_terminal_proto_rawDescData []byte
)

func file_terminal_proto_rawDescGZIP() []byte {
	file_terminal_proto_rawDescOnce.Do(func() {
		file_terminal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_terminal_proto_rawDesc), len(file_terminal_proto_rawDesc)))
	})
	return file_terminal_proto_rawDescData
}

var file_terminal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_terminal_proto_goTypes = []any{
	(*TerminalCreateRequest)(nil),  // 0: TerminalCreateRequest
	(*TerminalCreateResponse)(nil), // 1: TerminalCreateResponse
}
var file_terminal_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_terminal_proto_init() }
func file_terminal_proto_init() {
	if File_terminal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_terminal_proto_rawDesc), len(file_terminal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_terminal_proto_goTypes,
		DependencyIndexes: file_terminal_proto_depIdxs,
		MessageInfos:      file_terminal_proto_msgTypes,
	}.Build()
	File_terminal_proto = out.File
	file_terminal_proto_goTypes = nil
	file_terminal_proto_depIdxs = nil
}
