// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: unregister.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Agent注销消息
type Unregister struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unregister) Reset() {
	*x = Unregister{}
	mi := &file_unregister_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unregister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unregister) ProtoMessage() {}

func (x *Unregister) ProtoReflect() protoreflect.Message {
	mi := &file_unregister_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unregister.ProtoReflect.Descriptor instead.
func (*Unregister) Descriptor() ([]byte, []int) {
	return file_unregister_proto_rawDescGZIP(), []int{0}
}

func (x *Unregister) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_unregister_proto protoreflect.FileDescriptor

const file_unregister_proto_rawDesc = "" +
	"\n" +
	"\x10unregister.proto\"\x1c\n" +
	"\n" +
	"Unregister\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02idB)\n" +
	"\n" +
	"sothoth.pbP\x01Z\x19sothoth-nodeagent/pkg/pb/b\x06proto3"

var (
	file_unregister_proto_rawDescOnce sync.Once
	file_unregister_proto_rawDescData []byte
)

func file_unregister_proto_rawDescGZIP() []byte {
	file_unregister_proto_rawDescOnce.Do(func() {
		file_unregister_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_unregister_proto_rawDesc), len(file_unregister_proto_rawDesc)))
	})
	return file_unregister_proto_rawDescData
}

var file_unregister_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_unregister_proto_goTypes = []any{
	(*Unregister)(nil), // 0: Unregister
}
var file_unregister_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_unregister_proto_init() }
func file_unregister_proto_init() {
	if File_unregister_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_unregister_proto_rawDesc), len(file_unregister_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_unregister_proto_goTypes,
		DependencyIndexes: file_unregister_proto_depIdxs,
		MessageInfos:      file_unregister_proto_msgTypes,
	}.Build()
	File_unregister_proto = out.File
	file_unregister_proto_goTypes = nil
	file_unregister_proto_depIdxs = nil
}
