// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: web_routes.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WebAppType int32

const (
	WebAppType_TOMCAT   WebAppType = 0
	WebAppType_JETTY    WebAppType = 1
	WebAppType_UNDERTOW WebAppType = 2
	WebAppType_NETTY    WebAppType = 3
)

// Enum value maps for WebAppType.
var (
	WebAppType_name = map[int32]string{
		0: "TOMCAT",
		1: "JETTY",
		2: "UNDERTOW",
		3: "NETTY",
	}
	WebAppType_value = map[string]int32{
		"TOMCAT":   0,
		"JETTY":    1,
		"UNDERTOW": 2,
		"NETTY":    3,
	}
)

func (x WebAppType) Enum() *WebAppType {
	p := new(WebAppType)
	*p = x
	return p
}

func (x WebAppType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebAppType) Descriptor() protoreflect.EnumDescriptor {
	return file_web_routes_proto_enumTypes[0].Descriptor()
}

func (WebAppType) Type() protoreflect.EnumType {
	return &file_web_routes_proto_enumTypes[0]
}

func (x WebAppType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebAppType.Descriptor instead.
func (WebAppType) EnumDescriptor() ([]byte, []int) {
	return file_web_routes_proto_rawDescGZIP(), []int{0}
}

type WebProcessorType int32

const (
	WebProcessorType_FILTER          WebProcessorType = 0
	WebProcessorType_SERVLET         WebProcessorType = 1
	WebProcessorType_INTERCEPTOR     WebProcessorType = 2
	WebProcessorType_CONTROLLER      WebProcessorType = 3
	WebProcessorType_HENDLER_ADAPTER WebProcessorType = 4
)

// Enum value maps for WebProcessorType.
var (
	WebProcessorType_name = map[int32]string{
		0: "FILTER",
		1: "SERVLET",
		2: "INTERCEPTOR",
		3: "CONTROLLER",
		4: "HENDLER_ADAPTER",
	}
	WebProcessorType_value = map[string]int32{
		"FILTER":          0,
		"SERVLET":         1,
		"INTERCEPTOR":     2,
		"CONTROLLER":      3,
		"HENDLER_ADAPTER": 4,
	}
)

func (x WebProcessorType) Enum() *WebProcessorType {
	p := new(WebProcessorType)
	*p = x
	return p
}

func (x WebProcessorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebProcessorType) Descriptor() protoreflect.EnumDescriptor {
	return file_web_routes_proto_enumTypes[1].Descriptor()
}

func (WebProcessorType) Type() protoreflect.EnumType {
	return &file_web_routes_proto_enumTypes[1]
}

func (x WebProcessorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebProcessorType.Descriptor instead.
func (WebProcessorType) EnumDescriptor() ([]byte, []int) {
	return file_web_routes_proto_rawDescGZIP(), []int{1}
}

type WebFrameworkType int32

const (
	WebFrameworkType_SPRINGMVC WebFrameworkType = 0
)

// Enum value maps for WebFrameworkType.
var (
	WebFrameworkType_name = map[int32]string{
		0: "SPRINGMVC",
	}
	WebFrameworkType_value = map[string]int32{
		"SPRINGMVC": 0,
	}
)

func (x WebFrameworkType) Enum() *WebFrameworkType {
	p := new(WebFrameworkType)
	*p = x
	return p
}

func (x WebFrameworkType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebFrameworkType) Descriptor() protoreflect.EnumDescriptor {
	return file_web_routes_proto_enumTypes[2].Descriptor()
}

func (WebFrameworkType) Type() protoreflect.EnumType {
	return &file_web_routes_proto_enumTypes[2]
}

func (x WebFrameworkType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebFrameworkType.Descriptor instead.
func (WebFrameworkType) EnumDescriptor() ([]byte, []int) {
	return file_web_routes_proto_rawDescGZIP(), []int{2}
}

// 获取Web路由请求
type WebRoutesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebRoutesRequest) Reset() {
	*x = WebRoutesRequest{}
	mi := &file_web_routes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebRoutesRequest) ProtoMessage() {}

func (x *WebRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_routes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebRoutesRequest.ProtoReflect.Descriptor instead.
func (*WebRoutesRequest) Descriptor() ([]byte, []int) {
	return file_web_routes_proto_rawDescGZIP(), []int{0}
}

func (x *WebRoutesRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type WebProcessor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessorType WebProcessorType       `protobuf:"varint,1,opt,name=processor_type,json=processorType,proto3,enum=WebProcessorType" json:"processor_type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Methods       []string               `protobuf:"bytes,3,rep,name=methods,proto3" json:"methods,omitempty"`
	Patterns      []string               `protobuf:"bytes,4,rep,name=patterns,proto3" json:"patterns,omitempty"`
	Handler       string                 `protobuf:"bytes,5,opt,name=handler,proto3" json:"handler,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebProcessor) Reset() {
	*x = WebProcessor{}
	mi := &file_web_routes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebProcessor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebProcessor) ProtoMessage() {}

func (x *WebProcessor) ProtoReflect() protoreflect.Message {
	mi := &file_web_routes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebProcessor.ProtoReflect.Descriptor instead.
func (*WebProcessor) Descriptor() ([]byte, []int) {
	return file_web_routes_proto_rawDescGZIP(), []int{1}
}

func (x *WebProcessor) GetProcessorType() WebProcessorType {
	if x != nil {
		return x.ProcessorType
	}
	return WebProcessorType_FILTER
}

func (x *WebProcessor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WebProcessor) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *WebProcessor) GetPatterns() []string {
	if x != nil {
		return x.Patterns
	}
	return nil
}

func (x *WebProcessor) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

type WebFramework struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrameworkType WebFrameworkType       `protobuf:"varint,1,opt,name=framework_type,json=frameworkType,proto3,enum=WebFrameworkType" json:"framework_type,omitempty"`
	Processors    []*WebProcessor        `protobuf:"bytes,2,rep,name=processors,proto3" json:"processors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebFramework) Reset() {
	*x = WebFramework{}
	mi := &file_web_routes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebFramework) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebFramework) ProtoMessage() {}

func (x *WebFramework) ProtoReflect() protoreflect.Message {
	mi := &file_web_routes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebFramework.ProtoReflect.Descriptor instead.
func (*WebFramework) Descriptor() ([]byte, []int) {
	return file_web_routes_proto_rawDescGZIP(), []int{2}
}

func (x *WebFramework) GetFrameworkType() WebFrameworkType {
	if x != nil {
		return x.FrameworkType
	}
	return WebFrameworkType_SPRINGMVC
}

func (x *WebFramework) GetProcessors() []*WebProcessor {
	if x != nil {
		return x.Processors
	}
	return nil
}

type WebApp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppType       WebAppType             `protobuf:"varint,1,opt,name=app_type,json=appType,proto3,enum=WebAppType" json:"app_type,omitempty"`
	Connectors    []string               `protobuf:"bytes,2,rep,name=connectors,proto3" json:"connectors,omitempty"`
	Context       string                 `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	Docbases      []string               `protobuf:"bytes,4,rep,name=docbases,proto3" json:"docbases,omitempty"`
	Processors    []*WebProcessor        `protobuf:"bytes,5,rep,name=processors,proto3" json:"processors,omitempty"`
	Frameworks    []*WebFramework        `protobuf:"bytes,6,rep,name=frameworks,proto3" json:"frameworks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebApp) Reset() {
	*x = WebApp{}
	mi := &file_web_routes_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebApp) ProtoMessage() {}

func (x *WebApp) ProtoReflect() protoreflect.Message {
	mi := &file_web_routes_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebApp.ProtoReflect.Descriptor instead.
func (*WebApp) Descriptor() ([]byte, []int) {
	return file_web_routes_proto_rawDescGZIP(), []int{3}
}

func (x *WebApp) GetAppType() WebAppType {
	if x != nil {
		return x.AppType
	}
	return WebAppType_TOMCAT
}

func (x *WebApp) GetConnectors() []string {
	if x != nil {
		return x.Connectors
	}
	return nil
}

func (x *WebApp) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *WebApp) GetDocbases() []string {
	if x != nil {
		return x.Docbases
	}
	return nil
}

func (x *WebApp) GetProcessors() []*WebProcessor {
	if x != nil {
		return x.Processors
	}
	return nil
}

func (x *WebApp) GetFrameworks() []*WebFramework {
	if x != nil {
		return x.Frameworks
	}
	return nil
}

// 获取WebRoutes响应
type WebRoutesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Webapps       []*WebApp              `protobuf:"bytes,2,rep,name=webapps,proto3" json:"webapps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebRoutesResponse) Reset() {
	*x = WebRoutesResponse{}
	mi := &file_web_routes_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebRoutesResponse) ProtoMessage() {}

func (x *WebRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_routes_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebRoutesResponse.ProtoReflect.Descriptor instead.
func (*WebRoutesResponse) Descriptor() ([]byte, []int) {
	return file_web_routes_proto_rawDescGZIP(), []int{4}
}

func (x *WebRoutesResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *WebRoutesResponse) GetWebapps() []*WebApp {
	if x != nil {
		return x.Webapps
	}
	return nil
}

var File_web_routes_proto protoreflect.FileDescriptor

const file_web_routes_proto_rawDesc = "" +
	"\n" +
	"\x10web_routes.proto\"+\n" +
	"\x10WebRoutesRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\xac\x01\n" +
	"\fWebProcessor\x128\n" +
	"\x0eprocessor_type\x18\x01 \x01(\x0e2\x11.WebProcessorTypeR\rprocessorType\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\amethods\x18\x03 \x03(\tR\amethods\x12\x1a\n" +
	"\bpatterns\x18\x04 \x03(\tR\bpatterns\x12\x18\n" +
	"\ahandler\x18\x05 \x01(\tR\ahandler\"w\n" +
	"\fWebFramework\x128\n" +
	"\x0eframework_type\x18\x01 \x01(\x0e2\x11.WebFrameworkTypeR\rframeworkType\x12-\n" +
	"\n" +
	"processors\x18\x02 \x03(\v2\r.WebProcessorR\n" +
	"processors\"\xe4\x01\n" +
	"\x06WebApp\x12&\n" +
	"\bapp_type\x18\x01 \x01(\x0e2\v.WebAppTypeR\aappType\x12\x1e\n" +
	"\n" +
	"connectors\x18\x02 \x03(\tR\n" +
	"connectors\x12\x18\n" +
	"\acontext\x18\x03 \x01(\tR\acontext\x12\x1a\n" +
	"\bdocbases\x18\x04 \x03(\tR\bdocbases\x12-\n" +
	"\n" +
	"processors\x18\x05 \x03(\v2\r.WebProcessorR\n" +
	"processors\x12-\n" +
	"\n" +
	"frameworks\x18\x06 \x03(\v2\r.WebFrameworkR\n" +
	"frameworks\"O\n" +
	"\x11WebRoutesResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12!\n" +
	"\awebapps\x18\x02 \x03(\v2\a.WebAppR\awebapps*<\n" +
	"\n" +
	"WebAppType\x12\n" +
	"\n" +
	"\x06TOMCAT\x10\x00\x12\t\n" +
	"\x05JETTY\x10\x01\x12\f\n" +
	"\bUNDERTOW\x10\x02\x12\t\n" +
	"\x05NETTY\x10\x03*a\n" +
	"\x10WebProcessorType\x12\n" +
	"\n" +
	"\x06FILTER\x10\x00\x12\v\n" +
	"\aSERVLET\x10\x01\x12\x0f\n" +
	"\vINTERCEPTOR\x10\x02\x12\x0e\n" +
	"\n" +
	"CONTROLLER\x10\x03\x12\x13\n" +
	"\x0fHENDLER_ADAPTER\x10\x04*!\n" +
	"\x10WebFrameworkType\x12\r\n" +
	"\tSPRINGMVC\x10\x00B)\n" +
	"\n" +
	"sothoth.pbP\x01Z\x19sothoth-nodeagent/pkg/pb/b\x06proto3"

var (
	file_web_routes_proto_rawDescOnce sync.Once
	file_web_routes_proto_rawDescData []byte
)

func file_web_routes_proto_rawDescGZIP() []byte {
	file_web_routes_proto_rawDescOnce.Do(func() {
		file_web_routes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_web_routes_proto_rawDesc), len(file_web_routes_proto_rawDesc)))
	})
	return file_web_routes_proto_rawDescData
}

var file_web_routes_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_web_routes_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_web_routes_proto_goTypes = []any{
	(WebAppType)(0),           // 0: WebAppType
	(WebProcessorType)(0),     // 1: WebProcessorType
	(WebFrameworkType)(0),     // 2: WebFrameworkType
	(*WebRoutesRequest)(nil),  // 3: WebRoutesRequest
	(*WebProcessor)(nil),      // 4: WebProcessor
	(*WebFramework)(nil),      // 5: WebFramework
	(*WebApp)(nil),            // 6: WebApp
	(*WebRoutesResponse)(nil), // 7: WebRoutesResponse
}
var file_web_routes_proto_depIdxs = []int32{
	1, // 0: WebProcessor.processor_type:type_name -> WebProcessorType
	2, // 1: WebFramework.framework_type:type_name -> WebFrameworkType
	4, // 2: WebFramework.processors:type_name -> WebProcessor
	0, // 3: WebApp.app_type:type_name -> WebAppType
	4, // 4: WebApp.processors:type_name -> WebProcessor
	5, // 5: WebApp.frameworks:type_name -> WebFramework
	6, // 6: WebRoutesResponse.webapps:type_name -> WebApp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_web_routes_proto_init() }
func file_web_routes_proto_init() {
	if File_web_routes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_web_routes_proto_rawDesc), len(file_web_routes_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_web_routes_proto_goTypes,
		DependencyIndexes: file_web_routes_proto_depIdxs,
		EnumInfos:         file_web_routes_proto_enumTypes,
		MessageInfos:      file_web_routes_proto_msgTypes,
	}.Build()
	File_web_routes_proto = out.File
	file_web_routes_proto_goTypes = nil
	file_web_routes_proto_depIdxs = nil
}
