// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: web_routes.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WebAppType int32

const (
	WebAppType_Tomcat   WebAppType = 0
	WebAppType_Jetty    WebAppType = 1
	WebAppType_Undertow WebAppType = 2
	WebAppType_Netty    WebAppType = 3
	WebAppType_Nuwa     WebAppType = 4
	WebAppType_Nginx    WebAppType = 5
	WebAppType_Hiro     WebAppType = 6
)

// Enum value maps for WebAppType.
var (
	WebAppType_name = map[int32]string{
		0: "Tomcat",
		1: "Jetty",
		2: "Undertow",
		3: "Netty",
		4: "Nuwa",
		5: "Nginx",
		6: "Hiro",
	}
	WebAppType_value = map[string]int32{
		"Tomcat":   0,
		"Jetty":    1,
		"Undertow": 2,
		"Netty":    3,
		"Nuwa":     4,
		"Nginx":    5,
		"Hiro":     6,
	}
)

func (x WebAppType) Enum() *WebAppType {
	p := new(WebAppType)
	*p = x
	return p
}

func (x WebAppType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebAppType) Descriptor() protoreflect.EnumDescriptor {
	return file_web_routes_proto_enumTypes[0].Descriptor()
}

func (WebAppType) Type() protoreflect.EnumType {
	return &file_web_routes_proto_enumTypes[0]
}

func (x WebAppType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebAppType.Descriptor instead.
func (WebAppType) EnumDescriptor() ([]byte, []int) {
	return file_web_routes_proto_rawDescGZIP(), []int{0}
}

type WebProcessorType int32

const (
	WebProcessorType_Filter         WebProcessorType = 0
	WebProcessorType_Servlet        WebProcessorType = 1
	WebProcessorType_Listener       WebProcessorType = 2
	WebProcessorType_Interceptor    WebProcessorType = 3
	WebProcessorType_Controller     WebProcessorType = 4
	WebProcessorType_HendlerAdapter WebProcessorType = 5
)

// Enum value maps for WebProcessorType.
var (
	WebProcessorType_name = map[int32]string{
		0: "Filter",
		1: "Servlet",
		2: "Listener",
		3: "Interceptor",
		4: "Controller",
		5: "HendlerAdapter",
	}
	WebProcessorType_value = map[string]int32{
		"Filter":         0,
		"Servlet":        1,
		"Listener":       2,
		"Interceptor":    3,
		"Controller":     4,
		"HendlerAdapter": 5,
	}
)

func (x WebProcessorType) Enum() *WebProcessorType {
	p := new(WebProcessorType)
	*p = x
	return p
}

func (x WebProcessorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebProcessorType) Descriptor() protoreflect.EnumDescriptor {
	return file_web_routes_proto_enumTypes[1].Descriptor()
}

func (WebProcessorType) Type() protoreflect.EnumType {
	return &file_web_routes_proto_enumTypes[1]
}

func (x WebProcessorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebProcessorType.Descriptor instead.
func (WebProcessorType) EnumDescriptor() ([]byte, []int) {
	return file_web_routes_proto_rawDescGZIP(), []int{1}
}

type WebFrameworkType int32

const (
	WebFrameworkType_SpringMvc WebFrameworkType = 0
	WebFrameworkType_Struts    WebFrameworkType = 1
	WebFrameworkType_CloudSOP  WebFrameworkType = 2
)

// Enum value maps for WebFrameworkType.
var (
	WebFrameworkType_name = map[int32]string{
		0: "SpringMvc",
		1: "Struts",
		2: "CloudSOP",
	}
	WebFrameworkType_value = map[string]int32{
		"SpringMvc": 0,
		"Struts":    1,
		"CloudSOP":  2,
	}
)

func (x WebFrameworkType) Enum() *WebFrameworkType {
	p := new(WebFrameworkType)
	*p = x
	return p
}

func (x WebFrameworkType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebFrameworkType) Descriptor() protoreflect.EnumDescriptor {
	return file_web_routes_proto_enumTypes[2].Descriptor()
}

func (WebFrameworkType) Type() protoreflect.EnumType {
	return &file_web_routes_proto_enumTypes[2]
}

func (x WebFrameworkType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebFrameworkType.Descriptor instead.
func (WebFrameworkType) EnumDescriptor() ([]byte, []int) {
	return file_web_routes_proto_rawDescGZIP(), []int{2}
}

type WebProcessor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessorType WebProcessorType       `protobuf:"varint,1,opt,name=processor_type,json=processorType,proto3,enum=WebProcessorType" json:"processor_type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Methods       []string               `protobuf:"bytes,3,rep,name=methods,proto3" json:"methods,omitempty"`
	Patterns      []string               `protobuf:"bytes,4,rep,name=patterns,proto3" json:"patterns,omitempty"`
	Handler       string                 `protobuf:"bytes,5,opt,name=handler,proto3" json:"handler,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	InputSchema   string                 `protobuf:"bytes,7,opt,name=input_schema,json=inputSchema,proto3" json:"input_schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebProcessor) Reset() {
	*x = WebProcessor{}
	mi := &file_web_routes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebProcessor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebProcessor) ProtoMessage() {}

func (x *WebProcessor) ProtoReflect() protoreflect.Message {
	mi := &file_web_routes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebProcessor.ProtoReflect.Descriptor instead.
func (*WebProcessor) Descriptor() ([]byte, []int) {
	return file_web_routes_proto_rawDescGZIP(), []int{0}
}

func (x *WebProcessor) GetProcessorType() WebProcessorType {
	if x != nil {
		return x.ProcessorType
	}
	return WebProcessorType_Filter
}

func (x *WebProcessor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WebProcessor) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *WebProcessor) GetPatterns() []string {
	if x != nil {
		return x.Patterns
	}
	return nil
}

func (x *WebProcessor) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

func (x *WebProcessor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WebProcessor) GetInputSchema() string {
	if x != nil {
		return x.InputSchema
	}
	return ""
}

type WebFramework struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrameworkType WebFrameworkType       `protobuf:"varint,1,opt,name=framework_type,json=frameworkType,proto3,enum=WebFrameworkType" json:"framework_type,omitempty"`
	Processors    []*WebProcessor        `protobuf:"bytes,2,rep,name=processors,proto3" json:"processors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebFramework) Reset() {
	*x = WebFramework{}
	mi := &file_web_routes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebFramework) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebFramework) ProtoMessage() {}

func (x *WebFramework) ProtoReflect() protoreflect.Message {
	mi := &file_web_routes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebFramework.ProtoReflect.Descriptor instead.
func (*WebFramework) Descriptor() ([]byte, []int) {
	return file_web_routes_proto_rawDescGZIP(), []int{1}
}

func (x *WebFramework) GetFrameworkType() WebFrameworkType {
	if x != nil {
		return x.FrameworkType
	}
	return WebFrameworkType_SpringMvc
}

func (x *WebFramework) GetProcessors() []*WebProcessor {
	if x != nil {
		return x.Processors
	}
	return nil
}

type WebApp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppType       WebAppType             `protobuf:"varint,1,opt,name=app_type,json=appType,proto3,enum=WebAppType" json:"app_type,omitempty"`
	Connectors    []string               `protobuf:"bytes,2,rep,name=connectors,proto3" json:"connectors,omitempty"`
	Context       string                 `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	Docbases      []string               `protobuf:"bytes,4,rep,name=docbases,proto3" json:"docbases,omitempty"`
	Processors    []*WebProcessor        `protobuf:"bytes,5,rep,name=processors,proto3" json:"processors,omitempty"`
	Frameworks    []*WebFramework        `protobuf:"bytes,6,rep,name=frameworks,proto3" json:"frameworks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebApp) Reset() {
	*x = WebApp{}
	mi := &file_web_routes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebApp) ProtoMessage() {}

func (x *WebApp) ProtoReflect() protoreflect.Message {
	mi := &file_web_routes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebApp.ProtoReflect.Descriptor instead.
func (*WebApp) Descriptor() ([]byte, []int) {
	return file_web_routes_proto_rawDescGZIP(), []int{2}
}

func (x *WebApp) GetAppType() WebAppType {
	if x != nil {
		return x.AppType
	}
	return WebAppType_Tomcat
}

func (x *WebApp) GetConnectors() []string {
	if x != nil {
		return x.Connectors
	}
	return nil
}

func (x *WebApp) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *WebApp) GetDocbases() []string {
	if x != nil {
		return x.Docbases
	}
	return nil
}

func (x *WebApp) GetProcessors() []*WebProcessor {
	if x != nil {
		return x.Processors
	}
	return nil
}

func (x *WebApp) GetFrameworks() []*WebFramework {
	if x != nil {
		return x.Frameworks
	}
	return nil
}

// 获取WebRoutes响应
type WebRoutesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Webapps       []*WebApp              `protobuf:"bytes,1,rep,name=webapps,proto3" json:"webapps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebRoutesResponse) Reset() {
	*x = WebRoutesResponse{}
	mi := &file_web_routes_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebRoutesResponse) ProtoMessage() {}

func (x *WebRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_routes_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebRoutesResponse.ProtoReflect.Descriptor instead.
func (*WebRoutesResponse) Descriptor() ([]byte, []int) {
	return file_web_routes_proto_rawDescGZIP(), []int{3}
}

func (x *WebRoutesResponse) GetWebapps() []*WebApp {
	if x != nil {
		return x.Webapps
	}
	return nil
}

var File_web_routes_proto protoreflect.FileDescriptor

const file_web_routes_proto_rawDesc = "" +
	"\n" +
	"\x10web_routes.proto\"\xf1\x01\n" +
	"\fWebProcessor\x128\n" +
	"\x0eprocessor_type\x18\x01 \x01(\x0e2\x11.WebProcessorTypeR\rprocessorType\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\amethods\x18\x03 \x03(\tR\amethods\x12\x1a\n" +
	"\bpatterns\x18\x04 \x03(\tR\bpatterns\x12\x18\n" +
	"\ahandler\x18\x05 \x01(\tR\ahandler\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12!\n" +
	"\finput_schema\x18\a \x01(\tR\vinputSchema\"w\n" +
	"\fWebFramework\x128\n" +
	"\x0eframework_type\x18\x01 \x01(\x0e2\x11.WebFrameworkTypeR\rframeworkType\x12-\n" +
	"\n" +
	"processors\x18\x02 \x03(\v2\r.WebProcessorR\n" +
	"processors\"\xe4\x01\n" +
	"\x06WebApp\x12&\n" +
	"\bapp_type\x18\x01 \x01(\x0e2\v.WebAppTypeR\aappType\x12\x1e\n" +
	"\n" +
	"connectors\x18\x02 \x03(\tR\n" +
	"connectors\x12\x18\n" +
	"\acontext\x18\x03 \x01(\tR\acontext\x12\x1a\n" +
	"\bdocbases\x18\x04 \x03(\tR\bdocbases\x12-\n" +
	"\n" +
	"processors\x18\x05 \x03(\v2\r.WebProcessorR\n" +
	"processors\x12-\n" +
	"\n" +
	"frameworks\x18\x06 \x03(\v2\r.WebFrameworkR\n" +
	"frameworks\"6\n" +
	"\x11WebRoutesResponse\x12!\n" +
	"\awebapps\x18\x01 \x03(\v2\a.WebAppR\awebapps*[\n" +
	"\n" +
	"WebAppType\x12\n" +
	"\n" +
	"\x06Tomcat\x10\x00\x12\t\n" +
	"\x05Jetty\x10\x01\x12\f\n" +
	"\bUndertow\x10\x02\x12\t\n" +
	"\x05Netty\x10\x03\x12\b\n" +
	"\x04Nuwa\x10\x04\x12\t\n" +
	"\x05Nginx\x10\x05\x12\b\n" +
	"\x04Hiro\x10\x06*n\n" +
	"\x10WebProcessorType\x12\n" +
	"\n" +
	"\x06Filter\x10\x00\x12\v\n" +
	"\aServlet\x10\x01\x12\f\n" +
	"\bListener\x10\x02\x12\x0f\n" +
	"\vInterceptor\x10\x03\x12\x0e\n" +
	"\n" +
	"Controller\x10\x04\x12\x12\n" +
	"\x0eHendlerAdapter\x10\x05*;\n" +
	"\x10WebFrameworkType\x12\r\n" +
	"\tSpringMvc\x10\x00\x12\n" +
	"\n" +
	"\x06Struts\x10\x01\x12\f\n" +
	"\bCloudSOP\x10\x02B)\n" +
	"\n" +
	"gaiasec.pbP\x01Z\x19gaiasec-nodeagent/pkg/pb/b\x06proto3"

var (
	file_web_routes_proto_rawDescOnce sync.Once
	file_web_routes_proto_rawDescData []byte
)

func file_web_routes_proto_rawDescGZIP() []byte {
	file_web_routes_proto_rawDescOnce.Do(func() {
		file_web_routes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_web_routes_proto_rawDesc), len(file_web_routes_proto_rawDesc)))
	})
	return file_web_routes_proto_rawDescData
}

var file_web_routes_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_web_routes_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_web_routes_proto_goTypes = []any{
	(WebAppType)(0),           // 0: WebAppType
	(WebProcessorType)(0),     // 1: WebProcessorType
	(WebFrameworkType)(0),     // 2: WebFrameworkType
	(*WebProcessor)(nil),      // 3: WebProcessor
	(*WebFramework)(nil),      // 4: WebFramework
	(*WebApp)(nil),            // 5: WebApp
	(*WebRoutesResponse)(nil), // 6: WebRoutesResponse
}
var file_web_routes_proto_depIdxs = []int32{
	1, // 0: WebProcessor.processor_type:type_name -> WebProcessorType
	2, // 1: WebFramework.framework_type:type_name -> WebFrameworkType
	3, // 2: WebFramework.processors:type_name -> WebProcessor
	0, // 3: WebApp.app_type:type_name -> WebAppType
	3, // 4: WebApp.processors:type_name -> WebProcessor
	4, // 5: WebApp.frameworks:type_name -> WebFramework
	5, // 6: WebRoutesResponse.webapps:type_name -> WebApp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_web_routes_proto_init() }
func file_web_routes_proto_init() {
	if File_web_routes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_web_routes_proto_rawDesc), len(file_web_routes_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_web_routes_proto_goTypes,
		DependencyIndexes: file_web_routes_proto_depIdxs,
		EnumInfos:         file_web_routes_proto_enumTypes,
		MessageInfos:      file_web_routes_proto_msgTypes,
	}.Build()
	File_web_routes_proto = out.File
	file_web_routes_proto_goTypes = nil
	file_web_routes_proto_depIdxs = nil
}
